### PR TITLE
Kernel 4.16.1 and Buildroot 2018.02.1 stable release

### PR DESCRIPTION
**Pull request by shenki**

### CODE REVIEW

**Comment by shenki** [comment]
retest this please

**Comment by shenki** [comment]
retest this please

**Comment by shenki** [comment]
"IBM OP CI HW IPL test -- p9" and "IBM OP CI HW IPL test -- p9" look broken, and I can't tell where the failure is happening. Given it aborted so quickly after triggering I think this is a CI problem, not a problem with the PR.

**Comment by sammj** [comment]
```
Unable to get pull request builder trigger!!
Setting status of dd7183c7077dd3445e0c00dd7c3cd33bd50c4860 to FAILURE with url https://hostboot-jenkins.swg-devops.com/job/Hostboot/job/OpenPower/job/HW/job/p9-main/8206/ and message: 'Failed to boot one or more systems with built PNOR images.  See Jenkins console log for details.
```
Yup

**Comment by sammj** [comment]
Digging down a little more:
```
FAIL: Host Code Update.REST Host Code Update
File '/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/HW/p9-test-param__2/test_images/witherspoon/witherspoon.pnor.squashfs.tar' does not exist.
```

**Comment by shenki** [comment]
The "Build test" CI romulus hostboot build failed due to:

```
../common/xmltohb/handle_duplicate.pl \
--ekbXmlFile=../../../../obj/genfiles/attribute_types_ekb.xml \
--hbXmlFile=../../../../obj/genfiles/attribute_types_src.xml \
--fapi2Header=../../../../src/include/usr/fapi2/attribute_service.H \
--outFile=../../../../obj/genfiles/attribute_types_full.xml \
        --verbose
```
```
no element found at line 27781, column 56, byte 770048 at /usr/lib/powerpc64le-linux-gnu/perl5/5.22/XML/Parser.pm line 187.
XML::Simple called at ../common/xmltohb/handle_duplicate.pl line 99.
makefile:375: recipe for target '../../../../obj/genfiles/attribute_types_full.xml' failed
```

**Comment by stewart-ibm** [comment]
Joel Stanley <notifications@github.com> writes:
> "IBM OP CI HW IPL test -- p9" and "IBM OP CI HW IPL test -- p9" look
> broken, and I can't tell where the failure is happening. Given it
> aborted so quickly after triggering I think this is a CI problem, not
> a problem with the PR.

It's been broken for a while. I've pinged Ravi on it, hopefully somebody
is looking at it. Looks to be OpenBMC not flashing things correctly, but
who knows what's going on with :robot:

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by stewart-ibm** [comment]
Joel Stanley <notifications@github.com> writes:
> The "Build test" CI romulus hostboot build failed due to:
>
> ```
> ../common/xmltohb/handle_duplicate.pl \
> --ekbXmlFile=../../../../obj/genfiles/attribute_types_ekb.xml \
> --hbXmlFile=../../../../obj/genfiles/attribute_types_src.xml \
> --fapi2Header=../../../../src/include/usr/fapi2/attribute_service.H \
> --outFile=../../../../obj/genfiles/attribute_types_full.xml \
>         --verbose
> ```
> ```
> no element found at line 27781, column 56, byte 770048 at /usr/lib/powerpc64le-linux-gnu/perl5/5.22/XML/Parser.pm line 187.
> XML::Simple called at ../common/xmltohb/handle_duplicate.pl line 99.
> makefile:375: recipe for target '../../../../obj/genfiles/attribute_types_full.xml' failed
> ```

Looks to be some kind of spurious/random Hostboot problem. Urgh... Then
again, I never build Romulus and all this CI has been pretty damn broken
for a while now.

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by stewart-ibm** [comment]
merged in as a1e66746b17e9530dd558e3c3096d92e380e41dc

**Pull request closed without merging**
