### PR TITLE
Make installing 30-dtb_updates depend on BR2_PACKAGE_DTC

### PR DESCRIPTION
**Pull request by ArthurHeymans**
30-dtb_updates is only created when dtc is selected.

Signed-off-by: Arthur Heymans arthur@aheymans.xyz

---

This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/697)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
ok to test

**Comment by jazurin** [comment]
@stewart-ibm you were not in the admin list in the Jenkins project that runs the CI.  But I just added you so you should be able to authorize testing from now on.
ok to test

**Comment by e-liner** [comment]
Looks like there's an issue with the change on line 75:

make: Leaving directory `/tmp/hostboot/jenkins-slave/workspace/op_build_ghprb_trigger_multi/CONFIG/palmetto/OS/rhel6.4/op-build/buildroot'
make: Entering directory `/tmp/hostboot/jenkins-slave/workspace/op_build_ghprb_trigger_multi/CONFIG/palmetto/OS/rhel6.4/op-build/buildroot'
/tmp/hostboot/jenkins-slave/workspace/op_build_ghprb_trigger_multi/CONFIG/palmetto/OS/rhel6.4/op-build/openpower/package/petitboot/petitboot.mk:75: *** commands commence before first target.  Stop.
make: *** [_all] Error 2
make: Leaving directory `/tmp/hostboot/jenkins-slave/workspace/op_build_ghprb_trigger_multi/CONFIG/palmetto/OS/rhel6.4/op-build/buildroot'
Build step 'Execute shell' marked build as failure
Skipped archiving because build is not successful
Sending e-mails to: jmazurin@us.ibm.com

I think you just need to add a \ at the end of line 74.

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
@ArthurHeymans are you able to fix the build problem mentioned above?

**Comment by e-liner** [comment]
ok to test

**Comment by sammj** [comment]
Retest this please

**Comment by sammj** [comment]
This is superseded by https://github.com/open-power/op-build/pull/1032

**Comment by sammj** [comment]
With https://github.com/open-power/op-build/pull/1032 merged this should be closed.

**Pull request closed without merging**
