### PR TITLE
Allow "Security Version" To Be Set For A Given Configuration

### PR DESCRIPTION
**Pull request by mabaiocchi**
This commit allows for a given configuration/system to set an optional
"Security Version" value.  It specifically sets the value of the Boston
(p9dsu) configuration to zero.  This value then gets passed into the
openpower-pnor package and is built into the PNOR partitions via the
signing utilities.

Signed-off-by: Mike Baiocchi <mbaiocch@us.ibm.com>

### CODE REVIEW

**Comment by mabaiocchi** [comment]
retest this please

**Comment by mabaiocchi** [comment]
@klauskiwi, I was sent your direction via @cvswen for this Travis CI fail.  He thought the test might have to be updated somehow to pass?

It seems to be tripping over the one line I added to openpower/configs/p9dsu_defconfig:
+ BR2_OPENPOWER_SIGNED_SECURITY_VERSION="0"

Corey and I cannot figure out why this change is an issue.  Please advise.  Thank you.

(CC @cjengel @bofferdn @dcrowell77 )

**Comment by klauskiwi** [comment]
> 
> 
> @klauskiwi, I was sent your direction via @cvswen for this Travis CI fail. He thought the test might have to be updated somehow to pass?
> 
> It seems to be tripping over the one line I added to openpower/configs/p9dsu_defconfig:
> 
>     * BR2_OPENPOWER_SIGNED_SECURITY_VERSION="0"
> 
> 
> Corey and I cannot figure out why this change is an issue. Please advise. Thank you.
> 
> (CC @cjengel @bofferdn @dcrowell77 )

When changing Config.in options, one must update the _defconfig files to make sure they are in order, and with the minimum number of options set etc..

All you need to do is `./op-build p9dsu_defconfig && ./op-build savedefconfig` followed by a `git commit -as`..

if you need to change the config on all the defconfigs, the `openpower/script/update-defconfigs.sh` can be used to automate that.

**Comment by stewartsmith** [comment]
Where's the documentation additions explaining what this is, the significance of it, and how other platforms consume it?

**Comment by mabaiocchi** [comment]
@klauskiwi thank you for your reply.  Your commands allowed me to fix the issue - very much appreciated.

@stewartsmith at this time, this is a dedicated change to the Boston (p9dsu) config on an old op-build environment.  We are not ready to upstream this yet.  When we do, we'll provide full documentation on this issue.

**Review by bofferdn — APPROVED** [review]

**Pull request merged**
