### PR TITLE
nicole_config: Bump version of machine xml

### PR DESCRIPTION
**Pull request by artemsen**
Artem Senichev (1):
      Add WOF table for POWER9 Sforza module

Signed-off-by: Artem Senichev <a.senichev@yadro.com>

### CODE REVIEW

**Comment by cvswen** [comment]
ok to test

**Comment by cvswen** [comment]
retest this please

**Comment by cvswen** [comment]
ok to test

**Comment by camvanng** [comment]
add to whitelist

**Comment by shenki** [comment]
retest this please

**Pull request merged**
