### PR TITLE
linux: Release 4.4.13-openpower1

### PR DESCRIPTION
**Pull request by shenki**
Signed-off-by: Joel Stanley <joel@jms.id.au>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/497)

### CODE REVIEW

**Comment by williamspatrick** [comment]
Looks good to merge assuming we get the pervasive build issue figured out.  @jazurin

**Comment by jazurin** [comment]
retest this please

**Comment by stewart-ibm** [comment]
@shenki - it looks like you forgot to commit the associated buildroot bump to get 4.4.13 as the default

**Comment by shenki** [comment]
@stewart-ibm You're correct. My local tree is using the latest buildroot. Do we want to move to that as well?

**Comment by stewart-ibm** [comment]
@shenki I'd be okay with that.

**Comment by jazurin** [comment]
retest this please

**Comment by jazurin** [comment]
@shenki @stewart-ibm I reran the build and it failed again in the same place.  This is not related to the package download issue seen on other builds failures.  This build is running on an Ubuntu 14.10 ppcle node.  Looks like buildpnor.pl is failing.

`ERROR: Specified input file (/tmp/hostboot/jenkins-slave/workspace/op_build_ghprb_trigger/output/images/zImage.epapr) for key (BOOTKERNEL) does not exist.  Aborting! at /tmp/hostboot/jenkins-slave/workspace/op_build_ghprb_trigger/output/host/usr/powerpc64le-buildroot-linux-gnu/sysroot/hostboot_build_images//buildpnor.pl line 668.`

You can see the complete build log here:
http://gfw160.aus.stglabs.ibm.com:8088/jenkins/job/op_build_ghprb_trigger/226/console
and here:
http://gfw160.aus.stglabs.ibm.com:8088/jenkins/job/op_build_ghprb_trigger/225/console

**Comment by stewart-ibm** [comment]
@jazurin yes, @shenki needs to push the updated buildroot before this merge will pass.

**Comment by shenki** [comment]
Superseded by #504

**Pull request closed without merging**
