### PR TITLE
linux p9_defconfig: disable NFS, CIFS, RAW, ATA over Ethernet, /dev/mem

### PR DESCRIPTION
**Pull request by stewart-ibm**
Cc: @shenki @sammj @jk-ozlabs 

It appears the NUMA move-around is because of savedefconfig.

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/965)

### CODE REVIEW

**Comment by shenki** [comment]
You're removing the sparsemem changes we recently added. Is this intentional?

**Comment by shenki** [comment]
This is the diff from a `make skiroot_p9_defconfig && make savedefconfg`:
```
--- a/openpower/configs/linux/skiroot_p9_defconfig
+++ b/openpower/configs/linux/skiroot_p9_defconfig
@@ -43,6 +43,7 @@ CONFIG_GEN_RTC=y
 CONFIG_HZ_100=y
 CONFIG_KEXEC=y
 CONFIG_IRQ_ALL_CPUS=y
+CONFIG_NUMA=y
 # CONFIG_COMPACTION is not set
 # CONFIG_MIGRATION is not set
 # CONFIG_BOUNCE is not set
@@ -232,12 +233,3 @@ CONFIG_CRYPTO_MD4=y
 CONFIG_CRYPTO_ARC4=y
 CONFIG_CRYPTO_DES=y
 # CONFIG_CRYPTO_HW is not set
-CONFIG_SELECT_MEMORY_MODEL=y
-CONFIG_SPARSEMEM_MANUAL=y
-CONFIG_SPARSEMEM=y
-CONFIG_SPARSEMEM_EXTREME=y
-CONFIG_SPARSEMEM_VMEMMAP_ENABLE=y
-CONFIG_SPARSEMEM_VMEMMAP=y
-CONFIG_NUMA=y
-CONFIG_NEED_MULTIPLE_NODES=y
-CONFIG_HAVE_MEMORY_PRESENT=y
```

Someone has been adding stuff to the defconfig manually, which is not how defconfigs work.

**Comment by stewart-ibm** [comment]
The sparsemem changes may be default if NUMA=y ? It's what comes out of savedefconfig, I didn't actually touch them myself.

**Comment by stewart-ibm** [comment]
@shenki yeah, this occurred in ba1f1dcb6fea2257ebb10c0181d10540f98af1f8

So I think we're safe with this change, as long as we don't want NFS or CIFS, which I think a grand total of zero people have used.

**Pull request merged**
