### PR TITLE
witherspoon: enable keyutils in bootloader

### PR DESCRIPTION
**Pull request by naynajain**
keyutils package provides keyctl utility which can be
used to look at kernel keyrings. This patch enables
including this utility in bootloader.

Signed-off-by: Eric Richter<erichte@linux.ibm.com>
Signed-off-by: Nayna Jain <nayna@linux.ibm.com>

### CODE REVIEW

**Comment by klauskiwi** [comment]
ok to test

**Comment by klauskiwi** [comment]
@naynajain this looks good, but it failed the defconfig test.. the correct method for changing defconfig files is:
```./op-build witherspoon_defconfig
./op-build menuconfig
(make the change)
./op-build savedefconfig
(git commit the saved config>
```
In addition to the above, can you expand a bit on the justification for that package? Is it needed for secure & trusted boot? If that's true, wouldn't it be better we enable this only when we're ready to enable STB overall?

Thanks

**Comment by naynajain** [comment]
> @naynajain this looks good, but it failed the defconfig test.. the correct method for changing defconfig files is:
> 
> ```
> ./op-build menuconfig
> (make the change)
> ./op-build savedefconfig
> (git commit the saved config>
> ```

Sure.. will fix this and push again.

> In addition to the above, can you expand a bit on the justification for that package? Is it needed for secure & trusted boot? If that's true, wouldn't it be better we enable this only when we're ready to enable STB overall?

Yes, mainly it is going to be used for secureboot.  Enabling it without secure boot would not have any side effects, just that it would not be used.

We already have secureboot enablement patches in skiroot and petitboot for op-build. So, I didn't understand exactly what you mean by "when we enable STB overall" ?  I don't think there is specific witherspoon config for that. 

Thanks & Regards,
      - Nayna

**Comment by klauskiwi** [comment]
> > In addition to the above, can you expand a bit on the justification for that package? Is it needed for secure & trusted boot? If that's true, wouldn't it be better we enable this only when we're ready to enable STB overall?
> 
> Yes, mainly it is going to be used for secureboot. Enabling it without secure boot would not have any side effects, just that it would not be used.
> 
> We already have secureboot enablement patches in skiroot and petitboot for op-build. So, I didn't understand exactly what you mean by "when we enable STB overall" ? I don't think there is specific witherspoon config for that.
> 

If current upstream op-build is already including the necessary skiroot, skiboot and petitboot pieces, I thought that there would be some _defconfig flag enabling STB by default, and we'd only want to add keyutils if we had the STB flag enabled..

But I haven't been following the STB enablement mechanism closely, perhaps it's always available (if those pieces are present in op-build build-time) and something in runtime enables it?

**Comment by naynajain** [comment]
> > > In addition to the above, can you expand a bit on the justification for that package? Is it needed for secure & trusted boot? If that's true, wouldn't it be better we enable this only when we're ready to enable STB overall?
> > 
> > 
> > Yes, mainly it is going to be used for secureboot. Enabling it without secure boot would not have any side effects, just that it would not be used.
> > We already have secureboot enablement patches in skiroot and petitboot for op-build. So, I didn't understand exactly what you mean by "when we enable STB overall" ? I don't think there is specific witherspoon config for that.
> 
> If current upstream op-build is already including the necessary skiroot, skiboot and petitboot pieces, I thought that there would be some _defconfig flag enabling STB by default, and we'd only want to add keyutils if we had the STB flag enabled..
> 
> But I haven't been following the STB enablement mechanism closely, perhaps it's always available (if those pieces are present in op-build build-time) and something in runtime enables it?

Yes, the secureboot enablement is runtime by skiboot for the given platform. Currently, except skiboot patches all other patches are available in op-build. 

Thanks & Regards,
     - Nayna

**Comment by klauskiwi** [comment]
> Yes, the secureboot enablement is runtime by skiboot for the given platform. Currently, except skiboot patches all other patches are available in op-build.
> 

What about the p9layout.xml changes, I thought they were necessary?

Let's get all dependencies merged on op-build first before we enable this additional package.

Thanks

**Comment by naynajain** [comment]
> > Yes, the secureboot enablement is runtime by skiboot for the given platform. Currently, except skiboot patches all other patches are available in op-build.
> 
> What about the p9layout.xml changes, I thought they were necessary?
> 
> Let's get all dependencies merged on op-build first before we enable this additional package.
> 
> Thanks

Actually layout change is done.. We have to close on Mihawk fix patch that is broken because of skiboot size increase.. Working on that in another PR. 

This was simple to get done and had no dependency, so thought to get this also done.
I have pushed the patch again as per your suggestion. I am fine if want to merge it after all dependencies, just want to ensure that it gets included.

Thanks & Regards,
      - Nayna

**Comment by klauskiwi** [comment]
> 
> 
> > > Yes, the secureboot enablement is runtime by skiboot for the given platform. Currently, except skiboot patches all other patches are available in op-build.
> > 
> > 
> > What about the p9layout.xml changes, I thought they were necessary?
> > Let's get all dependencies merged on op-build first before we enable this additional package.
> > Thanks
> 
> Actually layout change is done.. We have to close on Mihawk fix patch that is broken because of skiboot size increase.. Working on that in another PR.

I just checked and I was surprised to see went under my radar with PR #3725 
@dcrowell77 that commit broke Mihawk build upstream. I thought that the op-jenkins bot wouldn't  touch things outside hostboot/occ/etc

We need to do better than this next time..

> 
> This was simple to get done and had no dependency, so thought to get this also done.
> I have pushed the patch again as per your suggestion. I am fine if want to merge it after all dependencies, just want to ensure that it gets included.
> 

Please fix #3750 as soon as possible..

@NicholeWang FYI and also as a call-to-action that we need to have Wistron validating our PRs with Mihawks builds + tesets on our CI, otherwise we might brake it like that..

**Comment by naynajain** [comment]
Since PR 3750 (https://github.com/open-power/op-build/pull/3750) is merged. Can we now please merge and close this as well ?

Thanks & Regards,
     - Nayna

**Comment by naynajain** [comment]
Hmm.. it seems to be somewhere failing for ubuntu ppc64le.

**Comment by klauskiwi** [comment]
Nayna, looks like one of the build jobs failed due to an unrelated issue, but regardless, can you re-base with the latest and force-push to re-trigger the test?

Thanks

**Comment by naynajain** [comment]
> Nayna, looks like one of the build jobs failed due to an unrelated issue, but regardless, can you re-base with the latest and force-push to re-trigger the test?
> 
> Thanks

Sure. will do sometime today.

Thanks & Regards,
    - Nayna

**Comment by naynajain** [comment]
Pushed again to trigger CI.

Thanks & Regards,
     - Nayna

**Comment by klauskiwi** [comment]
Looks good, thanks

**Comment by naynajain** [comment]
> Looks good, thanks

Thanks,

Thanks & Regards,
     - Nayna

**Pull request merged**
