### PR TITLE
phal: pdata: Bumped ae4e10..5940d4

### PR DESCRIPTION
**Pull request by aravynd**
aravnair-in (1):
      data:p10: Add ATTR_AVSBUS_BUSNUM and ATTR_AVSBUS_RAIL

Signed-off-by: Aravind T Nair <aravynd@gmail.com>

### CODE REVIEW

**Comment by danlarson-ibm** [comment]
ok to test

**Comment by bofferdn** [comment]
DCO check is failing, although I cannot exactly figure out why ...

**Comment by bofferdn** [comment]
I have updated https://github.com/open-power/op-build/pull/4937/ to pull in same changes and pass DCO checks, so I'll go with that one if it passes.

**Comment by bofferdn** [comment]
Merge #4937 which replicated the commit here.  Closing.

**Pull request closed without merging**
