### PR TITLE
Removing I2C patch now that skiboot is fixed

### PR DESCRIPTION
**Pull request by e-liner**
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1157)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch?

**Comment by stewart-ibm** [comment]
ok to test

**Comment by stewart-ibm** [comment]
@e-liner could you double check the p9 IPL failures here, they could be related to this change I'm not sure.

**Comment by e-liner** [comment]
I will. This was a test case really. I'll run it on hardware locally today.

**Comment by e-liner** [comment]
No, this is still legitimately broken. I'll close this out for now.

**Pull request closed without merging**
