### PR TITLE
Update Witherspoon XML level to include 2666 dimm freq change 05/19/17

### PR DESCRIPTION
**Pull request by wghoffa**
- Witherspoon-xml / master is broken again with changes that are
     known to not compile, so manual pull request required

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1097)

### CODE REVIEW

**Comment by e-liner** [comment]
ok to test

**Comment by e-liner** [comment]
retest this please

**Comment by wghoffa** [comment]
retest this please

**Comment by wghoffa** [comment]
retest this please

**Comment by wghoffa** [comment]
Validated this ran succesfully on a pass-2 Witherspoon system. Merging this.

**Pull request merged**
