### PR TITLE
Add sbe-odyssey package

### PR DESCRIPTION
**Pull request by ibmzach**
This commit adds the sbe-odyssey package, which builds Odyssey images from IBM's internal github repo. This package is enabled by default; to build without access to IBM Github Enterprise, the BR2_PACKAGE_SBE_ODYSSEY variable must be set to "n" in the configuration file.

### CODE REVIEW

**Review by zane131 — APPROVED** [review]

**Comment by fspbld** [comment]
ok to test

**Comment by dcrowell77** [comment]
retest this please

**Comment by dcrowell77** [comment]
retest this please

**Comment by IlyaSmirnov91** [comment]
retest this please

**Comment by dcrowell77** [comment]
retest this please

**Comment by ibmzach** [comment]
retest this please

**Comment by ibmzach** [comment]
retest this please

**Comment by ibmzach** [comment]
retest this please

**Comment by ibmzach** [comment]
retest this please

**Comment by dcrowell77** [comment]
Going to just ignore the ubuntu issues and merge

**Pull request merged**
