### PR TITLE
linux: enable CONFIG_CPU_IDLE

### PR DESCRIPTION
**Pull request by stewart-ibm**
Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/587)

### CODE REVIEW

**Comment by shenki** [comment]
LGTM

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
(for those playing along at home... the test run "failure" isn't exactly remotely obvious as to what is failing)

**Pull request merged**
