### PR TITLE
Skiboot v6.3

### PR DESCRIPTION
**Pull request by stewart-ibm**
Also needs to go to 2.3.y

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Requires https://github.com/open-power/op-test-framework/pull/489 for op-test

**Comment by oohal** [comment]
Witherspoon CI failure seems to be due to a tracehash collision in the SBE:

```
*** assimilate_file: ERROR: HASH Collision! (a_f)
    Two different strings have the same hash value (940815593)
    String 1: FBC_ALTD_BUSY = %d||/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/witherspoon/label_exp/austin/output-ubuntu1804-witherspoon_defconfig/build/sbe-249671d79a098be1068df41754a258483aa17614/src/import/chips/p9/procedures/hwp/nest/p9_adu_coherent_utils.C
    String 2: << p9_sbe_ppe_ffdc: #Regs %d||/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/witherspoon/label_exp/austin/output-ubuntu1804-witherspoon_defconfig/build/sbe-249671d79a098be1068df41754a258483aa17614/src/import/chips/p9/procedures/hwp/lib/p9_sbe_ppe_ffdc.C
*** assimilate_file: ERROR: HASH Collision! (a_f)
    Two different strings have the same hash value (940793680)
    String 1: Error from p9_pba_coherent_check_status, returning PBA rc||/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/witherspoon/label_exp/austin/output-ubuntu1804-witherspoon_defconfig/build/sbe-249671d79a098be1068df41754a258483aa17614/src/import/chips/p9/procedures/hwp/nest/p9_pba_coherent_utils.C
    String 2: ERROR:EDRAM_ABIST_DONE_BIT_NOT_SET||/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/witherspoon/label_exp/austin/output-ubuntu1804-witherspoon_defconfig/build/sbe-249671d79a098be1068df41754a258483aa17614/src/import/chips/p9/procedures/hwp/perv/p9_perv_sbe_cmn.C
```
Is that just bad luck?

**Comment by sammj** [comment]
> Requires [open-power/op-test-framework#489](https://github.com/open-power/op-test-framework/pull/489) for op-test

This is now merged.

**Comment by dcrowell77** [comment]
`
+ op-build garrison_defconfig
+ make --directory=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2113/CONFIG/garrison/OS/Ubuntu_18.04/build/op-build/buildroot O=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2113/CONFIG/garrison/OS/Ubuntu_18.04/build/op-build/output garrison_defconfig
op-build-env: line 18: make: command not found
`

**Comment by sammj** [comment]
retest this please

**Pull request merged**
