### PR TITLE
Release 4.4.20-openpower1

### PR DESCRIPTION
**Pull request by shenki**
v4.4.20 stable release, which includes a fix for a NVMe issue that is
important for OpenPower machines.

Signed-off-by: Joel Stanley <joel@jms.id.au>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/627)

### CODE REVIEW

**Comment by shenki** [comment]
Hot off the press. Untested by me.

**Comment by ploetzma** [comment]
"ERROR: Specified input file (/tmp/hostboot/jenkins-slave/workspace/op_build_ghprb_trigger/output/images/zImage.epapr) for key (BOOTKERNEL) does not exist.  Aborting! at /tmp/hostboot/jenkins-slave/workspace/op_build_ghprb_trigger/output/host/usr/powerpc64le-buildroot-linux-gnu/sysroot/hostboot_build_images//buildpnor.pl line 422."

I have seen this before - but fixed it by finding a zImage.epapr in another build and throwing it into that location. @jazurin any comments? Should we just retest?

**Comment by jazurin** [comment]
retest this please

**Comment by stewart-ibm** [comment]
```
>>> linux 4.4.20 Downloading
--2016-09-07 11:28:01--  https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.4.20.tar.xz
Resolving cdn.kernel.org... 151.101.68.69
Connecting to cdn.kernel.org|151.101.68.69|:443... connected.
ERROR: certificate common name “k.ssl.fastly.net” doesn’t match requested host name “cdn.kernel.org”.
To connect to cdn.kernel.org insecurely, use ‘--no-check-certificate’.
--2016-09-07 11:28:01--  http://sources.buildroot.net/linux-4.4.20.tar.xz
Resolving sources.buildroot.net... 176.9.16.109
Connecting to sources.buildroot.net|176.9.16.109|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-09-07 11:28:02 ERROR 404: Not Found.
```

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
So, that's the same error. I've tried both locally and from machines in Austin and I'm not reproducing it. So, I wonder what's special about the Jenkins machine....

@shenki additionally, we should probably have the hash of the kernel tarball somewhere too, is there a buildroot way to do this for custom kernel versions?

**Comment by shenki** [comment]
```
# Compute LINUX_SOURCE and LINUX_SITE from the configuration
ifeq ($(BR2_LINUX_KERNEL_CUSTOM_TARBALL),y)
LINUX_TARBALL = $(call qstrip,$(BR2_LINUX_KERNEL_CUSTOM_TARBALL_LOCATION))
LINUX_SITE = $(patsubst %/,%,$(dir $(LINUX_TARBALL)))
LINUX_SOURCE = $(notdir $(LINUX_TARBALL))
BR_NO_CHECK_HASH_FOR += $(LINUX_SOURCE)
```

No. It looks like they explicitly disable checks for the custom tarball URL.

Once 4.8 is released we don't need the custom URL and at that point I think we get hashes back.

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
(let's see if the Jenkins stuff is less broken now...)

**Comment by shenki** [comment]
The internal CI is failing to download the kernel source tarball:

```
 >>> linux 4.4.20 Downloading
--2016-09-11 22:52:31--  https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.4.20.tar.xz
Resolving cdn.kernel.org... 151.101.68.69
Connecting to cdn.kernel.org|151.101.68.69|:443... connected.
ERROR: certificate common name “k.ssl.fastly.net” doesn’t match requested host name “cdn.kernel.org”.
To connect to cdn.kernel.org insecurely, use ‘--no-check-certificate’.
--2016-09-11 22:52:31--  http://sources.buildroot.net/linux-4.4.20.tar.xz
Resolving sources.buildroot.net... 176.9.16.109
Connecting to sources.buildroot.net|176.9.16.109|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-09-11 22:52:32 ERROR 404: Not Found.
```

The common name for the cert is `k.ssl.fastly.net`, but there are a number of alternative names.

I suspect the version of wget that is being used on the IBM CI machines is too old to inspect the alternate name field of the certificate and so it fails.

**Comment by stewart-ibm** [comment]
@jazurin are you able to look into what's going on here? I don't want to hold up merging this much longer as 4.4.20 does have fixes in it we need (as likely will 4.4.21).

**Comment by shenki** [comment]
Thanks @op-jenkins. Do you have an alias we could call you by?

The core of the issue is a lack of alternate name support in wget's certificate parsing code. This feature was added several years ago, but must not be in the version of RHEL we're using. 

https://bugzilla.redhat.com/show_bug.cgi?id=903756
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=409938

We will have this issue with any site that relies on alternate names in their certificate, which is common for any sites behind a CDN.

The fix would be to update to a version of wget that does have the support. I'm not familiar with the version of RHEL we're running, nor what version would be required.

**Comment by shenki** [comment]
I'm told it should be fixed in `wget-1.12-5.

**Comment by jazurin** [comment]
@shenki sorry I didn't realize I was logged on as op-jenkins!
I've been in contact with IT, trying to expedite the wget upgrade on at least the machines we use as Jenkins slaves.  I also verified that `Wget 1.14` doesn't have problems downloading that file.

**Comment by stewart-ibm** [comment]
Joel Stanley <notifications@github.com> writes:
> Thanks @op-jenkins. Do you have an alias we could call you by?
>
> The core of the issue is a lack of alternate name support in wget's certificate parsing code. This feature was added several years ago, but must not be in the version of RHEL we're using. 
>
> https://bugzilla.redhat.com/show_bug.cgi?id=903756
> https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=409938
>
> We will have this issue with any site that relies on alternate names in their certificate, which is common for any sites behind a CDN.
>
> The fix would be to update to a version of wget that does have the
> support. I'm not familiar with the version of RHEL we're running, nor
> what version would be required.

I'd be surprised if there isn't a RHEL update to fix this...

There's https://bugzilla.redhat.com/show_bug.cgi?id=736445 for RHEL6,
but "You are not authorized to access bug #736445. To see this bug, you
must first log in to an account with the appropriate permissions."

grr...


-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by shenki** [comment]
You're tracing my steps from a few days ago. I chatted to a contact at Red Hat and they said that bug was resolved with 1.12-5

**Comment by williamspatrick** [comment]
@jazurin - I found out from Dean that anyone who doesn't have any kernel in the download cache runs into this problem, even on master. With that in mind, can you ma tally download this kernel version to get CI to pass while you figure out an alternative with wget?

**Comment by jazurin** [comment]
@williamspatrick ok, I am testing that right now.  I created a public dir with the kernel files that `wget` couldn't download: `linux-4.8-rc5.tar.xz` and `linux-4.4.20.tar.xz`.  Also created a short script that creates links to those files in op-build `dl` dir, so internal devs can use that while we wait for `wget` to be upgraded on the pool machines.

**Comment by jazurin** [comment]
retest this please

**Comment by stewart-ibm** [comment]
Jay Azurin <notifications@github.com> writes:
> @williamspatrick ok, I am testing that right now.  I created a public
> dir with the kernel files that `wget` couldn't download:
> `linux-4.8-rc5.tar.xz` and `linux-4.4.20.tar.xz`.  Also created a
> short script that creates links to those files in op-build `dl` dir,
> so internal devs can use that while we wait for `wget` to be upgraded
> on the pool machines.

Will also need 4.4.21 as we have a 4.4.21 pull request open too

-- 
Stewart Smith
OPAL Architect, IBM.

**Pull request closed without merging**
