### PR TITLE
Secure Boot: Support production signing in op-build

### PR DESCRIPTION
**Pull request by bofferdn**

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch for testing?

**Comment by bofferdn** [comment]
This commit in theory supplants Dave's original sb-signing-framework commit and additionally integrates support for production signing in op-build.

**Comment by bofferdn** [comment]
@hellerda @stewart-ibm

**Comment by hellerda** [comment]
Changes all look good, thanks Nick.

**Pull request merged**
