### PR TITLE
sbe: Fix build commands

### PR DESCRIPTION
**Pull request by wak-google**
Also, reindent to match other buildroot packages

This depends on https://github.com/open-power/sbe/pull/4 being accepted and the SBE_VERSION being updated accordingly.

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1035)

### CODE REVIEW

**Comment by williamspatrick** [comment]
"Fix build commands" isn't much of an explanation as to why this is needed. Doesn't sbe use the git commit number by default? Buildroot downloads a git repo. So why is this even needed?

**Comment by wak-google** [comment]
The SBE uses the git commit number, which breaks when you don't have a git repo. This commit passes the commit id manually, and the corresponding sbe change allows the manual specification.

This is all needed since using $(call github,open-power,sbe,$(SBE_VERSION)) returns something like "https://github.com/open-power/sbe/archive/c9fea2e9662bdef548ea4742106b721386240ffe.tar.gz". This is just a `git archive` compressed tarball that has no git information or submodules. For most projects this should be the preferred behavior as it is faster than cloning and saves bandwidth. However this breaks the SBE method for parsing git commit information.

**Comment by williamspatrick** [comment]
@sgupta2m -any issues?

**Comment by sgupta2m** [comment]
OK To test

**Comment by sgupta2m** [comment]
retest this please

**Comment by wak-google** [comment]
Now that https://github.com/open-power/sbe/pull/4 is merged, this commit contains the updated SBE sources and should build with the COMMIT_ID passed.

**Comment by wak-google** [comment]
So far building with the new stack of SBE commits from open-power/sbe@c9fea2e9662bdef548ea4742106b721386240ffe .. open-power/sbe@695eed7bf424f58899e2650ecfdadc5389bf35f5 seems to have broken in such a way that it can't even get to hostboot on zaius using DD1 chips. Using the old open-power/sbe@c9fea2e9662bdef548ea4742106b721386240ffe with open-power/sbe@695eed7bf424f58899e2650ecfdadc5389bf35f cherry-picked worked fine previously.

**Comment by sgupta2m** [comment]
Will be checking the latest version. when we update sbe image, in first ipl till istep 10 it uses old sbe image only. at istep 10 hostboot update sbe image and retrigger IPL . Are you saying your IPL is failing after sbe image update from HB ( second IPL ) ?

**Comment by wak-google** [comment]
That's correct. I'm reverting just that change now and swapping some CPU's to get back to the older SBE and make sure everything works.

**Comment by wak-google** [comment]
@sgupta2m Verified that it's the SBE update by reverting just the version of the SBE and including the COMMIT_ID patch.

**Comment by sgupta2m** [comment]
So you did not get issue by just having your commit. SBE  code is verified on hardware ( zz boxes ) before the release ... One possibility is that hardware image in op-build is not latest and not in sync with latest sbe changes ... will verify it and push other commit resolving dependencies ..

**Comment by sgupta2m** [comment]
@shakeebbk  I am on off today ... can you please give it a run

**Comment by wak-google** [comment]
@sgupta2m I'm not terribly familiar with the process of converting the output binary from the sbe build process into the SBE partition data. What other binaries are actually needed at this point (I presume from hostboot-binaries)? Or are there data sections in the chip specific sbe binaries in the hostboot-binaries repo that are parsed out and injected alongside the source build reference image?

**Comment by sgupta2m** [comment]
@wak-google please use this pull request  >https://github.com/open-power/hostboot-binaries/pull/28>

**Comment by pragupta** [comment]
retest this please

**Comment by pragupta** [comment]
retest this please

**Comment by williamspatrick** [comment]
@wak-google : I think there is an update to this needed?

**Comment by wak-google** [comment]
Yes, I'm currently trying to recover the chips i broke. I've tested this PR as it stands and it builds fine on zaius, boots and updates to working SBE image. Hopefully once I unbrick the CPUs I can retest with a new SBE version that includes my patch.

**Comment by stewart-ibm** [comment]
retest this please

**Comment by wak-google** [comment]
This is now working on zaius machines in our build environment using the latest SBE code and op-build master.

**Pull request merged**
