### PR TITLE
Update openpower-pnor package

### PR DESCRIPTION
**Pull request by crgeddes**
This will revert a commit that was causing swift compiles to fail.

Signed-off-by: Christian Geddes crgeddes@us.ibm.com

### CODE REVIEW

**Comment by stewartsmith** [comment]
Swift isn’t upstream, so unless this causes a regression for an upstream platform, I do not see why this should go in.

In the past we have not provided any guarantees for out of tree code.

**Comment by crgeddes** [comment]
This change is backing out changes that were made to axonePnorLayout64.xml (publicly available) which is only used in the swift config. IBM is running CI's internally that are pointing at the XML in order to keep regressions on swift running. 

Without this we would have to make wait for the real fix, meanwhile our CI's are failing and we cannot get anything through. 

Unless you can show how this hurts anyone, I would really like to get this in. Arguably this is a commit that should have never been merged, hence why its a revert.

**Comment by crgeddes** [comment]
Basically this is reverting our attempts to get swift upstream because it broke things for us. No upstream users will be affected.

**Comment by stewartsmith** [comment]
> On 6 Sep 2019, at 12:01, Christian Geddes <notifications@github.com> wrote:
> 
> This change is backing out changes that were made to axonePnorLayout64.xml (publicly available) which is only used in the swift config. IBM is running CI's internally that are pointing at the XML in order to keep regressions on swift running.
> 
> Without this we would have to make wait for the real fix, meanwhile our CI's are failing and we cannot get anything through.
> 
> Unless you can show how this hurts anyone, I would really like to get this in. Arguably this is a commit that should have never been merged, hence why its a revert.
> 

Makes sense now, thanks. Probably a bit better to revert the commit in pnor repo though

**Comment by crgeddes** [comment]
These changes were picked up in another PR so I am closing this.

**Pull request closed without merging**
