### PR TITLE
Modify XML Pointer

### PR DESCRIPTION
**Pull request by Erich-Hauptli**
Pick up updates to FRU IDs to match Firestone and Membuf Sensor ID updates to allow thermal algorithm to work properly.

### CODE REVIEW

**Comment by williamspatrick** [comment]
@Erich-Hauptli - This cannot be merged due to build failure.  Please check with @jazurin on the failure.  Are we missing a BMC or Hostboot dependency?

**Comment by jazurin** [comment]
The HW CI test failed on habanero while trying to load the OS.  That is issue is being tracked here:
https://github.com/open-power/op-build/issues/307
For reference, I captured the SOL output and copied it here: https://gist.github.com/jazurin/23ffc974d6e394792de0

I will manually re-trigger the test.

**Comment by Erich-Hauptli** [comment]
The test was run against a Habanero.  This patch simply updates the SHA for the Garrison-xml file.  I have no idea why you'd test this against a Habanero or why it would fail, but this patch would have nothing to do with the fail.

**Comment by Erich-Hauptli** [comment]
Jay,
        I'm very confused here.  Why would you run any of this on a 
Habanero?  This change only applies to Garrison.  Please look at the 
commit as I only modified the SHA pointer for the Garrison-xml.  If 
something broke it was not due to this patch.
Thank You,
Erich Hauptli
Open Power Development Engineer
Office:    1-512-286-6566 
(T/L):      2-363-6566
Cell:       1-517-881-2927

**Comment by jazurin** [comment]
The automated HW tests run on palmetto, habanero, and firestone platforms (soon on garrison).   I understand that your patch did not cause the failure.  I was simply trying to explain that the test failed due to an intermittent problem that is being looked at by the OPAL team.

**Pull request merged**
