### PR TITLE
Use witherspoon-xml op-build-2.0.y branch

### PR DESCRIPTION
**Pull request by popfuture**
This commit causes witherspoon_defconfig within op-build's
op-build-2.0.y branch to point to witherspoon-xml's
op-build-2.0.y branch, top commit as of November 26, 2018 and
includes the "Default Spectre/Meltdown HW Inits to Kernel Mode"
change.

### CODE REVIEW

**Comment by popfuture** [comment]
If you are reviewing this you should take note that the old witherspoon_defconfig that the commit is changing was originally pointing to a witherspoon-xml version that doesn't have Dean's "Default Spectre/Meltdown HW Inits to Kernel Mode" change. The new witherspoon_defconfig points to the latest witherspoon-xml so it does include the change. Please take note of that and make sure you understand the implications.

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
I'm pretty unhappy about this going in when it did.

1) The pull request was only opened on a Friday, then merged on a Saturday
2) The change did not live in master at **all** before being merged here. It's in a PR up at https://github.com/open-power/op-build/pull/2508 which has had failing CI.
3) There hasn't been sign off from a broader group of people than some hidden group of people deep in the bowels of building 45.
4) There is no clear way to easily revert back to the previous default behavior
5) this comes with *NO* explanation for release notes for reasoning for the change of the defaults over the previous stable release.

**Comment by stewart-ibm** [comment]
6) https://github.com/open-power/op-build/pull/2504#issuecomment-444729945 comment wasn't addressed either for the PR of master or this.

I am increasingly convincing myself to revert this until all of these items are resolved.

**Comment by sammj** [comment]
> I am increasingly convincing myself to revert this until all of these items are resolved.

Seconded

**Pull request merged**
