### PR TITLE
petitboot: Bump to v1.6.0

### PR DESCRIPTION
**Pull request by sammj**
Signed-off-by: Samuel Mendoza-Jonas <sam@mendozajonas.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1380)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch for testing?

**Comment by stewart-ibm** [comment]
ok to test

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by sammj** [comment]
`Agent went offline during the build`
Boooooo

**Comment by sammj** [comment]
retest this please

**Comment by stewart-ibm** [comment]
@sammj probably have to rebase, stupid CI is stupid with the platform name changes.

**Comment by sammj** [comment]
```
java.lang.NoClassDefFoundError: Could not initialize class org.eclipse.jgit.internal.storage.file.WindowCache
...
Caused: java.io.IOException: Remote call on p82 failed
```
Jenkins has got it out for me on this one.

**Pull request merged**
