### PR TITLE
buildroot: Bump to version 2023.02-op-build

### PR DESCRIPTION
**Pull request by runlevel5**
## Context

There have been few attempts to bump to newer linux 5.10.x and buildroot. Unfortunately most of them have failed builds on CI. So I'd like to do another attempt but starting with bumping to newer buildroot first.

## Changes

* Bump to buildroot version 2023.02-op-build

## NOTES

I can successfully compile `blackbird` firmware on Ubuntu 22.04 ppc64le

### CODE REVIEW

**Comment by IlyaSmirnov91** [comment]
CI crashed and burned. I'm not 100% sure if it's because of the commit or if it's just in a bad state. I made[ a test commit](https://github.com/open-power/op-build/pull/5632) to check.

**Comment by runlevel5** [comment]
@IlyaSmirnov91 is there any chance I could see the CI build output? Plus what is spec of the Ubuntu CI worker?

**Comment by IlyaSmirnov91** [comment]
> @IlyaSmirnov91 is there any chance I could see the CI build output? Plus what is spec of the Ubuntu CI worker?

Sure, here is the Ubuntu failure:

`python buildInfo.py /tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-4645/CONFIG/witherspoon/OS/ubuntu/build/op-build/output/build/sbe-f9b2cb1c91d5a44c3cda8f385d61118d55616465/obj/power/genfiles
make[3]: python: No such file or directory
make[3]: *** [Makefile:247: buildInfo] Error 127
make[2]: *** [Makefile:179: all] Error 2
make[2]: Leaving directory '/tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-4645/CONFIG/witherspoon/OS/ubuntu/build/op-build/output/build/sbe-f9b2cb1c91d5a44c3cda8f385d61118d55616465/src/build'
make[1]: *** [Makefile:36: DD2] Error 2
make[1]: Leaving directory '/tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-4645/CONFIG/witherspoon/OS/ubuntu/build/op-build/output/build/sbe-f9b2cb1c91d5a44c3cda8f385d61118d55616465'
make: *** [package/pkg-generic.mk:251: /tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-4645/CONFIG/witherspoon/OS/ubuntu/build/op-build/output/build/sbe-f9b2cb1c91d5a44c3cda8f385d61118d55616465/.stamp_built] Error 2
make: Leaving directory '/tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-4645/CONFIG/witherspoon/OS/ubuntu/build/op-build/buildroot'
+ '[' 2 -ne 0 ']'
witherspoon build failed.
+ echo 'witherspoon build failed.'
+ exit_out 1
+ helpful_messages
+ [[ 0 -eq 1 ]]
+ local rc=1`

This ran on Ubuntu 22.04
The RHEL failure (one of them):

/tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-multi-4473/CONFIG/witherspoon/OS/redhat-8/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/ppe42-toolchain/linux/powerpc-eabi/bin/ar crs /tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-multi-4473/CONFIG/witherspoon/OS/redhat-8/build/op-build/output/build/sbe-f9b2cb1c91d5a44c3cda8f385d61118d55616465/obj/power_axone/fapi2_seeprom/libfapi2seeprom.a /tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-multi-4473/CONFIG/witherspoon/OS/redhat-8/build/op-build/output/build/sbe-f9b2cb1c91d5a44c3cda8f385d61118d55616465/obj/power_axone/fapi2_seeprom/*.o
/bin/make --no-print-directory output_sbe_image
Generating /tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-multi-4473/CONFIG/witherspoon/OS/redhat-8/build/op-build/output/build/sbe-f9b2cb1c91d5a44c3cda8f385d61118d55616465/images/sbe_seeprom_AXONE.out
make[4]: ./parsAndCutElf.py: Command not found
make[4]: *** [Makefile:165: output_sbe_image] Error 127
make[3]: *** [Makefile:181: all] Error 2
make[2]: *** [Makefile:36: DD2] Error 2
make[2]: *** Waiting for unfinished jobs....
make[4]: ./parsAndCutElf.py: Command not found
make[4]: *** [Makefile:165: output_sbe_image] Error 127
make[3]: *** [Makefile:181: all] Error 2
make[2]: *** [Makefile:39: axone] Error 2
make[1]: *** [package/pkg-generic.mk:251: /tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-multi-4473/CONFIG/witherspoon/OS/redhat-8/build/op-build/output/build/sbe-f9b2cb1c91d5a44c3cda8f385d61118d55616465/.stamp_built] Error 2
make: *** [Makefile:84: _all] Error 2

**Comment by runlevel5** [comment]
> make[3]: python: No such file or directory

For Ubuntu 22.04, I know how to fix it, could you please install following packages:

```
python2 python-is-python3
```

And in regards to RHEL build, is the CI worker RHEL 7 or 8? I have to find out how to get it installed on my box first to be able to re-produce the issue

**Comment by dcrowell77** [comment]
> Is there any requirement that CI worker must be RHEL 7? For the sake of consistency, can we just use Ubuntu 22.04 x86_64?

Yes, we are still running some of our jobs against RHEL7 machines.  We are in the midst of transitioning to RHEL8 as our main platform.  We can't only run on Ubuntu.

**Comment by runlevel5** [comment]
Thanks for the prompt response. I will test against RHEL 7 locally.

**Comment by IlyaSmirnov91** [comment]
Note that there is also a fix in-flight from SBE for RHEL8 compilations.

**Comment by runlevel5** [comment]
>  Note that there is also a fix in-flight from SBE for RHEL8 compilations.

Would you mind point me to the Pull Request or commit of that fix?

**Comment by dcrowell77** [comment]
> Would you mind point me to the Pull Request or commit of that fix?

I believe it is still undergoing internal testing.

**Comment by runlevel5** [comment]
@IlyaSmirnov91 Quick update from me, I've just given RHEL 7 x86_64 a run and everything works.

I could not re-produce the error. Would it possible if you could upload the full logs to gist.github.com for my investigation?

NOTE: I am using RHEL 7.9 x86_64 in VirtualBox

**Comment by IlyaSmirnov91** [comment]
retest this please

**Comment by runlevel5** [comment]
Okay let me re-base

**Comment by runlevel5** [comment]
I looks much better. I am wondering what would be the error of the IBM OP CI HW IPL test? Many thanks

**Comment by runlevel5** [comment]
@IlyaSmirnov91 could you please send me the error log of IBM OP CI HW IPL test? Many thanks

**Comment by IlyaSmirnov91** [comment]
> @IlyaSmirnov91 could you please send me the error log of IBM OP CI HW IPL test? Many thanks

It looks like the fail may be due to the job being broken, I'm asking around.

**Pull request merged**
