### PR TITLE
ima-catalog: update version

### PR DESCRIPTION
**Pull request by drajarshi**
- Modified compatible field for core and thread.

- Fixed POWER9 DTS files.

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1246)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch for testing?

**Comment by stewart-ibm** [comment]
ok to test

**Comment by wghoffa** [comment]
retest this please

**Comment by scprek** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by wghoffa** [comment]
@stewart-ibm - I don't seem to have access to the Built test results. Did that ever get resolved?

**Comment by stewart-ibm** [comment]
@wghoffa Not really, it fell down my TODO list.

The failures here are spurious anyway, so all looks good from my end.

**Pull request merged**
