### PR TITLE
Romulus enable OCC and BMC MBOX

### PR DESCRIPTION
**Pull request by MengzeLiao**
1). enable OCC config
2). enable BMC MBOX
3). update MRW for OCC enablement and i2c 4x13

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1180)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch for testing?

**Comment by stewart-ibm** [comment]
ok to test

**Comment by MengzeLiao** [comment]
retest this please

**Comment by stewart-ibm** [comment]
The Zaius failure is a false failure, failing due to other issues it seems.

I tested on a romulus, and this fixes booting with current op-build. Merging.

**Pull request merged**
