### PR TITLE
petitboot: Update to v1.2.7

### PR DESCRIPTION
**Pull request by sammj**
Signed-off-by: Samuel Mendoza-Jonas <sam@mendozajonas.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/760)

### CODE REVIEW

**Comment by sammj** [comment]
> make[1]: *** No rule to make target 'witherspoon_defconfig'.  Stop.

Odd, but not related to this change.

**Comment by stewart-ibm** [comment]
@sammj It appears that the introduction of witherspoon testing breaks testing anything that doesn't have it (e.g. maintenance branches such as this).

@e-liner any way to fix? We'd still like to IPL test this branch.

**Comment by e-liner** [comment]
Yeah I should be able to turn it off for specific branches.  As long as it doesn't get pulled into master-next, I don't see a problem with that.  Let me look into it more, and I'll get back to you.

**Comment by e-liner** [comment]
retest this please

**Comment by e-liner** [comment]
retest this please

**Pull request merged**
