### PR TITLE
linux: Re-enable mlx5 driver

### PR DESCRIPTION
**Pull request by sammj**
With recent v4.4.x stable releases and updated card firmware, mlx5
network devices now appear to behave properly over kexec.

Reverts: 17b4c3c6e6389c8d5d354ef778ce1f39067f8a34
Signed-off-by: Samuel Mendoza-Jonas <sam@mendozajonas.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/781)

### CODE REVIEW

**Comment by sammj** [comment]
Additionally from what I hear these are the minimal card firmware levels needed to make mlx5 behave correctly over kexec, available in Fix Central:
- CX4 IB cards: 12.17.2020
- CV4 ETH cards: 12.17.1502

**Comment by sammj** [comment]
(Updated to reference correct commit in commit message)

**Comment by sammj** [comment]
> make[1]: *** No rule to make target `zaius_defconfig'.  Stop.

I imagine that is because https://github.com/open-power/op-build/pull/780 isn't merged just yet.

**Comment by shenki** [comment]
@sammj does the kernel driver test for those versions? Do we need to add a test?

**Comment by sammj** [comment]
@shenki Looks like the driver queries it but I can't see any sign of it checking for a minimum version.

**Comment by williamspatrick** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Pull request merged**
