### PR TITLE
Enable SBE compilation in P9 op-build

### PR DESCRIPTION
**Pull request by Shakeebbk**
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1008)

### CODE REVIEW

**Comment by wghoffa** [comment]
@sannerd @dcrowell77 @scprek - Will we want to get the SBE version in the version PNOR partition? Would this happen automatically?

**Comment by wghoffa** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/op-build/1008)*

**Comment by wghoffa** [comment]
Please test this

**Comment by wghoffa** [comment]
Test this please

**Comment by wghoffa** [comment]
ok to test

**Comment by dcrowell77** [comment]
Yes, we definitely want the output from this build to replace the file currently getting checked into hostboot-binaries.  There will need to be some work to combine this with the hw-image binary before pushing it into PNOR.  Since we are pulling from here I think we want this git level to get reported in VERSION.

**Comment by sgupta2m** [comment]
@dcrowell77 last was a question ? .. The hardware image in hostboot-binaries are still required for P8 ...

**Comment by dcrowell77** [comment]
Of course, P8 isn't changing.  This is all for P9 only.

**Comment by pragupta** [comment]
ok to test

**Comment by stewart-ibm** [comment]
Some build targets failed with:

```
Makefile:535: *** sbe is in the dependency chain of openpower-pnor that has added it to its _DEPENDENCIES variable without selecting it or depending on it from Config.in.  Stop.
Makefile:79: recipe for target '_all' failed
```

**Comment by stewart-ibm** [comment]
retest this please

**Comment by Shakeebbk** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
ok to test

**Comment by wghoffa** [comment]
retest this please

**Comment by wghoffa** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/op-build/1008)*

**Comment by wghoffa** [comment]
@sannerd - SBE Changes ready to go

**Comment by williamspatrick** [comment]
@Shakeebbk @sgupta2m @wghoffa - I'm going to merge this as is, but I suspect there is some interest in having the SBE version in the PNOR VERSION partition.  There is another buildroot file to update to include that.

**Comment by wghoffa** [comment]
@Shakeebbk - Can you make a second commit to update this? https://github.com/open-power/op-build/blob/master/openpower/package/openpower-pnor/openpower-pnor.mk#L53

It should now include the SBE package. This will allow the version of your package to be displayed during boot.

**Comment by sgupta2m** [comment]
The changes has sbe version.
The output from Dean run
open-power-zaius-v1.15-120-g1c7ae7d-dirty
       buildroot-2017.02-4-gc28573e
       skiboot-5.5.0
       hostboot-c4ede09
       linux-4.10.7-openpower1-p17e6cb1
       petitboot-v1.4.2-p335166a
       zaius-xml-b907705
       occ-e1889e5
       hostboot-binaries-d1b1312
       capp-ucode-1bb7503
       sbe-c9fea2e

**Pull request merged**
