### PR TITLE
POWER9 platforms switch to GCC6

### PR DESCRIPTION
**Pull request by stewart-ibm**
Fixes: https://github.com/open-power/op-build/issues/755
Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1137)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
This is going to depend either on HB switching to -Os or HBB growing in size. IIRC @wghoffa was working on bumping HBB size.

**Comment by dcrowell77** [comment]
@scprek is working on expanding HBB now.  I think he is pretty close but we might wait until after the next op-build tag to do it since it requires some changes to other packages.

**Comment by stewart-ibm** [comment]
Dan <notifications@github.com> writes:
> @scprek is working on expanding HBB now.  I think he is pretty close
> but we might wait until after the next op-build tag to do it since it
> requires some changes to other packages.

Okay, if that's the easy way to continue, I think that's feasible.

Now I just need to gather everyone around for an op-build tag... 

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by stewart-ibm** [comment]
@dcrowell77 any objections to this going in now? I saw that @wghoffa HBB expansion went in okay and this now seems to build *and* boot.

**Comment by dcrowell77** [comment]
We couldn't find a compelling reason to object so I guess you can go ahead.

**Comment by stewart-ibm** [comment]
Dan <notifications@github.com> writes:
> We couldn't find a compelling reason to object so I guess you can go
> ahead.

I'll rebase and run through the CI one more time to be sure everything
is good with current master.

Colour me paranoid in not wanting to break anybody :)

-- 
Stewart Smith
OPAL Architect, IBM.

**Pull request merged**
