### PR TITLE
Witherspoon BUP Config Settings Update

### PR DESCRIPTION
**Pull request by wghoffa**
Final updates missing from master-next from @pragupta's previous tags.

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/872)

### CODE REVIEW

**Comment by e-liner** [comment]
ok to test

**Comment by wghoffa** [comment]
retest

**Comment by wghoffa** [comment]
retest this please

**Comment by wghoffa** [comment]
@pragupta - Can you review?

**Comment by pragupta** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/op-build/872)*

**Pull request merged**
