### PR TITLE
buildroot: Move to 2018.08.1 point release

### PR DESCRIPTION
**Pull request by shenki**
Target packages:

 busybox: 1.29.1 -> 1.29.2

Host packages:

 libopenssl: 1.0.2o -> 1.0.2p

Upstream announcement:

 http://lists.busybox.net/pipermail/buildroot/2018-October/232433.html
 https://git.buildroot.net/buildroot/plain/CHANGES?id=2018.08.1

Importantly this includes fixes for building on host systems that have
glibc 2.28.

Signed-off-by: Joel Stanley <joel@jms.id.au>

### CODE REVIEW

**Comment by shenki** [comment]
retest this please

**Comment by stewart-ibm** [comment]
Joel Stanley <notifications@github.com> writes:
> retest this please

FYI if it builds on top of my "use docker with --init" patch then my CI
build stuff should actally work. I won't even pretend to know what
changed that made that suddenly required.

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by shenki** [comment]
@stewart-ibm This is rebased on top of that commit. It's still sitting at "default Pending — Build triggered for merge commit." several hours later.

**Comment by stewart-ibm** [comment]
> Took 2 hr 17 min on master

Yeah, I badly need hardware :/

**Pull request merged**
