### PR TITLE
configs: Add cryptsetup support

### PR DESCRIPTION
**Pull request by sammj**
Petitboot now supports opening encrypted partitions so include the
cryptsetup utility and required kernel options.
In particular this enables CRYPTO_XTS, CRYPTO_USER_API_HASH, and
CRYPTO_USER_API_SKCIPHER.

Signed-off-by: Samuel Mendoza-Jonas <sam@mendozajonas.com>

### CODE REVIEW

**Comment by sammj** [comment]
`savedefconfig` moved things around a bit in the kernel configs so it would be good to get a second pair of eyes on that too.

**Comment by sammj** [comment]
`has size (15772696) which is greater than allocated space (15728640) for section=BOOTKERNEL. `
44KB over :(

**Comment by stewart-ibm** [comment]
Sam Mendoza-Jonas <notifications@github.com> writes:
> `has size (15772696) which is greater than allocated space (15728640) for section=BOOTKERNEL. `
> 44KB over :(

we're going to bump it by 256k for the GCC8 work, so might get away with
it there

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by sammj** [comment]
Updating on top of master

**Pull request merged**
