### PR TITLE
Kernel 4.20.6 and Buildroot 2018.11.2

### PR DESCRIPTION
**Pull request by shenki**
Update to Linux 4.20.6, via 4.20.3. Includes buildroot bump to support 4.20, the latest buildroot stable release and a CI fix for Fedora.

### CODE REVIEW

**Comment by shenki** [comment]
Replaces https://github.com/open-power/op-build/pull/2597

**Comment by shenki** [comment]
The IBM OP CI build is failing on witherspoon due to downloading a non-existent file:
``
>>> hcode hw123119a.930 Downloading
--2019-02-03 18:54:16--  https://github.com/open-power/hcode/archive/hw123119a.930/hcode-hw123119a.930.tar.gz
Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
Connecting to github.com (github.com)|192.30.253.112|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/open-power/hcode/tar.gz/hw123119a.930/hcode-hw123119a.930 [following]
--2019-02-03 18:54:16--  https://codeload.github.com/open-power/hcode/tar.gz/hw123119a.930/hcode-hw123119a.930
Resolving codeload.github.com (codeload.github.com)... 192.30.253.121, 192.30.253.120
Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-02-03 18:54:16 ERROR 404: Not Found.
```

**Comment by stewart-ibm** [comment]
> The IBM OP CI build is failing on witherspoon due to downloading a non-existent file:
> ``
> 
> > > > hcode hw123119a.930 Downloading
> > > > --2019-02-03 18:54:16--  https://github.com/open-power/hcode/archive/hw123119a.930/hcode-hw123119a.930.tar.gz
> > > > Resolving github.com (github.com)... 192.30.253.112, 192.30.253.113
> > > > Connecting to github.com (github.com)|192.30.253.112|:443... connected.
> > > > HTTP request sent, awaiting response... 302 Found
> > > > Location: https://codeload.github.com/open-power/hcode/tar.gz/hw123119a.930/hcode-hw123119a.930 [following]
> > > > --2019-02-03 18:54:16--  https://codeload.github.com/open-power/hcode/tar.gz/hw123119a.930/hcode-hw123119a.930
> > > > Resolving codeload.github.com (codeload.github.com)... 192.30.253.121, 192.30.253.120
> > > > Connecting to codeload.github.com (codeload.github.com)|192.30.253.121|:443... connected.
> > > > HTTP request sent, awaiting response... 404 Not Found
> > > > 2019-02-03 18:54:16 ERROR 404: Not Found.

Well, that'd be because the tag doesn't exist. Urgh.

**Comment by shenki** [comment]
The `IBM OP CI HW IPL test -- p9` test failed due to a lack of available machine to test on.

**Comment by shenki** [comment]
`IBM OP CI HW IPL test -- p9` passed on Zaius but failed to find a Witherspoon to test on.

**Comment by stewart-ibm** [comment]
from a local op-test run on p9dsu (has occured at least twice)
```
[console-expect]#  
ipmitool event 3   
Sending SAMPLE event: Memory - Correctable ECC                                                      
cpu 0x2c: Vector: 300 (Data Access) at [c000001ff74d36d0]                                           
    pc: c00000000047d72c: __do_softirq+0xd4/0x2b0                                                   
    lr: c00000000047d8ac: __do_softirq+0x254/0x2b0                                                  
    sp: c000001ff74d3960                                                                            
   msr: 9000000000009033                                                                            
   dar: 1ffdbc0004 
 dsisr: 42000000   
  current = 0xc000001ff73cca80                                                                         
  paca    = 0xc000001ffffde600     irqmask: 0x03        irq_happened: 0x01                          
    pid   = 0, comm = swapper/44
Linux version 4.20.6-openpower1 (jenkins@bstn004p1) (gcc version 6.4.0 (Buildroot 2018.11.2-00011-g7
ded521)) #2 SMP Mon Feb 11 05:22:17 UTC 2019
enter ? for help
[c000001ff74d3a50] c00000000007c630 irq_exit+0x7c/0xd4
[c000001ff74d3a70] c00000000002bdd4 doorbell_exception+0x88/0xa4
[c000001ff74d3aa0] c000000000009b74 h_doorbell_common+0x124/0x130
--- Exception: e81 (Hypervisor Doorbell) at c000
00000000a8fc replay_interrupt_return+0x0/0x4
[link register   ] c000000000012a80 arch_local_irq_restore+0x5c/0x80
[c000001ff74d3da0] 0000000000462eff (unreliable)
[c000001ff74d3dc0] c000000000334334 cpuidle_enter_state+0x1a0/0x20c
[c000001ff74d3e10] c0000000000a0ee0 call_cpuidle+0x6c/0x74
[c000001ff74d3e30] c0000000000a12f0 do_idle+0x250/0x280
[c000001ff74d3ec0] c0000000000a14ac cpu_startup_entry+0x30/0x34
[c000001ff74d3ef0] c00000000002e988 start_secondary+0x3bc/0x528
[c000001ff74d3f90] c00000000
000ac70 start_secondary_prolog+0x10/0x14
2c:mon>
```

**Comment by stewart-ibm** [comment]
tail of kernel log:

```
[   14.645580] random: crng init done                                                                                                                             
[   14.645583] random: 7 urandom warning(s) missed due to ratelimiting                                                                                            
[   15.442215] mpt3sas_cm0: port enable: SUCCESS                                                                                                                  
[   15.682158] mpt3sas_cm1: port enable: SUCCESS                                                                                                                  
[   16.072132] mpt3sas_cm2: port enable: SUCCESS                                                                                                                  
[   16.312133] mpt3sas_cm3: port enable: SUCCESS                                                                                                                  
[   16.318727] scsi 4:0:0:0: Attached scsi generic sg0 type 0                                                                                                     
[   16.325607] sd 4:0:0:0: [sda] 30253056 512-byte logical blocks: (15.5 GB/14.4 GiB)                                                                             
[   16.326928] sd 4:0:0:0: [sda] Write Protect is off                                                                                                             
[   16.326931] sd 4:0:0:0: [sda] Mode Sense: 45 00 00 00                         
[   16.329303] sd 4:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA                                                           
[   16.376901]  sda: sda1               
[   16.379476] sd 4:0:0:0: [sda] Attached SCSI removable disk                    
[   16.407899] device-mapper: ioctl: 4.39.0-ioctl (2018-04-03) initialised: dm-devel@redhat.com                                                                   
[   16.461800] ISO 9660 Extensions: RRIP_1991A                                   
[   23.632940] aacraid: Comm Interface type3 enabled   
[   27.033789] AAC0: kernel 2.99-0[16] Apr 13 2017
[   27.033790] AAC0: monitor 0.0-0[0]
[   27.033792] AAC0: bios 0.13-209[32000]
[   27.033793] AAC0: serial 10F447
[   27.033794] AAC0: Non-DASD support enabled.
[   27.033795] AAC0: 64bit support enabled.
[   27.033799] aacraid 0003:01:00.0: Using 64-bit DMA iommu bypass
[   27.033803] aacraid 0003:01:00.0: 64 Bit DAC enabled
[   27.056373] scsi host0: aacraid
[   27.093973] scsi 0:2:1:0: Direct-Access     SEAGATE  ST2000NM0045     N003 PQ: 0 ANSI: 6
[   27.096134] sd 0:2:1:0: Attached scsi generic sg1 type 0
[   27.102666] sd 0:2:1:0: [sdb] 3907029168 512-byte logical blocks: (2.00 TB/1.82 TiB)
[   27.104215] sd 0:2:1:0: [sdb] Write Protect is off
[   27.104218] sd 0:2:1:0: [sdb] Mode Sense: db 00 10 08
[   27.107467] sd 0:2:1:0: [sdb] Write cache: enabled, read cache: enabled, supports DPO and FUA
[   27.112690] scsi 0:2:2:0: Direct-Access     SEAGATE  ST2000NM0045     N003 PQ: 0 ANSI: 6
[   27.116995] sd 0:2:2:0: Attached scsi generic sg2 type 0
[   27.118704] scsi 0:3:123:0: Enclosure         ADAPTEC  Smart Adapter    2.99 PQ: 0 ANSI: 5
[   27.119506] scsi 0:3:123:0: Attached scsi generic sg3 type 13
[   27.122617] sd 0:2:2:0: [sdc] 3907029168 512-byte logical blocks: (2.00 TB/1.82 TiB)
[   27.124050] sd 0:2:2:0: [sdc] Write Protect is off
[   27.124055] sd 0:2:2:0: [sdc] Mode Sense: db 00 10 08
[   27.125936] sd 0:2:2:0: [sdc] Write cache: enabled, read cache: enabled, supports DPO and FUA
[   27.135457]  sdb: sdb1 sdb2 sdb3
[   27.142926] sd 0:2:1:0: [sdb] Attached SCSI disk
[   27.172876]  sdc: sdc1 sdc2
[   27.179961] sd 0:2:2:0: [sdc] Attached SCSI disk
[   27.346994] Unable to handle kernel paging request for data at address 0x1ffdbc0004
[   27.346997] Faulting instruction address: 0xc00000000047d72c
```

**Comment by mpe** [comment]
Regs are:
```
2c:mon> r
R00 = c00000000047d8ac   R16 = 0000000000000100
R01 = c000001ff74d3960   R17 = c000000001d00100
R02 = c000000001cdb000   R18 = 0000000000000000
R03 = 0000000000000000   R19 = c000000001d00100
R04 = 0000000000000000   R20 = c000001ff74d0000
R05 = c000001fbd1c3800   R21 = c000000001c60d80
R06 = c000001fbd1c3b90   R22 = 0000000000000001
R07 = c000001bac3e2000   R23 = 0000000000000000
R08 = 0000001ffdbc0000   R24 = 0000000000000028
R09 = 0000001ffdbc0000   R25 = c000000001d01a00
R10 = 0000000000000000   R26 = 00000000ffff9580
R11 = 00000000000563ed   R27 = 0000000000200042
R12 = 0000000000004000   R28 = 0000000000000009
R13 = c000001ffffde600   R29 = 0000000000000010
R14 = 0000000000000020   R30 = c000001ff74d0000
R15 = 0000000000000004   R31 = 0000000000000004
pc  = c00000000047d72c __do_softirq+0xd4/0x2b0
cfar= c00000000047d7ac __do_softirq+0x154/0x2b0
lr  = c00000000047d8ac __do_softirq+0x254/0x2b0
msr = 9000000000009033   cr  = 48004224
ctr = 0000000000000000   xer = 0000000020040000   trap =  300
dar = 0000001ffdbc0004   dsisr = 42000000
```

We're in `__do_softirq`:

```
c00000000047d714  7ff5fb78	mr      r21,r31		backup r31 into r21 = c000000001c60d80
c00000000047d718  7fd4f378	mr      r20,r30
restart:
c00000000047d71c  e92d0028	ld      r9,40(r13)	r9 = paca->data_offset (percpu offset)
c00000000047d720  3e220002	addis   r17,r2,2
c00000000047d724  38600000	li      r3,0
c00000000047d728  3a315100	addi    r17,r17,20736
c00000000047d72c  7ee9f92e	stwx    r23,r9,r31	<- fault, r31 = 0x4
	set_softirq_pending(0);
```

So the compiler is putting the address of `local_softirq_pending_ref` in `r31`, but when we do the store we fault and see that `r31` is `0x4`. Presumably what's happened is we've done the body of the loop and jumped back to the label at `restart`. Something in the loop has corrupted `r31`.

Note for some reason the compiler is using `r21` to do the load of `local_softirq_pending_ref` in `local_softirq_pending()` prior to the `goto restart`, so that succeeds.

Nothing else in the function is using `r31`, which makes sense otherwise the compiler would need to reload it prior to the load.

So it's possible we have a softirq handler that is clobbering `r31`, or it's happening as part of irq replay in `local_irq_enable()` -> `arch_local_irq_enable()` -> `arch_local_irq_restore()` -> `__replay_interrupt()`.

We tend not to use `r31` in hand written asm (because it has to be saved), so there's not *too* many candidates, though still a lot.

**Comment by shenki** [comment]
See https://github.com/open-power/op-build/issues/2660

**Comment by shenki** [comment]
We will skip 4.20 and go to 5.0 :(

**Pull request closed without merging**
