### PR TITLE
RaptorCS Blackbird support

### PR DESCRIPTION
**Pull request by stewartsmith**
Hostboot config is basically Witherspoon but with LPC PORT 80h turned on
defconfig is from Witherspoon, with Blackbird XML setup from Raptor's tree.

NOTE: without linux v5.4.3 (or at least anything more recent than v5.3.7) my Intel SSD doesn't show up in Petitboot.

Also note that the blackbird-xml project doesn't yet existing in the open-power org, so you need to grab it from my repo (or Raptor's). Consider this a request to branch mine in :)

Signed-off-by: Stewart Smith <stewart@flamingspork.com>

### CODE REVIEW

**Comment by stewartsmith** [comment]
I've sent the skiboot patch upstream: https://patchwork.ozlabs.org/patch/1208967/

**Comment by sharkcz** [comment]
Hmm, I guess I should make the same for Talos :-)

**Comment by madscientist159** [comment]
Did the IPL observer stuff ever make its way in to upstream?  Especially w/ Talos II it's pretty critical. ;)

**Comment by stewartsmith** [comment]
On Sun, Dec 15, 2019, at 10:45 PM, Timothy Pearson wrote:
> Did the IPL observer stuff ever make its way in to upstream? Especially 
> w/ Talos II it's pretty critical. ;)

Not sure on the BMC side.

The host side, we have it upstream in skiboot, but the hostboot part isn't there, and there's nothing in the petitboot environment which would do the final write of 254,254.

**Comment by sharkcz** [comment]
I have started https://wiki.raptorcs.com/wiki/Firmware_Upstreaming (it got few changes from @merklort for the hostboot part) some time ago, probably based on the Talos GA branch (2018-04-19), not on the v2 firmware (2019-04-16).

**Comment by madscientist159** [comment]
I know that was one of the main blockers to upstreaming -- we don't want to have the support issues associated with OCC reads during IPL (or completely disables fan controls, for that matter).  The former in particular was quite expensive as the symptoms lead to spurious mainboard / CPU RMA in some cases and escalation to higher level support in many others.

While I'd really like to see upstream support, we need to have the IPL observer support merged into the subcomponents first.  Any chance that can happen?

**Comment by sharkcz** [comment]
Can't we start with the machine specific "overlay" in openpower/patches/talos-patches until they are properly upstreamed? How much of the non-upstream patches is shared between Blackbird and Talos?

**Comment by stewartsmith** [comment]
It’s probably a fair bit. I’ll try and get an updated PR sometime in the next day or so

**Comment by dcrowell77** [comment]
There were some internal network issues recently so I'm guessing that is what the CI fail probably is.

**Comment by dcrowell77** [comment]
retest this please

**Comment by madscientist159** [comment]
> Can't we start with the machine specific "overlay" in openpower/patches/talos-patches until they are properly upstreamed? How much of the non-upstream patches is shared between Blackbird and Talos?

Yes, a local set of patches combined with a RCS overlay directory would work.  Most of the modifications are common between Talos II / Blackbird / Condor; please feel free to pull whatever you need from our repos as we have retained the original Apache / GPL / BSD licenses for the modified components (newly written components are normally GPL v3 from our side, licenses are in the file headers).

**Comment by stewartsmith** [comment]
The v2 for skiboot patch, which talks IPL Observer: https://patchwork.ozlabs.org/patch/1210958/

**Comment by oohal** [comment]
retest this please

**Comment by madscientist159** [comment]
@stewartsmith Getting the IPL observer stuff into the SBE and hostboot would also be good -- in particular, the SBE patches (in our tree) drive the progress bar during the first part of the Blackbird boot, and have proven very useful over time to determine bad CPUs / sockets from hostboot issues at a glance.

**Comment by stewartsmith** [comment]
hoping we can have someone still working for IBM push the SBE patches, I’m a bit less inclined to mess with mine now that I don’t have crorecoversbe laying around...

**Comment by madscientist159** [comment]
I'd be willing to test any patches to upstream, since I do have access to the recovery system...

**Comment by madscientist159** [comment]
Just dug this back up:
https://github.com/open-power/sbe/pull/15

**Comment by sharkcz** [comment]
I have updated https://wiki.raptorcs.com/wiki/Firmware_Upstreaming with SBE, HCODE, OCC and Hostboot. Seems there is just few changes in the Raptor branches for these components.

**Comment by madscientist159** [comment]
Most center around the IPL observer, bit frustrating to have the simple PRs sit for > 8 months TBH.

**Comment by dcrowell77** [comment]
Is the SBE PR the only one outstanding?  I understand the frustration, I'll try to shake a tree.

**Comment by sharkcz** [comment]
If I see right in the wiki page above, then we need https://git.raptorcs.com/git/talos-hostboot/commit/?id=d90e6c513094231f622a427030f3dbca1eeb5ed5 for the hostboot part. @madscientist159 will know if there has been a PR already.

**Comment by dcrowell77** [comment]
Of course the link was added after I read it.  It looks like 3 new commits.  Make some PRs and I'll at least get them into the pipeline (with no promises on getting a lot of attention).

**Comment by sharkcz** [comment]
op-build WIP with Talos support = https://github.com/sharkcz/op-build/tree/talos
skiboot WIP with Talos using LPC observer = https://github.com/sharkcz/skiboot/tree/talos-lpc

be aware, not even compile tested

**Comment by madscientist159** [comment]
FWIW 0xfefe is the IPL observer code for Linux online and userspace launched.  Skiboot should NOT be sending it; it confuses two parts of the process and tells the BMC IPL has successfully finished when in fact it's only partially done.

**Comment by sharkcz** [comment]
@madscientist159, I understand your position. The open question is, whether there is a way to do the signalling correctly and upstreamable. How do the other platforms handle this kind of communication between the host and BMC?

**Comment by madscientist159** [comment]
@sharkcz I've seen a bunch of different methods over the years including writes to scratch registers in the south bridge.  What is wrong with a small userspace tool poking the last status code out the LPC port?

**Comment by sharkcz** [comment]
@madscientist159, nothing is wrong, it's for my education and overview :-) Also I'm thinking how it could be integrated into upstream.

**Comment by madscientist159** [comment]
@sharkcz we actually need an LPC access module for other reasons, something that can allow root to read / write bytes, nothing fancy.  I can see why it might be desirable to disable the debug interface, but LPC access is a useful and reasonable thing to have.

I wonder if we can do a simple device node that takes basic commands like IO_LPC_SET_TARGET_ADDRESS, IO_LPC_WRITE_BYTE, IO_LPC_READ_BYTE?

**Comment by stewartsmith** [comment]
We won’t have debugfs mounted in any secure mode

**Comment by stewartsmith** [comment]
What alternate code can I send down that kicks on fan control? By the time skiboot exits there’s nothing touching anything that wouldn’t happen during Normal runtime

**Comment by madscientist159** [comment]
Would there be an objection to an LPC access module in secure mode, if we were to write one?

**Comment by stewartsmith** [comment]
Something that did just this poke? Probably not. But arbitrary access? Yeah.

**Comment by madscientist159** [comment]
Yeah was looking at arbitrary access, see my post a few above about a possible IO_ access mechanism around /dev/lpc or similar.

**Pull request merged**
