### PR TITLE
petitboot: Update to v1.14

### PR DESCRIPTION
**Pull request by rarbab**
This release has fixes for a few issues we've seen in the field.

### CODE REVIEW

**Comment by IlyaSmirnov91** [comment]
@rarbab , looks like the OPAL simics fail is related: https://sys-powerfw-jenkins.swg-devops.com/job/PowerFW/job/CI/job/simics-ci/job/rainier_2s2u_opal_rhel/481/consoleFull

**Comment by IlyaSmirnov91** [comment]
> @IlyaSmirnov91 I don't think the failure has anything to do with the change itself. Seems like a CI problem?
> 
> ```
> 13:34:33  13:34:33 [Error] mkdir /gsa/ausgsa: permission denied
> [Pipeline] catchError
> [Pipeline] {
> [Pipeline] error
> [Pipeline] }
> 13:34:33  ERROR: Failure in simics-ci/rainier_2s2u_opal_rhel
> 13:34:33  ERROR: script returned exit code 1
> ```

Ah, yeah, you're right. Let me respin the job.

**Comment by IlyaSmirnov91** [comment]
@rarbab , CI looks good. It this ready to merge?

**Comment by rarbab** [comment]
Yes! Thanks.

**Pull request merged**
