### PR TITLE
Reduce BOOTKERNEL size

### PR DESCRIPTION
**Pull request by stewart-ibm**
This goes someway towards resyncing our kernel defconfigs with sanity, along with fixing a long standing issue where we'd needlessly build i2c-tools when we already had perfectly good busybox implementations.

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1205)

### CODE REVIEW

**Comment by pridhiviraj** [comment]
@stewart-ibm this busy box version of i2c-tools will have any impact our i2c tests we have implemented for skiroot in op-test.

**Comment by pragupta** [comment]
retest this please

**Comment by stewart-ibm** [comment]
@pridhiviraj I don't think it will, I have tested in the past and it's been okay.

**Comment by pridhiviraj** [comment]
@stewart-ibm Cool, Thanks.

**Pull request merged**
