### PR TITLE
Kernel 5.0.6

### PR DESCRIPTION
**Pull request by shenki**

### CODE REVIEW

**Comment by shenki** [comment]
Replaces https://github.com/open-power/op-build/pull/2749

**Comment by stewart-ibm** [comment]
```
cpu 0x27: Vector: 380 (Data Access Out of Range) at [c000001ff537b2d0]
    pc: c0000000001fe754: blk_add_timer+0x2c/0xa4
    lr: c0000000002001d4: blk_mq_start_request+0xa8/0xe0
    sp: c000001ff537b560
   msr: 9000000000009033
   dar: 43f900c0000020d3
  current = 0xc000001ff52dd880
  paca    = 0xc000001ffffe1f80     irqmask: 0x03     irq_happened: 0x01
    pid   = 812, comm = kworker/u321:1
Linux version 5.0.6-openpower1 (hostboot@gfw273.aus.stglabs.ibm.com) (gcc version 6.5.0 (Buildroot 2019.02.1-00015-gc5f183f)) #2 SMP Wed Apr 3 04:45:56 CDT 2019
enter ? for help
[c000001ff537b590] c0000000002001d4 blk_mq_start_request+0xa8/0xe0
[c000001ff537b5c0] c0000000002d25b0 scsi_queue_rq+0x508/0x810
[c000001ff537b660] c0000000002023c0 blk_mq_dispatch_rq_list+0x474/0x5c0
[c000001ff537b720] c000000000207360 blk_mq_sched_dispatch_requests+0x114/0x18c
[c000001ff537b780] c000000000200834 __blk_mq_run_hw_queue+0xe0/0xf8
[c000001ff537b800] c0000000002008ac __blk_mq_delay_run_hw_queue+0x60/0x184
[c000001ff537b860] c000000000200a70 blk_mq_run_hw_queue+0x70/0xe4
[c000001ff537b8b0] c0000000002075ec blk_mq_sched_insert_request+0x68/0x194
[c000001ff537b910] c0000000001fc028 blk_execute_rq_nowait+0x78/0x8c
[c000001ff537b930] c0000000001fc084 blk_execute_rq+0x48/0x90
[c000001ff537b980] c0000000002cf7b0 __scsi_execute+0xd8/0x1ac
[c000001ff537b9f0] c0000000002d3bd0 scsi_probe_and_add_lun+0x1ec/0xa48
[c000001ff537bb40] c0000000002d4778 __scsi_add_device+0xf4/0xf8
[c000001ff537bba0] c0000000002ef068 ata_scsi_scan_host+0xf4/0x1fc
[c000001ff537bc30] c0000000002e94b4 async_port_probe+0x6c/0x78
[c000001ff537bc60] c00000000009a0b0 async_run_entry_fn+0x68/0x138
[c000001ff537bca0] c0000000000907e0 process_one_work+0x204/0x334
[c000001ff537bd30] c000000000090c2c worker_thread+0x2d0/0x394
[c000001ff537bdb0] c000000000096c3c kthread+0x14c/0x154
[c000001ff537be20] c00000000000b72c ret_from_kernel_thread+0x5c/0x70
27:mon>
```

Well, that's interesting.

5.0.5 seemed to pass, so I've merged that PR. Hopefully this is something introduced between 5.0.5 and 5.0.6. I guess I know what we're looking at today! :)

**Comment by shenki** [comment]
This was just merged into 5.1:

```
commit fd9c40f64c514bdc585a21e2e33fa5f83ca8811b
Author: Bart Van Assche <bvanassche@acm.org>
Date:   Fri Apr 5 03:38:43 2019

    block: Revert v5.0 blk_mq_request_issue_directly() changes
    
    blk_mq_try_issue_directly() can return BLK_STS*_RESOURCE for requests that
    have been queued. If that happens when blk_mq_try_issue_directly() is called
    by the dm-mpath driver then dm-mpath will try to resubmit a request that is
    already queued and a kernel crash follows. Since it is nontrivial to fix
    blk_mq_request_issue_directly(), revert the blk_mq_request_issue_directly()
    changes that went into kernel v5.0.
    
    This patch reverts the following commits:
    * d6a51a97c0b2 ("blk-mq: replace and kill blk_mq_request_issue_directly") # v5.0.
    * 5b7a6f128aad ("blk-mq: issue directly with bypass 'false' in blk_mq_sched_insert_requests") # v5.0.
    * 7f556a44e61d ("blk-mq: refactor the code of issue request directly") # v5.0.
```

**Comment by stewart-ibm** [comment]
Joel Stanley <notifications@github.com> writes:
> This was just merged into 5.1:
>
> ```
> commit fd9c40f64c514bdc585a21e2e33fa5f83ca8811b
> Author: Bart Van Assche <bvanassche@acm.org>
> Date:   Fri Apr 5 03:38:43 2019
>
>     block: Revert v5.0 blk_mq_request_issue_directly() changes
>     
>     blk_mq_try_issue_directly() can return BLK_STS*_RESOURCE for requests that
>     have been queued. If that happens when blk_mq_try_issue_directly() is called
>     by the dm-mpath driver then dm-mpath will try to resubmit a request that is
>     already queued and a kernel crash follows. Since it is nontrivial to fix
>     blk_mq_request_issue_directly(), revert the blk_mq_request_issue_directly()
>     changes that went into kernel v5.0.
>     
>     This patch reverts the following commits:
>     * d6a51a97c0b2 ("blk-mq: replace and kill blk_mq_request_issue_directly") # v5.0.
>     * 5b7a6f128aad ("blk-mq: issue directly with bypass 'false' in blk_mq_sched_insert_requests") # v5.0.
>     * 7f556a44e61d ("blk-mq: refactor the code of issue request directly") # v5.0.
> ```

Huh. Mangaged to hit that on all my weekend test runs, so I guess it's
good we're getting a fix.

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by shenki** [comment]
retest this please

**Comment by shenki** [comment]
AIUI, the backtrace will happen with any of the 5.0 kernels.

I assume this fix will show up in 5.0.8. I've backported it to 5.0.7-openpower1:

 https://github.com/open-power/op-build/pull/2768

**Pull request closed without merging**
