### PR TITLE
Patch for istep5 performance

### PR DESCRIPTION
**Pull request by sgupta2m**
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1021)

### CODE REVIEW

**Comment by sannerd** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openpower/package/sbe/sbe.mk, line 17 at r1](https://reviewable.io:443/reviews/open-power/op-build/1021#-KhbYvbDrEaskv6I9N2o:-KhbYvbDrEaskv6I9N2p:b-e6pcb5) ([raw file](https://github.com/open-power/op-build/blob/5ed2b6b132760d599d7a2ca8674e13b6793d3af7/openpower/package/sbe/sbe.mk#L17)):*
> ```Makefile
> 
> 
> define SBE_APPLY_PATCHES
> ```

I don't think this is necessarily needed, as op-build supports this by default.  I don't think this hurts though (maybe applies 2X, which would fail silently)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/op-build/1021#-:-KhbbceGZoY8o5g8A3An:bnfp4nl)*

**Comment by sannerd** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/op-build/1021#-:-KhbdYdm-nnwl790l--c:bnfp4nl)*

**Comment by wghoffa** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openpower/package/sbe/sbe.mk, line 17 at r1](https://reviewable.io:443/reviews/open-power/op-build/1021#-KhbYvbDrEaskv6I9N2o:-KheC7OswYdWo1wYg6Zi:b-dfmdz1) ([raw file](https://github.com/open-power/op-build/blob/5ed2b6b132760d599d7a2ca8674e13b6793d3af7/openpower/package/sbe/sbe.mk#L17)):*
<details><summary><i>Previously, sannerd wrote…</i></summary><blockquote>

I don't think this is necessarily needed, as op-build supports this by default.  I don't think this hurts though (maybe applies 2X, which would fail silently)?
</blockquote></details>

Applying a 2nd time won't fail silently forever. In P8-land if a patch failed to apply it halted the compile.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/op-build/1021)*

**Comment by sgupta2m** [comment]
I have done same as HB. I will remove the SBE_APPLY_PATCHES in next patch.

**Comment by sannerd** [comment]
The special handling is for the P8/P9 sub directories.  op-build applies base level patches by default.

**Pull request closed without merging**
