### PR TITLE
Buildroot 2019.02

### PR DESCRIPTION
**Pull request by shenki**

### CODE REVIEW

**Comment by shenki** [comment]
This looks good. I did a test build locally and ran op-test against it on a romulus.

I didn't see any objections on the mailing list about requiring Python 2.7, so I think we should merge this as soon as 2.2 is tagged.

**Comment by dcrowell77** [comment]
I believe we are still working on support plans internally.  I think @ravimed1 is driving it

**Comment by danlarson-ibm** [comment]
retest this please

**Comment by danlarson-ibm** [comment]
retest this please

**Comment by wghoffa** [comment]
retest this please

**Comment by crgeddes** [comment]
Can one of the admins verify this patch?

**Comment by shenki** [comment]
Retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Pull request merged**
