### PR TITLE
kernel: Move to Linux v5.3.5-openpower1

### PR DESCRIPTION
**Pull request by shenki**
This adds Firmware Assissted dump passthrough mode to the OpenPower
kernel. These patches were backported from 5.4, and the
CONFIG_PRESERVE_FA_DUMP was added.

PowerPC related changes:

 powerpc: dump kernel log before carrying out fadump or kdump
 powerpc/eeh: Clean up EEH PEs after recovery finishes
 powerpc/64s/exception: machine check use correct cfar for late handler
 powerpc/eeh: Clear stale EEH_DEV_NO_HANDLER flag
 powerpc/perf: fix imc allocation failure handling
 powerpc/64s/radix: Fix memory hotplug section page table creation
 powerpc/futex: Fix warning: 'oldval' may be used uninitialized in this function
 powerpc/ptdump: fix walk_pagetables() address mismatch
 powerpc/rtas: use device model APIs and serialization during LPM
 powerpc/xmon: Check for HV mode when dumping XIVE info from OPAL
 powerpc/powernv/ioda2: Allocate TCE table levels on demand for default DMA window
 powerpc/imc: Dont create debugfs files for cpu-less nodes
 powerpc/Makefile: Always pass --synthetic to nm if supported
 powerpc/xive: Fix bogus error code returned by OPAL

Signed-off-by: Joel Stanley <joel@jms.id.au>

### CODE REVIEW

**Comment by hegdevasant** [comment]
retest this please

**Comment by shenki** [comment]
I have rebased on master and retriggered. This can go in once CI passes.

**Comment by shenki** [comment]
retest this please

**Comment by hegdevasant** [comment]
> I have rebased on master and retriggered. This can go in once CI passes.

Sorry for the trouble. I used new user to create skiboot PR.. that didn't trigger hostboot CI.
I didn't realize that and merged skiboot PR.. that resulted in CI failures.

Thanks for the rebase.


-Vasant

**Comment by oohal** [comment]
retest this please

**Comment by klauskiwi** [comment]
looks like the witherspoon build failed due to max size reached. I couldn't track, however, why the other tests succeeded apparently...

```
cd build/buildpnor/ && /usr/bin/make --no-print-directory --no-builtin-rules --no-builtin-variables buildpnor
true
../src/build/trace/tracehash_hb.pl -c -d ../obj -s ../img/hbotStringFile
make[6]: Nothing to be done for 'buildpnor'.
    GENLIST    hbibl
ERROR: ../img/hbibl.bin too large. Max allowed size is 32768
    GENLIST    hbicore
makefile:435: recipe for target 'imgsizecheck' failed
make[5]: *** [imgsizecheck] Error 1
make[5]: *** Waiting for unfinished jobs....
    GENLIST    hbicore_test
```

**Comment by dcrowell77** [comment]
I'm guessing it is related to the ppc build like all of the other issues we've had there lately...

**Comment by shenki** [comment]
retest this please

**Comment by shenki** [comment]
```
//============= Generate PNOR Image Settings ===========//
PNOR Layout = /scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/build/openpower-pnor-bdfd0d08a7a04b1326553f570d35e778eda9db81/p9Layouts/defaultPnorLayout_64.xml
Emit ECC-less versions of output files, when possible = No
Test Mode = No
Secureboot = Disabled
Sign Mode = NA
Key Transition Mode = NA
Lab security override (valid for SBE partition only) = Yes
//======================================================//

1Loading bin files...
TRACE: manipulateImages
HBBL raw size (/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HBBL.staged) (no padding/ecc) = 74744/20480
HBBL cannot fit HW Keys' Hash (64 bytes) at the end without overwriting real data at /scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/hostboot_build_images//genPnorImages.pl line 630.
Error running command: cd /scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch/ && /scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/hostboot_build_images//genPnorImages.pl --binDir /scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch/ --systemBinFiles HBEL=EMPTY,CVPD=/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//CVPD.staged,ATTR_TMP=EMPTY,HBRT=/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HBRT.staged,RINGOVD=EMPTY,DJVPD=EMPTY,CAPP=/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//CAPP.staged,VERSION=/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//VERSION.staged,OCC=/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//OCC.staged,PAYLOAD=/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//PAYLOAD.staged,HBI=/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HBI.staged,MEMD=/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//MEMD.staged,SBE=/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//SBE.staged,NVRAM=EMPTY,SBKT=EMPTY,HCODE=/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HCODE.staged,HBD=/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HBD.staged,GUARD=EMPTY,SECBOOT=EMPTY,BOOTKERNEL=/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//BOOTKERNEL.staged,MVPD=EMPTY,ATTR_PERM=EMPTY,IMA_CATALOG=/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//IMA_CATALOG.staged,HBBL=/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HBBL.staged,WOFDATA=/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//WOFDATA.staged,HDAT=EMPTY,FIRDATA=EMPTY,HBB=/scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HBB.staged --pnorLayout /scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/build/openpower-pnor-bdfd0d08a7a04b1326553f570d35e778eda9db81/p9Layouts/defaultPnorLayout_64.xml   --sign-mode development --hwKeyHashFile /scratch/jenkins/workspace/op-build/op-build-PR/PLATFORM/p9dsu/label_exp/austin/output-ubuntu1804-p9dsu_defconfig/host/powerpc64le-buildroot-linux-gnu/sysroot/hostboot_build_images//imprintHwKeyHash. Nonzero return code of (6400) returned.
```

**Comment by shenki** [comment]
retest this please

**Comment by shenki** [comment]
retest this please

**Comment by shenki** [comment]
retest this please

**Comment by shenki** [comment]
retest this please

**Pull request merged**
