### PR TITLE
Suppress shutdown messages

### PR DESCRIPTION
**Pull request by shenki**

### CODE REVIEW

**Comment by shenki** [comment]
retest this please

**Comment by shenki** [comment]
This was hitting https://github.com/open-power/op-build/issues/2430. However, I have since discovered we have the `openpower/custom/patches/` global patch directory which is included for all systems via `openpower/external.mk`. I will use this instead of attempting to add another directory to `BR2_GLOBAL_PATCH_DIR`.

**Comment by shenki** [comment]
This one looks good to go now

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Pull request merged**
