### PR TITLE
petitboot: Update to v1.11

### PR DESCRIPTION
**Pull request by klauskiwi**
This change bumps us up to petitboot v1.11, which includes fixes for
GRUB2 parsing, and IPMI mailbox message handling.

Jeremy Kerr (16):
      pb-console: start shell as a login shell
      pb-console: don't modify PATH unless it's empty
      discover/grub2: 'search' set-variable defaults to root
      discover/grub2: Use getopt for `search` argument parsing
      discover/grub2: test for (ignored) --no-floppy argument
      discover/grub2: Add support for UUID and label for 'search' command
      discover/grub2: expose a struct for grub2 file references
      discover/grub2: Add parsing code for grub2 file specifiers
      discover/grub2: add support for grub2-style path specifiers in resources
      discover/grub2: Allow (device)/path references in general script usage
      discover/grub2: Add a reference from script to parser
      discover/grub2: expose internal parse function
      discover/grub2: make statements_execute non-static
      discover/grub2: implement 'source' command
      test/parser: Add test for recent RHCOS grub2 config
      test/parser: Add RHEL8 grub config test

Maxim Polyakov (5):
      discover/platform-powerpc: add missing mbox block selector
      discover/platform-powerpc: limit mailbox response size
      discover/platform-powerpc: return the actual mailbox size
      discover/platform-powerpc: add mailbox message structure
      discover/platform-powerpc: don't copy IANA from mbox to buffer

Signed-off-by: Jeremy Kerr <jk@ozlabs.org>
(cherry picked from commit e333db3e19cee6a43ccf56606b43956325f9b0d9)

### CODE REVIEW

**Comment by klauskiwi** [comment]
retest this please

**Comment by hegdevasant** [comment]
petitboot moving from v1.7.5 to v1.11 is big jump for stable release.

Can't you just backport required patches? 

-Vasant

**Comment by klauskiwi** [comment]
> petitboot moving from v1.7.5 to v1.11 is big jump for stable release.
> 
> Can't you just backport required patches?

There were a significant number of dependencies/changes required on the parsing side...

**Comment by stewartsmith** [comment]
the changelog doesn't look to be v1.7.5 to v1.11

Are there any other dependencies for petitboot in op-build?

I agree with Vasant, it's a huge bump.

**Comment by hegdevasant** [comment]
> > petitboot moving from v1.7.5 to v1.11 is big jump for stable release.
> > Can't you just backport required patches?
> 
> There were a significant number of dependencies/changes required on the parsing side...

This still doesn't explain what specific changes you want in 2.0.y branch and why? Its not a good idea to push new releases to stable branch. AFAIK we just just cherry-pick/backport important fixes.

-Vasant

**Comment by youhour** [comment]
I'm not able to do a successful build of op-build-2.0.y with this pull request.  Without this pull request I was able to build successfully.  Look like there are more change to a Boston config file in order to include this pull request.

Here is a snapshot of the build failure
*************************************************************************
Please run 'aclocal -I m4' to regenerate the aclocal.m4 file.
You need aclocal from GNU automake 1.9 (or newer) to do this.
Then run 'autoconf' to regenerate the configure file.

You will also need config.guess and config.sub, which you can get from the CVS
of the 'config' project at http://savannah.gnu.org/. The commands to fetch them
are
$ wget 'http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.guess'
$ wget 'http://savannah.gnu.org/cgi-bin/viewcvs/*checkout*/config/config/config.sub'

You might also want to copy the convenience header file gettext.h
from the /esw/san5/youhour/bostonLC/opBuild20y/b20191216a/op-build/output/host/share/gettext directory into your package.
It is a wrapper around <libintl.h> that implements the configure --disable-nls
option.

Press Return to acknowledge the previous three paragraphs.
>>> petitboot v1.11 Autoreconfiguring
configure.ac:488: error: `po/Makefile.in' is already registered with AC_CONFIG_FILES.
../../lib/autoconf/status.m4:288: AC_CONFIG_FILES is expanded from...
configure.ac:488: the top level
autom4te: /esw/san5/youhour/bostonLC/opBuild20y/b20191216a/op-build/output/host/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: /esw/san5/youhour/bostonLC/opBuild20y/b20191216a/op-build/output/host/bin/aclocal failed with exit status: 1
make[1]: *** [/esw/san5/youhour/bostonLC/opBuild20y/b20191216a/op-build/output/build/petitboot-v1.11/.stamp_configured] Error 1
make: *** [_all] Error 2
make: Leaving directory `/esw/san5/youhour/bostonLC/opBuild20y/b20191216a/op-build/buildroot'
***********************************************************************

At this point PR 3334 is a no go.

**Comment by klauskiwi** [comment]
Made an attempt at backporting the necessary bits in https://github.com/open-power/op-build/pull/3355

**Comment by klauskiwi** [comment]
this was made obsolete by #3460

**Pull request closed without merging**
