### PR TITLE
skiroot: pull the latest stable release for kernel

### PR DESCRIPTION
**Pull request by naynajain**
This PR is to ask for upgrade of skiroot kernel to latest stable release.

Currently, IMA boot_aggregate measurement test is failing because skiroot kernel currently doesn't support extends to PCR 8 & 9 which are now included in boot aggregate.

The fix for that is available in the stable kernel. I have tested it with version 5.4.98 pulled from - https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git

I am not sure how the process for updating stable versions fetched by skiroot works, this PR is to start the discussion and get it updated.

Thanks & Regards,
     - Nayna

### CODE REVIEW

**Comment by klauskiwi** [comment]
ok to test

@shenki what's your preference for handling stable kernel updates? you want to update https://github.com/open-power/linux/ with a new tag, do you want me to do it? It's up to you.

**Comment by naynajain** [comment]
Will this update to skiroot also make to Mowgli and witherspoon ?

**Comment by shenki** [comment]
I pushed a new version to openpower/linux and created a pull request for it here:

https://github.com/open-power/op-build/pull/4045

I recommend closing this PR and using that one instead.

**Comment by klauskiwi** [comment]
Thanks Joel. Closing as this was made obsolete by #4045

**Pull request closed without merging**
