### PR TITLE
Patches to fix IPL fails in istep7.4 on Witherspoon

### PR DESCRIPTION
**Pull request by wghoffa**
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/900)

### CODE REVIEW

**Comment by e-liner** [comment]
retest this please

**Comment by e-liner** [comment]
retest this please

**Comment by wghoffa** [comment]
Recreating with more fixes since this didn't go in yet.

**Comment by wghoffa** [comment]
Newer fix here: https://github.com/open-power/op-build/pull/902. Closing this one.

**Pull request closed without merging**
