### PR TITLE
Add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by stewart-ibm**
Comments / additions welcome.

This is for when we're fully on the "s/master-next/master/; s/master/release/" bandwagon (i.e. the end of the month)

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/850)

### CODE REVIEW

**Comment by ajdlinux** [comment]
LGTM, as a complete outsider...

Reviewed-by: Andrew Donnellan <andrew.donnellan@au1.ibm.com>

**Comment by stewart-ibm** [comment]
(slightly tweaked first paragraph based on feedback from Pam Eggler)

**Comment by stewart-ibm** [comment]
Added mention of "master-next" and timeline of phasing it out after @mzipse review.

**Comment by stewart-ibm** [comment]
(just rebased, so as to have a nicer git history of when this was introduced)

**Pull request merged**
