### PR TITLE
QLogic Fibre Channel support for Boston

### PR DESCRIPTION
**Pull request by shenki**

### CODE REVIEW

**Comment by stewart-ibm** [comment]
`
Opening Robot Framework log failed

    Verify that you have JavaScript enabled in your browser.
    Make sure you are using a modern enough browser. Firefox 3.5, IE 8, or equivalent is required, newer browsers are recommended.
    Check are there messages in your browser's JavaScript error log. Please report the problem if you suspect you have encountered a bug.

`

Robot 💩 

urgh.

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by sammj** [comment]
```
op-build-pull-request » witherspoon completed with result SUCCESS
op-build-pull-request » openpower_p9_mambo completed with result SUCCESS
op-build-pull-request » romulus completed with result SUCCESS
op-build-pull-request » palmetto completed with result SUCCESS
op-build-pull-request » garrison completed with result SUCCESS
op-build-pull-request » p9dsu completed with result SUCCESS
op-build-pull-request » firestone completed with result SUCCESS
op-build-pull-request » zz completed with result SUCCESS
op-build-pull-request » openpower_mambo completed with result SUCCESS
op-build-pull-request » zaius completed with result SUCCESS
op-build-pull-request » barreleye completed with result SUCCESS
op-build-pull-request » firenze completed with result SUCCESS
op-build-pull-request » pseries completed with result SUCCESS
FATAL: channel is already closed
Command close created at
	at hudson.remoting.Command.<init>(Command.java:60)
	at hudson.remoting.Channel$CloseCommand.<init>(Channel.java:1132)
	at hudson.remoting.Channel$CloseCommand.<init>(Channel.java:1130)
	at hudson.remoting.Channel.close(Channel.java:1290)
	at hudson.remoting.Channel.close(Channel.java:1272)
	at hudson.remoting.Channel$CloseCommand.execute(Channel.java:1137)
Caused: hudson.remoting.Channel$OrderlyShutdown
	at hudson.remoting.Channel$CloseCommand.execute(Channel.java:1138)
	at hudson.remoting.Channel$1.handle(Channel.java:535)
	at hudson.remoting.SynchronousCommandTransport$ReaderThread.run(SynchronousCommandTransport.java:83)
Caused: hudson.remoting.ChannelClosedException: channel is already closed
	at hudson.remoting.Channel.send(Channel.java:613)
	at hudson.remoting.Request.call(Request.java:130)
	at hudson.remoting.Channel.call(Channel.java:838)
	at hudson.Launcher$RemoteLauncher.kill(Launcher.java:1079)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:496)
	at hudson.model.Run.execute(Run.java:1735)
	at hudson.matrix.MatrixBuild.run(MatrixBuild.java:313)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:415)

Deleting matrix project workspace... 
done

Setting status of d5155dc4b9607dc853cb999f0fd49f21b3c0a5d5 to FAILURE with url https://jenkins.ozlabs.ibm.com/job/op-build-pull-request/333/ and message: 'Build failed. See Jenkins console log for details.
 '
Using context: Build test
Finished: FAILURE
```
Jenkins fun?

**Comment by stewart-ibm** [comment]
Yeah, junkins "fun"

**Pull request merged**
