### PR TITLE
Petitboot: Bump to 1.10.4 and Bring-in upstream fixes

### PR DESCRIPTION
**Pull request by klauskiwi**
Bump Petitboot 1.10.3 to 1.10.4, Changes:
    Javier Martinez Canillas (2):
          discover/grub2: Allow using title for default even if id was defined
          discover/grub2: Allow to separate the --id argument using a space char

    Samuel Mendoza-Jonas (6):
          Various fixups and checks to make scan-build happy
          utils: Quote plugin name and vendor variables
          utils: Optionally run utilities as root
          Remove outdated TODO file
          doc: Start writing some in-tree documentation
          travis: Publish sphinx docs to Github pages

Additionally, carry some upstream patches not yet available in a stable release:
    Jeremy Kerr (15):
          discover/grub2: 'search' set-variable defaults to root
          discover/grub2: Use getopt for `search` argument parsing
          discover/grub2: test for (ignored) --no-floppy argument
          discover/grub2: Add support for UUID and label for 'search' command
          discover/grub2: expose a struct for grub2 file references
          discover/grub2: Add parsing code for grub2 file specifiers
          discover/grub2: add support for grub2-style path specifiers in resources
          discover/grub2: Allow (device)/path references in general script usage
          discover/grub2: Add a reference from script to parser
          discover/grub2: expose internal parse function
          discover/grub2: make statements_execute non-static
          discover/grub2: implement 'source' command
          test/parser: Add test for recent RHCOS grub2 config
          test/parser: Add RHEL8 grub config test
          lib/pb-protocol: fix ordering of system info length calculation

    Maxim Polyakov (3):
          discover/platform-powerpc: add missing mbox block selector
          discover/platform-powerpc: limit mailbox response size
          discover/platform-powerpc: return the actual mailbox size

### CODE REVIEW

**Comment by oohal** [comment]
```
3044/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/build/petitboot-v1.10.4/missing: line 81: automake-1.16: command not found
WARNING: 'automake-1.16' is missing on your system.
         You should only need it if you modified 'Makefile.am' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'automake' program is part of the GNU Automake package:
         <https://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <https://www.gnu.org/software/autoconf>
         <https://www.gnu.org/software/m4/>
         <https://www.perl.org/>
Makefile:2709: recipe for target 'Makefile.in' failed
```

**Comment by hegdevasant** [comment]
This patch brings in quite a bit of changes to stable branch. This needs better explanation.

-Vasant

**Comment by klauskiwi** [comment]
> 
> 
> This patch brings in quite a bit of changes to stable branch. This needs better explanation.
> 
The changes are similar to what was pushed to stable branch 1.7.x in support of grub2 commands that were never being parsed. This prevents petitboot from trapping on RHEL8 and RHOSP installation, possibly others (as the previously unsupported grub2 commands were available for quite some time now).

**Comment by klauskiwi** [comment]
retest this please

**Comment by klauskiwi** [comment]
I was able to validate some of the changes are working on a Briggs system, by editing the grub.cfg file to
* search for a named GPT partition and attributing that partition to a "testpart" variable (testing the `search --label=test --set=testpart` syntax)
* testing for a file inside that partition using a (device)/path style
* sourcing an additional configuration file with "source", where I was simply adding another menuentry with additional text/commandline items identifying that the command worked.

**Pull request merged**
