### PR TITLE
Bump p9dsu-xml to 734a35ebe5af49dba57269ca26065d40b876c962

### PR DESCRIPTION
**Pull request by youhour**
734a35e - careyz@supermicro.com - 2019-04-05 - MEMD:VM keyword is not set in system vpd on P9DSU-C
e1a56eb - careyz@supermicro.com - 2019-03-28 - Checkstop in istep 14.1 (mss_memdiag) - dimm garded
218a77a - jimsmc - 2018-05-03 - Fix duplicate capps target

Change-Id: I3b7823193608a79ece806f2aa8c84422e68bebbe
Signed-off-by: Michael Y. Lim <youhour@us.ibm.com>

### CODE REVIEW

**Comment by dcrowell77** [comment]
Test only PR - do not merge yet

**Comment by youhour** [comment]
The p9dsu.pnor image that Dan pointed to me to (https://hostboot-jenkins.swg-devops.com/job/Hostboot/job/OpenPower/job/GHPR/job/build-multi/2809/CONFIG=p9dsu,OS=op-build-ci-rhel7/) is installed into bstnbmc010 and boot to OS fine.

**Comment by stewartsmith** [comment]
Does op-test look good though?

A machine booting isn’t a high bar.

**Comment by youhour** [comment]
> 
> Does op-test look good though? A machine booting isn’t a high bar.
> […](#)
> Sent from my iPhone
> On 31 Oct 2019, at 15:36, Michael Lim ***@***.***> wrote: ﻿ The p9dsu.pnor image that Dan pointed to me to (https://hostboot-jenkins.swg-devops.com/job/Hostboot/job/OpenPower/job/GHPR/job/build-multi/2809/CONFIG=p9dsu,OS=op-build-ci-rhel7/) is installed into bstnbmc010 and boot to OS fine. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Have not run op-test.  Do you have a link to procedure how to setup and run the test?

**Comment by dcrowell77** [comment]
Michael - op-test only runs against the systems we have in our pool, which currently does not include a Boston.   Since you are (basically) the lead for Boston FW deliverables, I'll leave it to you to decide if this change has gone through enough verification or not.

**Comment by stewartsmith** [comment]
Check out the github project and the documentation for it. We managed to get it pretty good in explaining how to get started running things

**Comment by klauskiwi** [comment]
Trying to do a bit of a cleanup on PRs here.. is this still relevant? If that's the case, please re-base to the latest, post test results etc

**Pull request closed without merging**
