### PR TITLE
Adding MEMD header to new pnor section - NO MERGE

### PR DESCRIPTION
**Pull request by e-liner**
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1241)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch for testing?

**Comment by e-liner** [comment]
This is the current update of the MEMD story for op-build.  It adds in the header in the pnor and the needed makefile changes in op-build.   This is still a work in progress.

**Comment by stewart-ibm** [comment]
e-liner <notifications@github.com> writes:
> This is the current update of the MEMD story for op-build.  It adds in
> the header in the pnor and the needed makefile changes in op-build.
> This is still a work in progress.

what is MEMD? What story? What is a story in this context, I don't see
them on github anywhere.


-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by dcrowell77** [comment]
We don't use github for project planning so nothing is on github.  The response is just saying this isn't meant to be merged yet (I think).  I think a PR was just needed to test some stuff out.

MEMD is currently a VPD record that contains Memory configuration Data.  The data is being moved into a PNOR partition on some systems.

**Comment by stewart-ibm** [comment]
Dan <notifications@github.com> writes:
> We don't use github for project planning so nothing is on github.  The response is just saying this isn't meant to be merged yet (I think).  I think a PR was just needed to test some stuff out.
>
> MEMD is currently a VPD record that contains Memory configuration
> Data.  The data is being moved into a PNOR partition on some systems.

How much fuzz testing and unit testing has the parser for it had?

With the explosion of random bits of pnor data read by hostboot, this is
a serious security concern for bypassing secure boot.

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by dcrowell77** [comment]
This section will get signed once that is all in place.  You could consider this data equivalent to stuff we have in the MRW now.

**Comment by stewart-ibm** [comment]
Dan <notifications@github.com> writes:
> This section will get signed once that is all in place.  You could
> consider this data equivalent to stuff we have in the MRW now.

Cool, thanks for clarifying.

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by scprek** [comment]
retest this please

**Comment by sameerveer** [comment]
retest this please

**Pull request closed without merging**
