### PR TITLE
Bump up HB, adjust OCC patches and fix HDAT I2C

### PR DESCRIPTION
**Pull request by sannerd**
- Latest HB has first in chain of WOF fixes
  - Existing patches to make OCC run fail to apply
  - Recent HDAT I2C commit only works on Witherspoon, so
    Add patch to allow other platforms to pass

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1214)

### CODE REVIEW

**Comment by bofferdn** [comment]
looks good to me

**Comment by bofferdn** [comment]
testing failing P9 witherspoon due to #V slope error or something

**Comment by sannerd** [comment]
retest please

**Comment by sannerd** [comment]
Manual test on wsbmc017 failed with: 

[   69.265740560,3] I2C: HDAT device array has no version! Assuming v1                   
[   69.265874082,3] DT: dt_attach_root failed, duplicate eeprom@50                       
[   69.265922420,3] ***********************************************                      
[   69.265957751,3] Unexpected exception 200 !                                           
[   69.265981239,3] SRR0 : 0000000030096be8 SRR1 : 9000000000201000                      
[   69.266020039,3] HSRR0: 0000000000000180 HSRR1: 9000000000001000        

@bofferdn -- this is back to the I2C stuff that got added.  Looks like we will have to revert it to get going :(

**Comment by sannerd** [comment]
Fixed via https://github.com/open-power/op-build/pull/1218.  Closing

**Pull request closed without merging**
