### PR TITLE
Add support for IMA-CATALOG package

### PR DESCRIPTION
**Pull request by ploetzma**
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/825)

### CODE REVIEW

**Comment by williamspatrick** [comment]
Need Zaius updated.

**Comment by ploetzma** [comment]
Zaius defconfig has been updated.

**Comment by e-liner** [comment]
@williamspatrick Could you take a look at this?  op-build pull requests will continue to fail until it's merged.

**Comment by rlippert** [comment]
FYI it looks like this is breaking builds for me since there is no build time dependency between openpower-pnor and ima-catalog packages, so the openpower-pnor build complains it can't find the ima-catalog.bin file.  I think OPENPOWER_PNOR_DEPENDENCIES needs to be updated to add ima-catalog package as (optional) dependency?

**Comment by stewart-ibm** [comment]
Thanks to https://github.com/open-power/op-build/issues/803 I have issues building any P9 system on machines I have readily available, so debugging may be slower.

@ploetzma are you able to jump in here?

**Comment by ploetzma** [comment]
I have helped @wghoffa through this issue, I believe you are describing it correctly. I will update the dependencies to include ima-catalog.

**Pull request merged**
