### PR TITLE
Revert witherspoon linux kernel version back to 4.8

### PR DESCRIPTION
**Pull request by ploetzma**
Management has asked me to make a pull request to move this back to 4.8 so it is no longer blocking build team.

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/736)

### CODE REVIEW

**Comment by ravimed1** [comment]
@stewart-ibm can you please review  / merge ? This is blocking builds.

**Comment by stewart-ibm** [comment]
What's the build failure?

**Comment by williamspatrick** [comment]
Issue 730

**Comment by shenki** [comment]
Nak. Lets fix the filesize issue instead.

**Comment by stewart-ibm** [comment]
As mentioned on #730 , I get 15661480 for a witherspoon_defconfig with gcc6 (a whole 67160 of free space there).

**Comment by stewart-ibm** [comment]
With XZ compression of kernel: 14665992, a saving of 995,488 bytes.

So, the better approach is to set BR2_LINUX_KERNEL_XZ=y in witherspoon_defconfig (as XZ is supported on ppc in 4.9)

**Comment by stewart-ibm** [comment]
I'll close this pull req, and put up one that does just that for Witherspoon.

**Pull request closed without merging**
