### PR TITLE
[package/occ] Update to the latest commit SHA

### PR DESCRIPTION
**Pull request by runlevel5**
## Changes

* [occ] Point to the latest commit
* [buildroot] Bump to 2022.02-op-build
* [defconfig] Use GCC9
* [loadkeys] Bump to 2.5.1

## Why

To address compilation issue with GCC9 or newer.

## Related PR

https://github.com/open-power/occ/pull/32

### CODE REVIEW

**Comment by runlevel5** [comment]
@IlyaSmirnov91 the PR is ready for review. Great thanks

**Comment by IlyaSmirnov91** [comment]
ok to test

**Comment by runlevel5** [comment]
@IlyaSmirnov91 what is the error with the RHEL7 please?

**Comment by IlyaSmirnov91** [comment]
@runlevel5 , it looks like the failure is consistent:

/tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-multi-4500/CONFIG/zz/OS/redhat-8/build/op-build/output/host/lib/gcc/powerpc64le-buildroot-linux-gnu/10.3.0/../../../../powerpc64le-buildroot-linux-gnu/bin/ld: libfont.a(kdmapop.o):(.bss+0x0): multiple definition of `progname'; mapscrn-mapscrn.o:(.bss+0x8): first defined here
/tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-multi-4500/CONFIG/zz/OS/redhat-8/build/op-build/output/host/lib/gcc/powerpc64le-buildroot-linux-gnu/10.3.0/../../../../powerpc64le-buildroot-linux-gnu/bin/ld: libfont.a(kdmapop.o):(.bss+0x0): multiple definition of `progname'; showconsolefont.o:(.bss+0x220): first defined here
/tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-multi-4500/CONFIG/zz/OS/redhat-8/build/op-build/output/host/lib/gcc/powerpc64le-buildroot-linux-gnu/10.3.0/../../../../powerpc64le-buildroot-linux-gnu/bin/ld: libfont.a(kdfontop.o):(.bss+0x0): multiple definition of `progname'; showconsolefont.o:(.bss+0x220): first defined here
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:707: mapscrn] Error 1
make[5]: *** Waiting for unfinished jobs....
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:749: showconsolefont] Error 1
/tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-multi-4500/CONFIG/zz/OS/redhat-8/build/op-build/output/host/lib/gcc/powerpc64le-buildroot-linux-gnu/10.3.0/../../../../powerpc64le-buildroot-linux-gnu/bin/ld: libfont.a(kdmapop.o):(.bss+0x0): multiple definition of `progname'; loadunimap-loadunimap.o:(.bss+0x0): first defined here
/tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-multi-4500/CONFIG/zz/OS/redhat-8/build/op-build/output/host/lib/gcc/powerpc64le-buildroot-linux-gnu/10.3.0/../../../../powerpc64le-buildroot-linux-gnu/bin/ld: libfont.a(kdmapop.o):(.bss+0x0): multiple definition of `progname'; setfont.o:(.bss+0x8): first defined here
/tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-multi-4500/CONFIG/zz/OS/redhat-8/build/op-build/output/host/lib/gcc/powerpc64le-buildroot-linux-gnu/10.3.0/../../../../powerpc64le-buildroot-linux-gnu/bin/ld: libfont.a(kdfontop.o):(.bss+0x0): multiple definition of `progname'; setfont.o:(.bss+0x8): first defined here
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:704: loadunimap] Error 1
collect2: error: ld returned 1 exit status
make[5]: *** [Makefile:725: setfont] Error 1
make[4]: *** [Makefile:903: all-recursive] Error 1
make[3]: *** [Makefile:364: all-recursive] Error 1
make[2]: *** [Makefile:295: all] Error 2
make[1]: *** [package/pkg-generic.mk:292: /tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-multi-4500/CONFIG/zz/OS/redhat-8/build/op-build/output/build/loadkeys-2.0.3/.stamp_built] Error 2
make: *** [Makefile:84: _all] Error 2
make: Leaving directory '/tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-multi-4500/CONFIG/zz/OS/redhat-8/build/op-build/buildroot'

This happens when we try to build the ZZ configuration. Maybe that needs to be updated too?
https://github.com/open-power/op-build/blob/master/openpower/configs/zz_defconfig

**Comment by runlevel5** [comment]
The `zz` build error has reference to GCC 10.3.0. In theory we should use the same GCC 9 like others. I do not believe changing to GCC 9 would fix the issue because it was working fine with native build on ppc64le, perhaps it is some other issues that are related to cross compilation

**Comment by runlevel5** [comment]
@IlyaSmirnov91 what's the error output of `IBM OP CI HW IPL test -- p9 `?

**Comment by runlevel5** [comment]
> gnu/10.3.0/../../../../powerpc64le-buildroot-linux-gnu/bin/ld: libfont.a(kdmapop.o):(.bss+0x0): multiple definition of progname'; setfont.o:(.bss+0x8): first defined here /tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-multi-4500/CONFIG/zz/OS/redhat-8/build/op-build/output/host/lib/gcc/powerpc64le-buildroot-linux-gnu/10.3.0/../../../../powerpc64le-buildroot-linux-gnu/bin/ld: libfont.a(kdfontop.o):(.bss+0x0): multiple definition of progname'; setfont.o:(.bss+0x8): first

FYI I can re-produce this issue reliably with GCC 10. TL;DR; this is yet another breaking behaviour of GCC10 and we could ignore multi-define in C code by setting `-fcommon`.

I don't think we would have to worry about this issue because we do not get the same issue with buildroot 2023.02

**Comment by runlevel5** [comment]
@IlyaSmirnov91 Would you be able to send me the full log of the `IBM OP CI HW IPL test -- p9` build? Many thanks

**Comment by IlyaSmirnov91** [comment]
> @IlyaSmirnov91 Would you be able to send me the full log of the `IBM OP CI HW IPL test -- p9` build? Many thanks

Just needed a retrigger. Looks good now!

**Pull request merged**
