### PR TITLE
Release 4.4.27-openpower1

### PR DESCRIPTION
**Pull request by shenki**
Signed-off-by: Joel Stanley <joel@jms.id.au>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/704)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
```
>>> linux 4.4.27 Downloading
--2016-10-24 22:54:20--  https://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.4.27.tar.xz
Resolving cdn.kernel.org... 151.101.20.69
Connecting to cdn.kernel.org|151.101.20.69|:443... connected.
ERROR: certificate common name “k.ssl.fastly.net” doesn’t match requested host name “cdn.kernel.org”.
To connect to cdn.kernel.org insecurely, use ‘--no-check-certificate’.
--2016-10-24 22:54:20--  http://sources.buildroot.net/linux-4.4.27.tar.xz
Resolving sources.buildroot.net... 176.9.16.109
Connecting to sources.buildroot.net|176.9.16.109|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-10-24 22:54:21 ERROR 404: Not Found.
```

*sigh*

@jazurin can you fix this?

**Comment by e-liner** [comment]
retest this please

**Comment by e-liner** [comment]
retest this please

**Comment by stewart-ibm** [comment]
@op-jenkins @jazurin @e-liner At some point we're going to have to make a call on this, if we can't have reliable CI hosted there, then it should be hosted elsewhere.

**Pull request merged**
