### PR TITLE
romulus: Enable BR2_BUILD_PNOR_SQUASHFS

### PR DESCRIPTION
**Pull request by mine260309**
Romulus OpenBMC is going to support Virtual PNOR, and it requires
squashfs tarball for PNOR code update.

Enable BR2_BUILD_PNOR_SQUASHFS to make Romulus build to generate
squashfs.tar which could be used by OpenBMC.

Tested: Do romulus build and see romulus.pnor.squashfs.tar is generated
        and could be used for OpenBMC to do PNOR code update.

Signed-off-by: Lei YU <mine260309@gmail.com>

### CODE REVIEW

**Comment by stewart-ibm** [comment]
ok to test

**Comment by shenki** [comment]
Please do not merge.

**Comment by shenki** [comment]
@mine260309 I think we can close this now

**Comment by mine260309** [comment]
@shenki Yup, closed.

**Pull request closed without merging**
