### PR TITLE
Adding patch to revert Removed-pdwn-settings

### PR DESCRIPTION
**Pull request by cvswen**

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch for testing?

**Comment by stewart-ibm** [comment]
Your commit is missing your Signed-Off-by as required by the Developer Certificate of Origin section of https://github.com/open-power/op-build/blob/master/CONTRIBUTING.md.

Please "git commit --amend -s && git push -f" so we can accept the patch.

This also seems to be a duplicate of https://github.com/open-power/op-build/pull/1789 ?

**Comment by cvswen** [comment]
Added Signed-Off-by to commit

**Comment by stewart-ibm** [comment]
retest this please

**Pull request merged**
