### PR TITLE
Bump up HB w/ fixes for AVS bus and I2C XML

### PR DESCRIPTION
**Pull request by sannerd**
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1222)

### CODE REVIEW

**Comment by bofferdn** [comment]
Looks ok to me .. waiting for auto tests

**Comment by bofferdn** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/op-build/1222)*

**Comment by bofferdn** [comment]
retriggered HW test due to aes reserve failure

**Comment by pragupta** [comment]
System restarted in the middle of the job. So, just re-triggered the HW CI part of it here: http://gfw160.aus.stglabs.ibm.com:8088/jenkins/job/OP_HW_CI_gerrit_trigger_p9/584/

**Pull request merged**
