### PR TITLE
Removing temporary Process I2C patch and updating xmls

### PR DESCRIPTION
**Pull request by e-liner**
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1072)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
e-liner <notifications@github.com> writes:
>   * Removing temporary Process I2C patch and updating xmls

This commit message isn't terribly informative as to why any of this is
being done.

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by e-liner** [comment]
retest this please

**Comment by e-liner** [comment]
retest this please

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
