### PR TITLE
Create 'custom' subdirectory.

### PR DESCRIPTION
**Pull request by williamspatrick**
This directory is a place for users to add custom packages
    and patches outside of the rest of the openpower package
    tree.  This allows them to more easily maintain a fork of
    op-build and enhance it with their own packages.

### CODE REVIEW

**Comment by dcrowell77** [comment]
Seems like a good idea to me.

**Comment by geissonator** [comment]
@williamspatrick , can you provide an example of how we'd use this?  Should we wait for the phase 4 tag before merging or low risk?

**Comment by williamspatrick** [comment]
Added README file.

**Comment by williamspatrick** [comment]
Merged to master-next.

**Pull request closed without merging**
