### PR TITLE
Buildroot 2016.11

### PR DESCRIPTION
**Pull request by shenki**
Move op-build to the latest upstream release of Buildroot:

 https://git.buildroot.net/buildroot/plain/CHANGES?id=2016.11

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/766)

### CODE REVIEW

**Comment by shenki** [comment]
Do not merge; testing new buildroot.

**Comment by shenki** [comment]
Boot tested on Firestone.

I think this is good to go!

**Comment by stewart-ibm** [comment]
Joel Stanley <notifications@github.com> writes:
>  * Regenerate defconfigs
>   * The GCC 5 series becomes the default, so we need to explicitly
>     select GCC 4.9 for Witherspoon. All GCC 6 platforms are okay.

Or, we force them to fix their code :)

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by williamspatrick** [comment]
I'd like to hold this off until we split for the next major release. I think we are waiting for Witherspoon updates on that.

**Comment by stewart-ibm** [comment]
Patrick Williams <notifications@github.com> writes:
> I'd like to hold this off until we split for the next major release. I
> think we are waiting for Witherspoon updates on that.

For 1.14 would be good.

I had thought that we were good to go for tagging 1.13, maybe it got
lost in the list of things for that other GA :)

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by shenki** [comment]
Ping? This has been sitting here for 19 days now

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
(my aim is to merge this immediately after 1.13 is tagged, which should be tomorrow)

**Comment by stewart-ibm** [comment]
Seeing as master-next has moved to master for 1.13, should be good to merge now.

**Pull request merged**
