### PR TITLE
Change op-build to use build script from public directory.

### PR DESCRIPTION
**Pull request by sandeepkumaryadaw**
JIRA: PFSBE-854
STGD: 613141

### CODE REVIEW

**Review by akhis023 — APPROVED** [review]

**Comment by skumar8j** [comment]
Code look goods.

**Comment by dcrowell77** [comment]
test this please

**Review by dcrowell77 — APPROVED** [review]
Looks fine, just waiting for CI

**Comment by dcrowell77** [comment]
CI fail looks like one of the known glitches with disappearing directories.  I'll retrigger it.

/bin/sh: ./public/src/test/framework/build-script: No such file or directory

**Comment by dcrowell77** [comment]
Failed again, maybe this is actually related to the change

sed -i 's/--user//g' /tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-p10-public-github-500/CONFIG/p10ebmc/OS/redhat-8/build/op-build/output/build/sbe-odyssey-2d6c892a123f9c49d395af4cdff45b377fb2c801/public/src/tools/utils/sbe/sbe-workon-utils
/tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-p10-public-github-500/CONFIG/p10ebmc/OS/redhat-8/build/op-build/output/host/bin/python3 -m venv /tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-p10-public-github-500/CONFIG/p10ebmc/OS/redhat-8/build/op-build/output/build/sbe-odyssey-2d6c892a123f9c49d395af4cdff45b377fb2c801/.venv --prompt="SBE"
cd /tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-p10-public-github-500/CONFIG/p10ebmc/OS/redhat-8/build/op-build/output/build/sbe-odyssey-2d6c892a123f9c49d395af4cdff45b377fb2c801 && ./public/src/test/framework/build-script odyssey pnor --skip-tests
/bin/sh: ./public/src/test/framework/build-script: No such file or directory

**Comment by sandeepkumaryadaw** [comment]
Yeah tested , and sync with latest driver , can you please retrigger the CI ?

**Comment by dcrowell77** [comment]
retest this please

**Comment by sandeepkumaryadaw** [comment]
If CI is passed , can this commit get merged ?

**Comment by sandeepkumaryadaw** [comment]
synced with latest driver where resolved last CI failure   so can you please retrigger the CI ?

**Pull request merged**
