### PR TITLE
Add files for mihawk platform

### PR DESCRIPTION
**Pull request by chcyjoy**
Signed-off-by: Joy Chu <joy_chu@wistron.com>

### CODE REVIEW

**Comment by chcyjoy** [comment]
1. mbox config following zaius/witherspoon 
2. occ pull requested but would like merge first 
3. will support vpnor as witherspoon

**Comment by chcyjoy** [comment]
@stewartsmith would you please help us review these files?

**Comment by chcyjoy** [comment]
@stewartsmith Due to our tight schedule, we need to upstream mihawk to ibm op930 branch before 8/5. Could we speed up the review?

**Comment by oohal** [comment]
@amboar @shenki can one of you help out with this?

**Comment by stewartsmith** [comment]
I can't speak for OP930, but this should be good to go for master.

**Comment by dcrowell77** [comment]
Submit the PR over to https://github.com/ibm-op-release/op-build/tree/release-op930 if you need it in op930

**Pull request merged**
