### PR TITLE
Patch for istep5 performance

### PR DESCRIPTION
**Pull request by sgupta2m**
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1023)

### CODE REVIEW

**Comment by sannerd** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/op-build/1023#-:-KhgVteSjIrmFJbqXrko:bnfp4nl)*

**Comment by sgupta2m** [comment]
retest this please

**Comment by wghoffa** [comment]
@pragupta - How do we get @sgupta2m and team on the list to be able to retrigger themselves?

**Comment by pragupta** [comment]
I added @sgupta2m. Anyone else who needs to be added can give me their github id.

**Comment by wghoffa** [comment]
http://gfw160.aus.stglabs.ibm.com:8088/jenkins/job/OP_HW_test_multi_p9/237/ - Which was a retrigger of "GitHub pull request #1023 of commit 1a4b59c2cb751889abd342c51a435c70269a870c, no merge conflicts." shows good results. The previous fails were related to a Linux Distro problem on the Zaius box, and the new Witherspoon in the pool that did not have a network setup so the test would never successfully ping the OS and deemed it a failure. With both issues resolved the test passes. This should be good to merge.

**Pull request merged**
