### PR TITLE
skiboot v6.6-111-gd362ae4f4

### PR DESCRIPTION
**Pull request by opalci**
Benjamin Herrenschmidt (7):
      xive: Set the fused core mode properly
      chip: Fix pir_to_thread_id for fused cores
      cpu: Keep track of the "ec_primary" in big core more
      direct-ctl: Use the EC primary for special wakeups
      slw: Limit fused cores P9 to STOP0/1/2
      cpu: Make cpu_get_core_index() return the fused core number
      imc: Use pir_to_core_id() rather than cpu_get_core_index()

Cédric Le Goater (1):
      xive/p9: Enforce thread enablement before TIMA accesses

Dan Horák (1):
      external/ffspart: define $(sbindir) for Makefile

Gustavo Romero (3):
      xive: Fix typos in comments
      Update comments for bit manipulation macros
      Fix typos in comment

Joel Stanley (1):
      doc: Document more platforms

Jordan Niethe (1):
      external/mambo: Do not enable TM on P9 in ibm, pa-features

Klaus Heinrich Kiwi (1):
      hdata: Add new "smp-cable-connector" VPD keyword

Oliver O'Halloran (5):
      hdata: Ensure the prd-label hbrt-code-image is prefixed
      hw/psi-p9: Configure IRQ offset before XIVE notify
      hw/phb4: Actually enable error reporting
      hw/phb4: Verify AER support before initialising AER regs
      stack: only print stack usage backtraces when we hit a new watermark

Ryan Grimm (1):
      Add basic P9 fused core support

Vaidyanathan Srinivasan (3):
      Add POWER9 Cumulus processor PVR type
      Add POWER9 Fleetwood platform support
      Enable fused core mode support in OPAL

Vasant Hegde (2):
      fsp/dump: Handle non-MPIPL scenario
      skiboot v6.6.3 release notes

Signed-off-by: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by hegdevasant** [comment]
retest this please

**Comment by klauskiwi** [comment]
@hegdevasant @oohal so looks like we're hitting a fast-reset failure: https://hostboot-jenkins.swg-devops.com/job/Hostboot/job/OpenPower/job/HW/job/p9-test-param/3958/artifact/op-test/test-reports/skiroot_test_suite_report/latest/skiroot.log/*view*/

Skiboot 6.6 changed how we force fast-reset to `nvram -p ibm,skiboot --update-config force-fast-reset=1` instead of what op-test has been using (`fast-reset=feeling-lucky`) and, although I couldn't find in any logs, I wonder if someone is calling `disable_fast_reboot()` in this particular run..

We should talk about this. Should we still expect op-test to force-fast-reset and expect successful results? What do we want the fast reset testcase to really do?

**Comment by klauskiwi** [comment]
retest this please

**Comment by klauskiwi** [comment]
made obsolete by https://github.com/open-power/op-build/pull/3865

**Pull request closed without merging**
