### PR TITLE
Remove obus powerdown revert patch

### PR DESCRIPTION
**Pull request by dcrowell77**
Changes have been made to the SBE and OS code to handle the
issues exposed by the original change.

Signed-off-by: Dan Crowell <dcrowell@us.ibm.com>

### CODE REVIEW

**Comment by dcrowell77** [comment]
I fixed the DCO.  The OP CI job is a victim of unrelated issues...

**Comment by cvswen** [comment]
retest this please

**Comment by cvswen** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by dcrowell77** [comment]
Any idea what is still failing here?  Can we re-kick it @cvswen ?

**Comment by cvswen** [comment]
Will try again.  There was a lot of churn in CI over the last week.

**Comment by cvswen** [comment]
retest this please

**Comment by stewart-ibm** [comment]
Fixed up the signed-off-by and merged as of 15866229b3a05f437b055c80aa66810dd9bae169 (but seeing as I modified the commit I have to close htis rather than have it marked as merged).

**Pull request closed without merging**
