### PR TITLE
kernel: Move to Linux v4.15.14-openpower1

### PR DESCRIPTION
**Pull request by shenki**
Adds a fix for a race when EEH devices are unbound, which was seen with
the NVMe driver.

Signed-off-by: Joel Stanley <joel@jms.id.au>

### CODE REVIEW

**Comment by stewart-ibm** [comment]
```Applying 0003-Release-OpenPower-kernel.patch using patch: 
patching file Makefile
Hunk #1 FAILED at 2.
1 out of 1 hunk FAILED -- saving rejects to file Makefile.rej
make[1]: *** [/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/garrison/OS/rhel6.4/build/op-build/output/build/linux-4.15.14/.stamp_patched] Error 1
make: *** [_all] Error 2
make: Leaving directory `/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/garrison/OS/rhel6.4/build/op-build/buildroot'```

**Comment by stewart-ibm** [comment]
retest this please

**Comment by shenki** [comment]
There was a stray patch in the tree that shouldn't have been there which was causing the build failure. It should be resolved now.

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
After bashing CI with a hammer and swearing a *lot* (and nearly just deleting jobs from jenkins because everything is terrible) I finally got a p9 witherspoon system to run the test, so this does actually pass.

Merging.

**Pull request merged**
