### PR TITLE
op-build update 06/13/2017

### PR DESCRIPTION
**Pull request by wghoffa**
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1146)

### CODE REVIEW

**Comment by wghoffa** [comment]
retest this please

**Comment by wghoffa** [comment]
retest this please

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch?

**Comment by wghoffa** [comment]
Newer content merged here: https://github.com/open-power/op-build/pull/1151

**Pull request closed without merging**
