### PR TITLE
Add BR2_SKIBOOT_DEVICETREE

### PR DESCRIPTION
**Pull request by rarbab**
Skiboot can build device trees now. Let's deliver them in a freshened simulator-friendly defconfig.

### CODE REVIEW

**Comment by stewart-ibm** [comment]
ok to test

**Comment by rarbab** [comment]
Note that this pull causes a failed CI check of CONFIG=openpower_mambo, because it actually changes the name of that config.

That will need to be addressed in the CI if/when this gets merged.

**Comment by shenki** [comment]
retest this please

**Comment by rarbab** [comment]
> We could just make building the dtb the default. If you agree, I suggest we do that in a future patch.

I don't really have a preference, but it seems like users of this new opal_defconfig would be the only ones who actually need device trees.

Also, looks like I've got a merge conflict now because BR2_LINUX_KERNEL_CUSTOM_VERSION_VALUE has been updated upstream. Should I fix that or can it be handled at merge?

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Pull request merged**
