### PR TITLE
Update README.md for Fedora 31 build-deps

### PR DESCRIPTION
**Pull request by stewartsmith**
Signed-off-by: Stewart Smith <stewart@flamingspork.com>

### CODE REVIEW

**Comment by dcrowell77** [comment]
retest this please

**Comment by oohal** [comment]
retest this please

**Comment by sharkcz** [comment]
Could you also change perl-bignum to "perl(bigint)", so all perl modules are called the same way?

**Comment by stewartsmith** [comment]
> Could you also change perl-bignum to "perl(bigint)", so all perl modules are called the same way?

Done.

**Comment by sharkcz** [comment]
LGTM

**Pull request merged**
