### PR TITLE
update romulus xml to latest commit

### PR DESCRIPTION
**Pull request by jackydalong**

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch for testing?

**Comment by wghoffa** [comment]
ok to test

**Comment by MengzeLiao** [comment]
retest this please

**Comment by MengzeLiao** [comment]
retest this please

**Comment by stewart-ibm** [comment]
Does this duplicate what's in https://github.com/open-power/op-build/pull/1826 ?

Your commit also seems to be missing your Signed-Off-by as required by the Developer Certificate of Origin in https://github.com/open-power/op-build/blob/master/CONTRIBUTING.md - please fix this so we can merge.

**Comment by jackydalong** [comment]
Yes, this is a duplicate of #1826 . You can close this.
And I've fixed the missing Signed-off-by issue.
Thanks

**Pull request merged**
