### PR TITLE
Update romulus mrw for removing nvbus and memory throttle/utilization

### PR DESCRIPTION
**Pull request by MengzeLiao**
1) remove nvbus target instance
2) adjust memory throttle and utilization according memory team

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1425)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch for testing?

**Comment by MengzeLiao** [comment]
retest please

**Comment by MengzeLiao** [comment]
retest this please

**Comment by MengzeLiao** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by MengzeLiao** [comment]
retest this please

**Comment by wghoffa** [comment]
retest this please

**Pull request closed without merging**
