### PR TITLE
openpower: pnor: Generate tarball

### PR DESCRIPTION
**Pull request by mine260309**
A tarball containing PNOR and MANIFEST is used to do code update for
OpenBMC.
This was done for VPNOR, and now it is needed for static layout PNOR.

* Rename openpower-vpnor to openpower-pnor-util and rename the installed
script to `generate-tar`.
* Invoke generate-tar to generate tarball for both static and VPNOR.

Signed-off-by: Lei YU <mine260309@gmail.com>

### CODE REVIEW

**Comment by stewart-ibm** [comment]
ok to test

**Comment by shenki** [comment]
Retest this please

**Comment by shenki** [comment]
Retest this please

**Comment by stewart-ibm** [comment]
```
+ cp -Rp '/esw/phbci/opbuild/dl/*' /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/firestone/OS/op-build-ci-rhel7/build/op-build/dl/
cp: cannot stat ‘/esw/phbci/opbuild/dl/*’: No such file or directory
```

Austin CI is busted.

**Comment by stewart-ibm** [comment]
Succeeded previously in CI, so assuming okay and merging.

**Pull request merged**
