### PR TITLE
POWER9 defconfigs: apply linux kernel patches

### PR DESCRIPTION
**Pull request by stewart-ibm**
We initially disabled applying the patches on P9 platforms due to running
a more recent kernel on P9 than P8 configs (and it being early bringup).

Fixes: bca805249d4191a113731e872978038434db2987
Fixes: 1a78268ee5f55282614cc27b290f140b0a7ce9b7
Fixes: 268ed580914e96b543769b7de221d7c528989198
Fixes: 4ea0cf4bd6e90f87cdcab2fb29d0302eba825174
Fixes: https://github.com/open-power/op-build/issues/956
Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/957)

### CODE REVIEW

**Comment by wghoffa** [comment]
LGTM

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/op-build/957#-:-Kfrw8bPrf6cUqVkad2f:bb6ywmx)*

**Comment by williamspatrick** [comment]
Something doesn't jive with the commit message here. Does it mean we didn't use to apply them and now we do?  It feels like the body is missing one sentence.

**Comment by stewart-ibm** [comment]
Fair comment. Commit message updated. No other change

**Comment by williamspatrick** [comment]
:+1:

**Pull request merged**
