### PR TITLE
Reverting hostboot to a level that works with witherspoon pnor

### PR DESCRIPTION
**Pull request by pragupta**
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/759)

### CODE REVIEW

**Comment by e-liner** [comment]
ok to test

**Comment by e-liner** [comment]
ok to test

**Comment by williamspatrick** [comment]
What is the plan to get this fixed?  We have tools that automatically update this so we should either turn those off for master or fix this.

**Comment by pragupta** [comment]
I have been actively working on trying to get this fixed. I should have something very soon. I thought we had disabled updates, but I guess we only disabled witherspoon ci. 
 
Prachi GuptaPower Firmware Development (IBM Austin)pragupta@us.ibm.com512-286-9703 (Tie4line: 363-9703)
 
 
----- Original message -----From: Patrick Williams <notifications@github.com>To: open-power/op-build <op-build@noreply.github.com>Cc: Prachi Gupta/Austin/IBM@IBMUS, Author <author@noreply.github.com>Subject: Re: [open-power/op-build] Reverting hostboot to a level that works with witherspoon pnor (#759)Date: Tue, Nov 22, 2016 10:42 AM 
What is the plan to get this fixed? We have tools that automatically update this so we should either turn those off for master or fix this.

**Comment by williamspatrick** [comment]
@e-liner - If we merge this can we then re-enable CI and prevent future merges from reverting this again?

**Pull request merged**
