### PR TITLE
skiboot v6.5-27-g1785745d

### PR DESCRIPTION
**Pull request by opalci**
Madhavan Srinivasan (1):
      hdat/spira: export abc and wxyz bus speeds

Nicholas Piggin (6):
      core/cpu.c: current_radix_mode should be initialised to true
      build: use -mcpu=power8
      core/exceptions.c: rearrange code to allow more interrupt types
      core/util: trap based assertions
      core/util: branch-to-NULL assert for ELFv2 ABI
      core/exceptions.c: do not include handler code in exception backtrace

Oliver O'Halloran (1):
      core/platform: Actually disable fast-reboot on P8

### CODE REVIEW

**Comment by hegdevasant** [comment]
Just to clarify, I'm using `opalci` github ID to send skiboot PRs.  So this is valid PR.

-Vasant

**Comment by oohal** [comment]
test this please

**Comment by oohal** [comment]
retest this please

**Comment by oohal** [comment]
ok to test

**Comment by hegdevasant** [comment]
Commit message in this PR was not proper. Also looks like updating subject line didn't trigger CI jobs. 
Will send new PR.

-Vasant

**Pull request closed without merging**
