### PR TITLE
linux: Disable CAPI support

### PR DESCRIPTION
**Pull request by sammj**
Support for the CAPI (CXL) driver in Skiroot is unnecessary and
potentially harmful as CAPI does not support being used over a kexec,
which could result in CAPI devices being unavailable in the host.

Signed-off-by: Samuel Mendoza-Jonas <sam@mendozajonas.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/452)

### CODE REVIEW

**Comment by oohal** [comment]
Please do not merge this. I am planning on using the CAPI gzip accelerator card to enhance the boot wrapper decompresser.

**Comment by mikey** [comment]
@oohal

**Comment by williamspatrick** [comment]
Can I assume this was a joke?

Patrick

**Comment by sammj** [comment]
My commit is legitimate; I think everyone else used this as an opportunity to test a few Github features :)

**Comment by stewart-ibm** [comment]
Makes sense (well, not the damage we've done to @oohal due to working on the kernel wrapper).

**Pull request merged**
