### PR TITLE
Firestone makefiles

### PR DESCRIPTION
**Pull request by ploetzma**

### CODE REVIEW

**Comment by ploetzma** [comment]
Added actual serverwiz2 processing of firestone.xml

**Comment by ploetzma** [comment]
This is dependent on  Hostboot commit 84a672bd28630d9998fc2808df3659ddcf5a7eda (IPMI Fru Updates) going into op-build. Andrew is working on merging that. As soon as that is in, these can be merged.

**Comment by ploetzma** [comment]
@williamspatrick This can be merged, now that 84a672bd28630d9998fc2808df3659ddcf5a7eda  is in.

**Comment by williamspatrick** [comment]
Need bios file support from Nick and firestone_defconfig update for kernel commit pointer (per #70).

**Pull request merged**
