### PR TITLE
Update sbe.mk to pass SBE image name

### PR DESCRIPTION
**Pull request by nmuruli**
Pass SBE image name as input parameter to sbeOpDistribute.py

### CODE REVIEW

**Comment by dcrowell77** [comment]
@mabaiocchi

**Comment by danlarson-ibm** [comment]
retest this please

**Comment by danlarson-ibm** [comment]
ok to test

**Comment by danlarson-ibm** [comment]
Can one of the admins verify this patch?

**Comment by danlarson-ibm** [comment]
ok to test

**Comment by danlarson-ibm** [comment]
manual test please

**Comment by danlarson-ibm** [comment]
add to whitelist

**Comment by camvanng** [comment]
retest this please

**Comment by danlarson-ibm** [comment]
add to whitelist

**Comment by stewart-ibm** [comment]
ok to test

**Pull request merged**
