### PR TITLE
Patch to resolve backward compatibility

### PR DESCRIPTION
**Pull request by sgupta2m**
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1239)

### CODE REVIEW

**Comment by sgupta2m** [comment]
OK to test

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch for testing?

**Comment by stewart-ibm** [comment]
ok to test

**Comment by sgupta2m** [comment]
ok to test

**Comment by sgupta2m** [comment]
@sannerd @pragupta is this CI failure a known issue

**Comment by sannerd** [comment]
HW CI retest passed here: http://gfw160.aus.stglabs.ibm.com:8088/jenkins/job/OP_HW_CI_multi_p9/679/

**Pull request merged**
