### PR TITLE
openpower/configs: Set default hostname to skiroot

### PR DESCRIPTION
**Pull request by sammj**
Change the default hostname to something more useful than "buildroot".

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/456)

### CODE REVIEW

**Comment by mikey** [comment]
What about HostyMcHostFace?

**Comment by shenki** [comment]
LGTM, please merge

**Comment by ruscur** [comment]
A bit offtopic, but having some generic defconfig for every machine type would be good...changing something like this becomes more of a pain as you add more and more machines

**Comment by shenki** [comment]
@ruscur that's super off topic. Please open a bug

**Pull request merged**
