### PR TITLE
Enable host_fw_debug.tar file to keep file structure

### PR DESCRIPTION
**Pull request by wghoffa**
- The HB tools were losing their file structure,
       which caused commands like ecmd-debug-framework
       to fail as the required perl modules were not
       in the expected location

Signed-off-by: Bill Hoffa <wghoffa@us.ibm.com>

### CODE REVIEW

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
(I wonder why there's some build failures.. I'll retrigger everything as even opening the jankins pages takes too long)

**Comment by stewart-ibm** [comment]
```
#Create Debug Tarball
mkdir -p /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/witherspoon/OS/rhel6.4/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/pnor/host_fw_debug_tarball_files/
cp -r /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/witherspoon/OS/rhel6.4/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/../../../staging/hostboot_build_images//* /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/witherspoon/OS/rhel6.4/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/../../../build//skiboot-*/skiboot.elf /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/witherspoon/OS/rhel6.4/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/../../../build//skiboot-*/skiboot.map /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/witherspoon/OS/rhel6.4/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/../../../build//linux-*/.config /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/witherspoon/OS/rhel6.4/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/../../../build//linux-*/vmlinux /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/witherspoon/OS/rhel6.4/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/../../../build//linux-*/System.map /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/witherspoon/OS/rhel6.4/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/../../../images//zImage.epapr /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/witherspoon/OS/rhel6.4/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/pnor/host_fw_debug_tarball_files/
tar -zcvf /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/witherspoon/OS/rhel6.4/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/../../../images//host_fw_debug.tar -C .
tar: Cowardly refusing to create an empty archive
Try `tar --help' or `tar --usage' for more information.
```

which means something is going wrong in assembling it.

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch?

**Comment by wghoffa** [comment]
I must have a typo in that makefile compared to what I tested locally.... I'll fix it up here.

**Comment by wghoffa** [comment]
Fixed up here: https://github.com/open-power/op-build/pull/2322

**Pull request closed without merging**
