### PR TITLE
Single XML package rather than one per platform

### PR DESCRIPTION
**Pull request by stewart-ibm**
This saves us a *lot* of copy&pasted build foo and replaces it with a couple
of config options that can be set in menuconfig.

This makes adding a new platform a much smaller operation, requiring fewer
changes that are scattered throughout the buildroot tree.

Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1076)

### CODE REVIEW

**Comment by williamspatrick** [comment]
:+1:

**Comment by dcrowell77** [comment]
I'm a little lost in the changes, can you add a little more verbiage here describing how we end up after this?  We will still have system1-xml, system2-xml repositories that contain the actual MRW data, but now there is a generic machine-xml that drives the actual build?  Mechanically, what changes would there be to rebuild - do we need to dirclean+rebuild system1-xml and machine-xml?  Or do we now just generically build machine-xml because the initial defconfig will point to the right system package?

Thanks

**Comment by wghoffa** [comment]
@pragupta / @e-liner - What work do we have for this? It will change our Pull Request Creator tool as it'll update the XML version in a different file now (defconfig instead of <system-xml>.mk). Is that simple to change?

**Comment by wghoffa** [comment]
:lgtm:

---

Reviewed 46 of 46 files at r1.
Review status: 38 of 40 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/op-build/1076#-:-KkCDiMYUPdgtpKQraPs:bnfp4nl)*

**Comment by e-liner** [comment]
We'll probably have to add in a new function so it knows the new place to find the hash.  This shouldn't be that bad of a change, it just depends on when we can make it.

**Comment by williamspatrick** [comment]
@stewart-ibm - I don't see any update to the release script?

**Comment by stewart-ibm** [comment]
@williamspatrick that's because I'm missing an update to the release script :)

(It's coming, I just wanted to ensure everything else passed CI first)

**Comment by stewart-ibm** [comment]
Dan <notifications@github.com> writes:
> I'm a little lost in the changes, can you add a little more verbiage
> here describing how we end up after this?  We will still have
> system1-xml, system2-xml repositories that contain the actual MRW
> data, but now there is a generic machine-xml that drives the actual
> build?  Mechanically, what changes would there be to rebuild - do we
> need to dirclean+rebuild system1-xml and machine-xml?  Or do we now
> just generically build machine-xml because the initial defconfig will
> point to the right system package?

The repositories stay the same, it's just one common bit of
infrastructure to deal with them (and most of the ifs and weird config
things are about effectively not changing what gets run for any of the
platforms over the makefiles we have now).

Instaed of packages habanero-xml, palmetto-xml, witherspoon-xml, it is
all one machine-xml package (according to buildroot), it's just we vary
where the source comes from per platform in the defconfig file.

For driving a rebuild, you simply s/$(platform)-xml/machine-xml/ and
everything should "just work".

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by stewart-ibm** [comment]
Somebody with a bit more expertise in how a bunch of the XML fits together should probably take a look at everything at some point and work out if all the different combinations are *really* needed, or if there's a way to not have as many config options.

I think as it is now, we should be good for building all the things exactly how we were building all the things, just with less makefile explosion.

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
Flaky CI strikes again.

**Comment by stewart-ibm** [comment]
broken CI infrastructure *AGAIN*.

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
@wghoffa IT looks like the zaius box in CI has been hit by the SBE slave corruption thing that @mikey spotted on our Witherspoon. @pragupta you will probably have to get a special hostobot from @wghoffa to recover it.

**Comment by wghoffa** [comment]
@stewart-ibm - Agree. #1083 seemed to suffer the same fate. Working on recovering it now.

**Comment by dcrowell77** [comment]
Thanks for the explanation @stewart-ibm , I like this idea.

**Comment by wghoffa** [comment]
retest this please

**Comment by wghoffa** [comment]
Reviewed 1 of 46 files at r1, 4 of 4 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/op-build/1076)*

**Comment by wghoffa** [comment]
@stewart-ibm - The CI system is recovered, I'll try and get this passing everything today.

**Comment by wghoffa** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
If the P9 zaius machine is still broken at the end of this test, I'm merging it anyway.

**Comment by stewart-ibm** [comment]
"Build has been executing for 4 hr 22 min on gfw290" and still not completed 😭 😭 😭

**Comment by stewart-ibm** [comment]
Zaius machine is broken again.

But the iteration of tests before this last one did succeed everywhere. So, merging.

**Comment by wghoffa** [comment]
Heh, should scroll to the bottom before I review again :)

**Pull request merged**
