### PR TITLE
Update the HB level and swizzle patches

### PR DESCRIPTION
**Pull request by sannerd**
- Various (temp) patches needed to ungate CI testing

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1213)

### CODE REVIEW

**Comment by bofferdn** [comment]
Would rather put in the i2c patch that fixes the main issue, vs. reverting a bunch of stuff, it was a total pain to get it working the first time

**Comment by sannerd** [comment]
Tried the I2C patch -- however zaius.xml (and probably boston, romulus) don't have all the updated i2c information... and OPAL then faults on the incoming data....

Going to get the CI run to pass as is, just so we can make progress.

**Comment by sannerd** [comment]
Superseded by https://github.com/open-power/op-build/pull/1214 (per Nick's request above)

**Comment by sannerd** [comment]
https://github.com/open-power/op-build/pull/1214 has its own issues on witherspoon, resurrecting t his pull request (big hammer) instead of tweaks

**Comment by sannerd** [comment]
retest this please

**Comment by sannerd** [comment]
Fixed via https://github.com/open-power/op-build/pull/1218.  Closing

**Pull request closed without merging**
