### PR TITLE
Update Petitboot and enable Petitboot privilege separation

### PR DESCRIPTION
**Pull request by sammj**
Update to v1.10.0 and enable "Petitboot Users".
By default this has no affect aside from some minor UI and shell improvements.
If a password is configured via System Configuration or directly in NVRAM then all user-facing utilities run as unprivileged user accounts, including the shell. Most actions will require entering the password to proceed.

### CODE REVIEW

**Comment by sammj** [comment]
Still running some tests in the background, but I wanted to see this go through the op-build CI as well.

**Comment by stewart-ibm** [comment]
Sam Mendoza-Jonas <notifications@github.com> writes:
> Still running some tests in the background, but I wanted to see this
> go through the op-build CI as well.

one question is if we should sneak this into op-build v2.2 or get it in
at the start for the v2.3 cycle.

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by sammj** [comment]
Fixed up the mambo & palmetto defconfig order

**Comment by sammj** [comment]
Forgot the hash update too! Must be mid December or something.

**Comment by sammj** [comment]
Yep, we can hide the prompt with `-n`

**Comment by sammj** [comment]
The P8 IPL test passed except for on Palmetto, not sure whether this is legit though:
```
WHOAMI=hostboot
WORKSPACE_SLAVE=/tmp/hostboot-jenkins.swg-devops/jenkins-slave
WORKSPACE=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/HW/p8-test-param
Missing artifact deploy script
Build step 'Run with timeout' marked build as failure
```

**Comment by sammj** [comment]
https://hostboot-jenkins.swg-devops.com/job/Hostboot/job/OpenPower/job/HW/job/p9-test-param/16825/console also looks like a false positive.

**Comment by stewart-ibm** [comment]
retest this please

**Comment by sammj** [comment]
retest this please

**Pull request merged**
