### PR TITLE
buildroot: 2019.02.1, Linux 5.0, LVM, make, localedef fixes

### PR DESCRIPTION
**Pull request by shenki**
Update buildroot for Linux 5.0 support, LVM bug fix, localedef fix that should re-enable translations for Petitboot. Also includes 2019.02.1 security and bugfix point release.

### CODE REVIEW

**Comment by stewart-ibm** [comment]
retest this please

**Comment by shenki** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
CI has been busted since friday one way or another, ignoring the mess that is Austin and merging.

**Pull request merged**
