### PR TITLE
Bump version to v0.4

### PR DESCRIPTION
**Pull request by hellerda**
Latest release of sb-signing-utils.  Tested in Jenkins.

### CODE REVIEW

**Comment by wghoffa** [comment]
@bofferdn - Is there something you need to review here?

**Comment by hellerda** [comment]
Although it failed the build test (which I can't see), my guess is that it's really OK, since passed the other build and flash tests.

**Comment by hellerda** [comment]
Again: I'm thinking that the Build test failure is erroneous.  Is there a way to re-run the tests w/o a new pull request?  Thx,

**Comment by wghoffa** [comment]
@stewart-ibm - Can you weigh in on why 'Build test' failed?

**Comment by stewart-ibm** [comment]
@wghoffa @hellerda I can weigh in on why that failed: Jenkins is *FANTASTIC* and *completely* and **totally** reliable that absolutely *never* just randomly fails for no reason. :)

Anyway, besides from that, I see the commit here is missing your Signed-Off-by, which is required by https://github.com/open-power/op-build/blob/master/CONTRIBUTING.md (Developer Certificate of Origin). Please "git commit --amend -s && git push -f" so that we can merge.

Otherwise looks okay.

**Comment by hellerda** [comment]
Sorry, I usually to add the tag when I do the operations in git.  But for simple updates I do them through the github UI, and I didn't notice if has the option to apply the flag there.  I will check and resubmit as needed.

**Comment by hellerda** [comment]
Replaced by pull request #1841, closing this one.

**Pull request closed without merging**
