### PR TITLE
Update ci/ Dockerfiles to Fedora 27/Ubuntu 16.04LTS

### PR DESCRIPTION
**Pull request by stewart-ibm**
@pridhiviraj can you have a look at these? I think you're the primary user of them on a regular basis, so it'd be good to know that my changes here still work.

This brings us up to current supported Ubuntu LTS and Fedora.

### CODE REVIEW

**Comment by pridhiviraj** [comment]
@stewart-ibm `rsync` package missing for fedora27 Dockerfile, after adding that it works fine. PNOR images built successfully. I will test for Ubuntu and update here.

**Comment by stewart-ibm** [comment]
Updated the fedora27 dockerfile to add rsync (and make it look a bit neater)

**Comment by pridhiviraj** [comment]
@stewart-ibm With ubuntu builds fine with minor failure at the end.
```
make: Leaving directory '/home/ubuntu/stewart_opbuild/op-build/buildroot'
+ r=0
+ mkdir output-images/ubuntu1604/witherspoon_defconfig-images
+ mv output/images/cappucode.bin output/images/host_fw_debug.tar output/images/ima_catalog.bin output/images/rootfs.cpio output/images/rootfs.cpio.xz output/images/rootfs.tar output/images/skiboot.lid output/images/skiboot.lid.bin output/images/witherspoon.pnor output/images/witherspoon.pnor.squashfs.tar output/images/zImage.epapr output-images/ubuntu1604/witherspoon_defconfig-images/
+ mv output/.config output-images/ubuntu1604/witherspoon_defconfig-images/.config
+ lsb_release -a
./ci/build-all-defconfigs.sh: line 45: lsb_release: command not found
```

**Comment by stewart-ibm** [comment]
Paidipeddi Pridhiviraj <notifications@github.com> writes:
> ./ci/build-all-defconfigs.sh: line 45: lsb_release: command not found

Whoops. My inadequate testing is pretty obvious now :)

Fix coming

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by stewart-ibm** [comment]
@pridhiviraj does this look good to you now?

**Comment by pridhiviraj** [comment]
@stewart-ibm Yes, As you mentioned in slack by running the apt-get update and install in combine images built fine.
```
+RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -yy cscope ctags \
```

**Pull request merged**
