### PR TITLE
Change op-build to use build script from public directory.

### PR DESCRIPTION
**Pull request by sandeepkumaryadaw**
JIRA: PFSBE-854
STGD: 613141
Signed-off-by: sandeep <sandeep.kumar.yadav@ibm.com>

### CODE REVIEW

**Review by akhis023 — APPROVED** [review]

**Comment by skumar8j** [comment]
Code looks good.

**Comment by dcrowell77** [comment]
test this please

**Review by dcrowell77 — APPROVED** [review]
Looks fine, just waiting for CI

**Comment by dcrowell77** [comment]
retest this please

**Comment by fspbld** [comment]
retest this please

**Pull request merged**
