### PR TITLE
xmltohb.pl: pass mrw scratch dir as src-output-dir

### PR DESCRIPTION
**Pull request by pragupta**
This will allow the generation of PersistRwAttrList.csv in
output/staging/openpower_mrw_scratch/ instead of buildroot

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1196)

### CODE REVIEW

**Comment by pragupta** [comment]
retest this please

**Comment by popfuture** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/op-build/1196)*

**Comment by pragupta** [comment]
@stewart-ibm what are these Build tests that are failing? I can't seem to get to them. Can I safely ignore?

**Comment by stewart-ibm** [comment]
Prachi Gupta <notifications@github.com> writes:
> @stewart-ibm what are these Build tests that are failing? I can't seem
> to get to them. Can I safely ignore?

Yeah, safely ignore, we're hunting jenkins bugs.

-- 
Stewart Smith
OPAL Architect, IBM.

**Pull request merged**
