### PR TITLE
Enable secure boot for P9DSU.

### PR DESCRIPTION
**Pull request by jimsmc**

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch for testing?

**Comment by stewart-ibm** [comment]
Hi! You seem to be missing your `Signed-off-by` in this commit as required by https://github.com/open-power/op-build/blob/master/CONTRIBUTING.md#developer-certificate-of-origin

You can fix this with `git commit --amend -s && git push -f` and then we'll be able to merge

**Comment by jimsmc** [comment]
@stewart-ibm, this change is ready to be merged.

**Comment by youhour** [comment]
bonston18 has been recovered and boot to petitboot now.

**Comment by stewart-ibm** [comment]
@youhour there's still problems with enabling this. By turning this on, simply going from op-build master to op-build master plus this change (i.e. from 1a59e5e67cac04edc099296824208c1bc93b6772 to what would happen if i merged this) we end up not getting past the SBE.

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch?

**Comment by stewart-ibm** [comment]
Is this still applicable? Does somebody want to shepherd this into the tree?

If not, please close it, or I will in a few days.

**Pull request closed without merging**
