### PR TITLE
Fix conflict for Default to std=gnu++03 patch

### PR DESCRIPTION
**Pull request by scprek**
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/922)

### CODE REVIEW

**Comment by dcrowell77** [comment]
Seems good to me

**Comment by stewart-ibm** [comment]
Why not respin the original patch? It's still sitting waiting to be reviewed and merged into Hostboot, along with most of the others.

I also can't seem to find this change id (or anything else that would cause the conflict) in gerrit. URL?

**Comment by dcrowell77** [comment]
I don't think these changes are compatible with the local build environment that we use for P8.  I'm investigating a way to make it dependent on the build environment.

**Comment by scprek** [comment]
only hit our known ubuntu issues. Rebuilding now with the bad node down

**Comment by stewart-ibm** [comment]
Stephen Cprek <notifications@github.com> writes:
> only hit our known ubuntu issues. Rebuilding now with the bad node
> down

I guess that's a known issue with something internal to HB team? I'm not
aware of any Ubuntu issue with upstream code.


-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by scprek** [comment]
@stewart-ibm Yes, only to our internal CI process. It's why the Jenkins test failed the first time.

**Comment by scprek** [comment]
@dcrowell77 Looks like @stewart-ibm has implemented the patches in hostboot
https://ralgit01.raleigh.ibm.com/gerrit1/#/c/32209/6 No reviewers on it.

**Comment by dcrowell77** [comment]
Yep, I pulled in a chunk of this request to see how it worked.

**Pull request closed without merging**
