### PR TITLE
Remove CCACHE from p9 defconfig

### PR DESCRIPTION
**Pull request by deece**
The decision to use CCACHE or not should be up to the user.

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/527)

### CODE REVIEW

**Comment by sammj** [comment]
Patch looks fine but it is missing your signed-off by.

**Comment by deece** [comment]
Should be fixed now

**Comment by stewart-ibm** [comment]
Whoops - my fault this one. Merging in as the jenkins tests that run here don't actually do P9 testing.

**Comment by williamspatrick** [comment]
None of the mambo configs are tested as part of the CI test.  Talk to @jazurin if you would like that changed.

**Pull request merged**
