### PR TITLE
skiboot v6.6-rc1-9-g9547b3da

### PR DESCRIPTION
**Pull request by opalci**
Stewart Smith (1):
      platform: add Raptor Blackbird support

Vasant Hegde (4):
      skiboot v6.0.23 release notes
      fsp: Ignore platform dump notification on P9
      MPIPL: Add support to save crash CPU details on FSP system
      ZZ: Fix System Attention Indicator location code

Signed-off-by: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by hegdevasant** [comment]
retest this please

**Comment by hegdevasant** [comment]
@oohal @stewartsmith FYI.. I have dropped blackbird support patch (001-platform-add-Raptor-Blackbird-support.patch) from op-build as we have merged blackbird support to skiboot upstream.

-Vasant

**Comment by stewartsmith** [comment]
On Mon, Apr 20, 2020, at 10:11 PM, Vasant Hegde wrote:
> @oohal <https://github.com/oohal> @stewartsmith 
> <https://github.com/stewartsmith> FYI.. I have dropped blackbird 
> support patch (001-platform-add-Raptor-Blackbird-support.patch) from 
> op-build as we have merged blackbird support to skiboot upstream.

Fantastic, thanks!

**Comment by oohal** [comment]
retest this please

**Comment by hegdevasant** [comment]
` IBM OP CI HW IPL test -- p8 ` is completed. But for some reason it didn't update the PR.

[WS-CLEANUP] Deleting project workspace...[WS-CLEANUP] done
Strings match run condition: string 1=[false], string 2=[true]
Run condition [Strings match] preventing perform for step [Builder to mark whether executed]
Strings match run condition: string 1=[false], string 2=[true]
Run condition [Strings match] preventing perform for step [Builder to mark whether executed]
Strings match run condition: string 1=[false], string 2=[true]
Run condition [Strings match] preventing perform for step [Builder to mark whether executed]
Finished: SUCCESS

-Vasant

**Pull request merged**
