### PR TITLE
Enable OCC by default in Zaius

### PR DESCRIPTION
**Pull request by wghoffa**
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1156)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch?

**Comment by agangidi53** [comment]
same as this https://github.com/open-power/op-build/pull/1114

**Comment by wghoffa** [comment]
Yeah sorry, I noticed that a bit ago. Now that we moved the fw levels up this will now work.

**Comment by wghoffa** [comment]
Only Jenkins fails were Jenkins tools errors, Systems IPLs and everything else compiles, going to merge this.

**Pull request merged**
