### PR TITLE
linux: Enable ipmi watchdog support

### PR DESCRIPTION
**Pull request by wak-google**
We need this support so that the skiroot linux kernel can handle the
watchdog after it is handed off by skiboot. This way we can keep the
watchdog enabled throughout the entire skiboot handoff to linux instead
of disabling it prior to executing the linux kernel. This allows us to
increase our watchdog coverage during boot.

It also gives us the benefit that we can now use the ipmi watchdog
through /dev/watchdog in the skiroot environment.

### CODE REVIEW

**Comment by jk-ozlabs** [comment]
OK, so it does disable before kexec, that's great. All fine by me then.

**Comment by wak-google** [comment]
Anyone else I need to sign off on this?

**Comment by shenki** [comment]
LGTM. @stewart-ibm can we please merge this?

**Comment by stewart-ibm** [comment]
"William A. Kennington III" <notifications@github.com> writes:
> Anyone else I need to sign off on this?

Let me run it through a few tests and I'll be okay to merge it.

I trust the CI about as far as I can throw a gorilla, so I'll run actual
tests :)
-- 
Stewart Smith
OPAL Architect, IBM.

**Pull request merged**
