### PR TITLE
Split P8 and P9 Hostboot and OCC packages

### PR DESCRIPTION
**Pull request by stewart-ibm**
This was causing a couple of issues:
1) increased complexity in build files
2) It breaks the pkg-version patch detection/checksum
3) Failing to apply patches to HB silently fails.

The split makes this a bit easier and requires less custom code.
We have the p8 and p9 packages provide the 'hostboot' virtual package,
allowing all the existing dependencies to work.

Fixes: https://github.com/open-power/op-build/issues/876
Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1359)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
@dcrowell77 @zane131 @shenki This is what I mean when I say split HB into p8/p9 for building. This would fix the patches silently failing to apply problem as well as simplify makefiles a bit. The same thing here could be done for OCC code.

**Comment by stewart-ibm** [comment]
Also fixes https://github.com/open-power/op-build/issues/1194 (I'll add that to Fixes in the commit too)

**Comment by dcrowell77** [comment]
Can you elaborate a bit on how this changes the external functionality?  Would we just change to using 'hostboot-p9' as the package name for op-build commands then?

This:
> op-build hostboot-rebuild

becomes this?
> op-build hostboot-p9-rebuild

**Comment by stewart-ibm** [comment]
@dcrowell77 yeah, it's exactly that. `hostboot-rebuild` would be `hostboot-p9-rebuild` and with what I just pushed for OCC to fix https://github.com/open-power/op-build/issues/1560 - same for OCC.

**Comment by stewart-ibm** [comment]
I'm taking a slightly different approach to this, and I don't think this PR needs to stay open for that.

**Pull request closed without merging**
