### PR TITLE
Bump kernel to 5.10.223

### PR DESCRIPTION
**Pull request by abhisheksinghtomar**

### CODE REVIEW

**Comment by fspbld** [comment]
ok to test

**Comment by dcrowell77** [comment]
Looks like infrastructure issues, I'll restart it

ssh: connect to host 9.41.165.71 port 22: Connection timed out

**Comment by dcrowell77** [comment]
retest this please

**Comment by maheshsal** [comment]
Looks like it is still failing with same reason 

08/16/2024 10:42:16 [rc_pnor_reimage=1] Finished updating PNOR image on host of witherspoon (9.41.165.71)

08/16/2024 10:42:16 Collecting journal log for "pnor_reimage" ...
ssh: connect to host 9.41.165.71 port 22: Connection timed out
ssh: connect to host 9.41.165.71 port 22: Connection timed out

**Comment by dcrowell77** [comment]
Current BMC image:
ssh: connect to host 9.41.165.71 port 22: Connection timed out

Looking into if a P9 system got moved around since the last time this job ran...

**Pull request merged**
