### PR TITLE
Added suport for stonewither board

### PR DESCRIPTION
**Pull request by LowellDennis**
This pull request is in response to issues with the original pull request I generated (#1931).

The initial pull request had the following issues as delineated by Steward Smith

1) **power-fixed2.patch** was in stonewither specific patch directory.
    It has been moved to general Linux patch directory as requested.
2) **stonewither_defconfig** referred to linux build 4.14.6.
    Updated to refer to Linux build 4.15.6 as requested.
3) **stonewither_defconfig** referred stonewither patches folder.
    In conversations with Bill Hoffa and Nicole Schwartz Nett we believe this is safe
    in connection with recent changes to witherspoon.xml and reflected in stonewither.xml
   with respect to the work-arounds  for the stop4/5 issues.
4) **output/.gitignore** had been removed.
    This has been corrected as suggested.
5) It was requested that all of the updates be condensed into a single commit.
    This has been done as requested.

It should also be noted that the skiboot patch file that Stewart Smith sent was added so that all references to witherspoon could be removed from **stonewither.xml**

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch for testing?

**Comment by wghoffa** [comment]
ok to test

**Comment by wghoffa** [comment]
@stewart-ibm - Are we good to go here?

**Comment by stewart-ibm** [comment]
Since stonewither is not currently planned to go ahead, I'm going to close this PR.

Thanks everyone for your work on this though.

**Pull request closed without merging**
