### PR TITLE
Release Linux v4.10.9-openpower1

### PR DESCRIPTION
**Pull request by shenki**
This adds "powerpc/powernv: Add OPAL exports attributes to sysfs",
backported from the powerpc/next branch.

Signed-off-by: Joel Stanley <joel@jms.id.au>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1016)

### CODE REVIEW

**Comment by sammj** [comment]
```
URI:https://9.3.23.134/org/openbmc/managers/System//action/getSystemState, method:Post, args:{u'data': {u'data': []}, u'headers': {u'Content-Type': u'application/json'}}
Response code:200, Content:{
  "data": "HOST_BOOTED", 
  "message": "200 OK", 
  "status": "ok"
}
| FAIL |
Keyword 'Verify BMC State' failed after retrying for 10 minutes. The last error was: '[u'BMC_READY', u'HOST_POWERED_OFF']' does not contain 'HOST_BOOTED'
```
Without knowing too much about how this test works, that looks like an issue with Jenkins rather than the PR.

**Comment by shenki** [comment]
retest this please

**Comment by shenki** [comment]
I don't think I have permission to force a retest

**Comment by pragupta** [comment]
retest this please

**Comment by pragupta** [comment]
retest this please

**Comment by pragupta** [comment]
retest this please

**Comment by pragupta** [comment]
retest this please

**Comment by pragupta** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by sameerveer** [comment]
retest this please

**Comment by sameerveer** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
Can we please get rid of this robot shit that just plain doesn't work?
screenshot from 2017-05-03 14-06-03

Seriously, how on earth is anyone meant to use it if you can't even view a log file (which for some reason is a TWELVE MEGABYTE html file that just displays the above).

The attached screenshot takes 40x less disk space than Robot does.

Plus, from the SOL log, it appears the machine booted.

It's possible the machines aren't set up correctly too, as this isn't exactly confidence inspiring:
```
sed: can't read s/sed:: No such file or directory
```

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
Discussed with @shenki , we're going to go straight to 4.11

**Pull request closed without merging**
