### PR TITLE
ci: Switch to fedora30 for docker based CI

### PR DESCRIPTION
**Pull request by stewartsmith**
Signed-off-by: Stewart Smith <stewart@linux.ibm.com>

### CODE REVIEW

**Comment by hegdevasant** [comment]
Looks good to me.

-Vasant

**Comment by stewartsmith** [comment]
The CI failure here should not have anything to do with this PR as the CO job there doesn’t even use the Docker bits

**Comment by hegdevasant** [comment]
> The CI failure here should not have anything to do with this PR as the CO job there doesn’t even use the Docker bits

Agreed. 

I tried to look into jenkin job. But its throwing `http 404` error to me.

I'm tempted to merge this patch.

@shenki ^^ 

-Vasant

**Comment by shenki** [comment]
retest this please

**Comment by hegdevasant** [comment]
retest this please

**Comment by hegdevasant** [comment]
CI failures are nothing to do with this PR. Merging .

-Vasant

**Pull request merged**
