### PR TITLE
patches/mihawk: adjust patch to apply on top of skiboot-increasing patch

### PR DESCRIPTION
**Pull request by naynajain**
Mihawk patch was failing after merging skiboot partition size patch - https://github.com/open-power/pnor/pull/134

This patch fixes the mihawk patch - openpower/patches/mihawk-patches
to apply correctly now.

Thanks & Regards,
     - Nayna

### CODE REVIEW

**Comment by klauskiwi** [comment]
@naynajain thanks for the patch. But in the same PR, you'll need to move the openpower-pnor reference (i.e., in `openpower/packages/openpower-pnor/openpower-pnor.mk`) to grab the latest version (i.e., https://github.com/open-power/pnor/commit/e582e4ac5941da0e728aecb44e22ecc5ee0ac53a) and then you resolve any conflicts of the mihawk patch caused by that change..

**Comment by klauskiwi** [comment]
please make sure you do a builds of `./op-build mihawk_defconfig` at least once to validate, post results. Thanks

**Comment by naynajain** [comment]
> @naynajain thanks for the patch. But in the same PR, you'll need to move the openpower-pnor reference (i.e., in `openpower/packages/openpower-pnor/openpower-pnor.mk`) to grab the latest version (i.e., [open-power/pnor@e582e4a](https://github.com/open-power/pnor/commit/e582e4ac5941da0e728aecb44e22ecc5ee0ac53a)) and then you resolve any conflicts of the mihawk patch caused by that change..

The openpower-pnor.mk is already pulling the commit id that you specified -
OPENPOWER_PNOR_VERSION ?= e582e4ac5941da0e728aecb44e22ecc5ee0ac53a
OPENPOWER_PNOR_SITE ?= $(call github,open-power,pnor,$(OPENPOWER_PNOR_VERSION))

That means I don't have to do anything extra and is tested on right one. Yes I have validated it doing mihawk_defconfig

**Comment by klauskiwi** [comment]
@naynajain The math looks right and I checked that the patch is applying cleanly on mihawk_defconfig + `./op-build openpower-pnor-patch`, but have you built an image with a clean tree to check that it is at least building successfully? Perhaps @NicholeWang could test it?

Additionally, I need a proper commit message, with signed-off-by...

Thanks,

 -Klaus

**Comment by naynajain** [comment]
> @naynajain The math looks right and I checked that the patch is applying cleanly on mihawk_defconfig + `./op-build openpower-pnor-patch`, but have you built an image with a clean tree to check that it is at least building successfully? Perhaps @NicholeWang could test it?
> 

Yes I did build the mihawk image with clean tree. I only built, not tested which is not possible also for me.

That would be great if @NicholeWang  can test it and verify.

> Additionally, I need a proper commit message, with signed-off-by...
> 
Sure. Sorry looks like I missed it somehow. I will do that and push again.

Thanks & Regards,
    - Nayna

**Comment by naynajain** [comment]
Have pushed the updated commit with patch description and Signed-off.

Thanks & Regards,
     - Nayna

**Comment by klauskiwi** [comment]
ok to test

**Pull request merged**
