### PR TITLE
linux: Move to v5.10.184

### PR DESCRIPTION
**Pull request by maheshsal**
Update to the latest v5.10 kernel for security and bug fixes.

### CODE REVIEW

**Comment by fspbld** [comment]
ok to test

**Comment by fspbld** [comment]
retest this please

**Comment by dcrowell77** [comment]
retest this please

**Comment by maheshsal** [comment]
Any update on this ?

**Comment by dcrowell77** [comment]
retest this please

**Comment by dcrowell77** [comment]
Looks like the CI jobs are having issues.  The ubuntu compiled fails with this.

make[1]: Entering directory '/tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-4644/CONFIG/witherspoon/OS/ubuntu/build/op-build/output/build/hcode-hw042423a.opmst'
    DEP        ppetracepp.dep
    C++        ppetracepp.o
../../import/chips/p9/procedures/ppe/tools/ppetracepp//ppetracepp.C: In function ‘int main(int, char**)’:
../../import/chips/p9/procedures/ppe/tools/ppetracepp//ppetracepp.C:1097:14: error: ignoring return value of ‘char* fgets(char*, int, FILE*)’ declared with attribute ‘warn_unused_result’ [-Werror=unused-result]
 1097 |         fgets(buf, MAX_BUFFER, PWD);
      |         ~~~~~^~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[3]: *** [../../import/chips/p9/procedures/ppe/tools/ppetracepp/ppetracepp.mk:33: ../../import/../output/obj/ppetracepp/ppetracepp.o] Error 1


And the redhat job fails with a bunch of missing files...

In file included from ../../../../../src/import/chips/p9/procedures/hwp/memory/mss.H:79,
                 from ../../../../../src/import/chips/p9/procedures/hwp/memory/lib/workarounds/freq_workarounds.C:40:
../../../../../src/import/chips/p9/procedures/hwp/memory/lib/mc/mc.H:42:10: fatal error: ../../../../../src/import/chips/p9/common/include/p9_mc_scom_addresses_fld.H: No such file or directory
compilation terminated.
make[13]: *** [../../../../../src/build/mkrules/cc.rules.mk:82: ../../../../../obj/modules/prdf_rt/freq_workarounds.o] Error 1
make[13]: *** Waiting for unfinished jobs....
    CXX        p9_pm_ocb_init.C
powerpc64le-buildroot-linux-gnu-g++: error: ../../../../../src/import/chips/p9/procedures/hwp/pm/p9_pm_ocb_init.C: No such file or directory

**Comment by maheshsal** [comment]
Any idea when CI build failure will get fix?

**Comment by dcrowell77** [comment]
retest this please

**Comment by maheshsal** [comment]
So this PR is now superceded by https://github.com/open-power/op-build/pull/5631. We should get #5631 merged to master.

**Comment by dcrowell77** [comment]
https://github.com/open-power/op-build/pull/5631 seems to still be in draft mode, not sure if CIs will trigger or not, I poked it to see.

**Comment by IlyaSmirnov91** [comment]
Superseded by #5631

**Pull request closed without merging**
