### PR TITLE
skiboot: Change to BR2_PACKAGE_SKIBOOT from BR2_TARGET_SKIBOOT

### PR DESCRIPTION
**Pull request by stewart-ibm**
We think that BR2_TARGET rather than BR2_PACKAGE was originally
used incorrectly as a way to produce a single LID for an FSP build
back sometime in 2014 or before.

Suggested-by: Alastair D'Silva <alastair@d-silva.org>
Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/414)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
@deece - this look good to you? I've pulled out that one change as it does seem to fix a thing, and is separate from bumping buildroot up

**Comment by williamspatrick** [comment]
You guys didn't even let this commit go through test before you merged it. Barreleye and garrison are now broken.

**Comment by williamspatrick** [comment]
You guys didn't even let this commit go through test before you merged it. Barreleye and garrison are now broken.

**Comment by williamspatrick** [comment]
Also mambo config.

**Comment by williamspatrick** [comment]
The issue wasn't detected by our CI job because it reused the skiboot image from an earlier compile to put into the Barreleye image.  I am fixing the missing configs with #416

**Comment by stewart-ibm** [comment]
Hrm... I swear I saw everything complete okay, and did try locally (although I obviously missed building a couple of configs).... and how did I miss editing them... eep.

Sorry about that.

**Comment by deece** [comment]
Looks reasonable - I didn't have the barreleye config, so no patch for that was submitted, so it would be an easy oversight. Have you done a grep to ensure there are no other references to BR2_TARGET_SKIBOOT?

**Comment by williamspatrick** [comment]
Yes, I fixed all the remaining packages.

On Wed, Mar 30, 2016 at 09:59:56PM -0700, deece wrote:
> Looks reasonable - I didn't have the barreleye config, so no patch for that was submitted, so it would be an easy oversight. Have you done a grep to ensure there are no other references to BR2_TARGET_SKIBOOT?
> 
> ---
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/open-power/op-build/pull/414#issuecomment-203752503

-- 
Patrick Williams

**Pull request merged**
