### PR TITLE
hostboot: Add patches to fix cmpi assembly

### PR DESCRIPTION
**Pull request by shenki**
Signed-off-by: Joel Stanley <joel@jms.id.au>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1174)

### CODE REVIEW

**Comment by shenki** [comment]
Yeah, I have sent it to the internal gerrit.

As I understand it, the change is preserving the status quo - old binutils was generating cmpw instructions when the code had cmp. Please correct me on the internal code review if that's not the case.

**Comment by shenki** [comment]
For reference, this is change is a noop with the existing toolchain. We change from implicitly generating the cmpwi to explicitly stating in for compatibility with newer toolchains.
```
$ cat asm-test.S 
.text
.global test
        cmpi 0, 8, 1
$ /opt/cross/gcc-4.9.3-nolibc/powerpc64-linux/bin/powerpc64-linux-gcc -c asm-test.S 
$ objdump -d asm-test.o 
0000000000000000 <.text>:
   0:	2c 08 00 01 	cmpwi   r8,1
```

Old compiler, updated instruction:
```
$ cat asm-test.S 
.text

.global test
        cmpwi 0, 8, 1
$ /opt/cross/gcc-4.9.3-nolibc/powerpc64-linux/bin/powerpc64-linux-gcc -c asm-test.S 
$ objdump -d asm-test.o 
0000000000000000 <.text>:
   0:	2c 08 00 01 	cmpwi   r8,1
```

And then the new compiler with the updated asm: 
```
$ cat asm-test.S 
.text

.global test
        cmpwi 0, 8, 1
$ powerpc64-linux-gnu-gcc --version
powerpc64-linux-gnu-gcc (Ubuntu 6.3.0-16ubuntu6) 6.3.0 20170506
$ powerpc64-linux-gnu-gcc -c asm-test.S 
$ objdump -d asm-test.o 
0000000000000000 <.text>:
   0:	2c 08 00 01 	cmpwi   r8,1
```

**Comment by stewart-ibm** [comment]
FYI, Tomorrow I'm going to look at merging this and the buildroot bump.

**Comment by shenki** [comment]
Updated with upstream patch from master branch. P8 patch is still in the review queue due to process stuff, but it's essentially the same change.

**Comment by stewart-ibm** [comment]
Usual Zaius failure... :/
(my build test job had a false failure due to issues with jenkins)

**Pull request merged**
