### PR TITLE
buildroot: Move to 2019.05

### PR DESCRIPTION
**Pull request by shenki**
Upstream release notes:

 http://lists.busybox.net/pipermail/buildroot/2019-June/251548.html
 https://git.buildroot.net/buildroot/plain/CHANGES?id=2019.05

Signed-off-by: Joel Stanley <joel@jms.id.au>

### CODE REVIEW

**Comment by stewart-ibm** [comment]
```
ERROR: PnorUtils::checkSpaceConstraints: Image provided (/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/p9dsu/OS/op-build-ci-rhel7/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//zImage.epapr) has size (31457280) which is greater than allocated space (15728640) for section=BOOTKERNEL.  Aborting! at /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/p9dsu/OS/op-build-ci-rhel7/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/hostboot_build_images/PnorUtils.pm line 385.
```

okay, that's strange. and only for p9dsu...

**Comment by stewart-ibm** [comment]
retest this please

**Comment by shenki** [comment]
> okay, that's strange. and only for p9dsu...

Not too strange, given p9dsu includes the QLOGIC_2XXX firmware in addition to the firmwares that the other platforms include. Of the six files that this enables, we only whitelist ql2500_fw.bin which is 270KB.

But the size you have there is double normal, so something must have gone horribly wrong!

**Comment by stewart-ibm** [comment]
retest this please

**Comment by shenki** [comment]
retest this please

**Comment by shenki** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Pull request merged**
