### PR TITLE
Romulus disable the console trace and update machine XML

### PR DESCRIPTION
**Pull request by stewart-ibm**
(cherry picked from commit a0163b392cf902bd68fbdd2e9d390b12a46b9233)
Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>

(just pumping this through CI)

### CODE REVIEW

**Comment by wghoffa** [comment]
retest this please

**Comment by MengzeLiao** [comment]
retest this please

**Comment by wghoffa** [comment]
retest this please

**Comment by wghoffa** [comment]
retest this please

**Pull request merged**
