### PR TITLE
skiboot v6.1-25-g25f7266f736c

### PR DESCRIPTION
**Pull request by stewart-ibm**
Alistair Popple (2):
      Move pb_cen_hp_mode_curr register definition to xscom-p9-reg.h
      phb4: Disable nodal scoped DMA accesses when PB pump mode is enabled

Andrew Jeffery (6):
      ast-bmc: Move copy routines to ast-sf-ctrl
      core/pci-quirk: Remove broken comment in quirk_astbmc_vga()
      core/pci-quirk: Clean up commented code in quirk_astbmc_vga()
      ast-bmc: Rename LPC FW cycle helpers
      ast-io: Rework setup/tear-down of communication with the BMC
      lpc: Silence LPC SYNC no-response error when necessary

Michael Ellerman (1):
      doc: Add documentation on supported platforms and CPUs

Nicholas Piggin (1):
      cpu: add cpu_queue_job_on_node()

Prem Shanker Jha (1):
      STOP API: API conditionally supports 255 SCOM restore entries for each quad.

Reza Arbab (2):
      npu2/hw-procedures: Don't open code NPU2_NTL_MISC_CFG2_BRICK_ENABLE
      npu2/hw-procedures: Enable parity and credit overflow checks

Samuel Mendoza-Jonas (2):
      Recognise signed VERSION partition
      core/flash: Emit a warning if Skiboot version doesn't match

Stewart Smith (8):
      fast-reboot: parallel memory clearing
      Scan PCI and clear memory simultaneously
      mem_region: log region name on mem_alloc failure
      mem_check(): Correct alignment assumptions
      Fixup unit tests for cpu_queue_job() in mem_region.c
      Fixup pflash build for ast refactor
      skiboot 6.0.6 release notes
      core/cpu.c: assert pir is sane before using

Vaibhav Jain (2):
      phb4: Reallocate PEC2 DMA-Read engines to improve GPU-Direct bandwidth
      doc: Add a man page for OPAL_PCI_SET_PHB_CAPI_MODE

Signed-off-by: Stewart Smith <stewart@linux.ibm.com>

### CODE REVIEW

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
I'm about to perma-ban the damn CI system that never *ever* works correctly. Grrrrrr.....

**Comment by stewart-ibm** [comment]
@sammj looks like we're going to have to wait for the other patches that do the signed VERSION partition before we merge this - the CI systems have secure boot enabled and thus we quite rightly fail.

**Comment by sammj** [comment]
@stewart-ibm The one time CI works correctly and it's my change at fault :grimacing:

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch?

**Pull request closed without merging**
