### PR TITLE
Bump Petitboot to v1.1.1

### PR DESCRIPTION
**Pull request by sammj**
Signed-off-by: Samuel Mendoza-Jonas <sam@mendozajonas.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/495)

### CODE REVIEW

**Comment by williamspatrick** [comment]
please retest this

**Comment by sammj** [comment]
```
gzip: /tmp/hostboot/jenkins-slave/workspace/op_build_ghprb_trigger/dl/capp-ucode-105cb8f69edb7e76c4d153bf2e5c9718811a3114.tar.gz: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
make[1]: *** [/tmp/hostboot/jenkins-slave/workspace/op_build_ghprb_trigger/output/build/capp-ucode-105cb8f69edb7e76c4d153bf2e5c9718811a3114/.stamp_extracted] Error 2
make: *** [_all] Error 2
```

and

```
gzip: /tmp/hostboot/jenkins-slave/workspace/op_build_ghprb_trigger/dl/p8-pore-binutils-1d6a41d5a5104ce9bc8b6ad59f8e58c3a50824a4.tar.gz: not in gzip format
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
make[1]: *** [/tmp/hostboot/jenkins-slave/workspace/op_build_ghprb_trigger/output/build/host-p8-pore-binutils-1d6a41d5a5104ce9bc8b6ad59f8e58c3a50824a4/.stamp_extracted] Error 2
make: *** [_all] Error 2
make: Leaving directory `/tmp/hostboot/jenkins-slave/workspace/op_build_ghprb_trigger/buildroot'
palmetto BUILD FAILED!!
```

Aren't Petitboot build errors - is this intermittent or a new regression?

**Comment by williamspatrick** [comment]
We seem to be having trouble with GitHub and package downloading. Jay looking into it.

**Comment by jazurin** [comment]
retest this please

**Comment by jazurin** [comment]
We have some issues with our Jenkins nodes running RHEL.  Downloads are getting corrupted for some reason.   Our Ubuntu node doesn't have this problem.  I've diverted to pull request builds to that node temporarily.

**Comment by fspbld** [comment]
I am seeing this on our full op-build runs now, too. First failure was noticed 06/19.

**Comment by jazurin** [comment]
@fspbld I think this is a problem with github.  I sent them a message with all my findings.

**Pull request merged**
