### PR TITLE
Move to public sbe-odyssey repo - DO NOT MERGE YET

### PR DESCRIPTION
**Pull request by dcrowell77**
Start using the public sbe-odyssey repository for op-build.

### CODE REVIEW

**Comment by dcrowell77** [comment]
retest this please

**Comment by danlarson-ibm** [comment]
test this please

**Review by danlarson-ibm — COMMENTED** [review]
cleared the cache before the last test. same error

**Comment by dcrowell77** [comment]
Running locally and have discovered a couple issues in the sbe-odyssey source repository that are being worked.

**Comment by dcrowell77** [comment]
Current failure is a permission issue that needs to be fixed in the sbe-odyssey repo

PermissionError: [Errno 13] Permission denied: '/esw/san5/dcrowell/op10/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/ody-pak-files/sbe_tools/ecc'

**Review by zane131 — CHANGES_REQUESTED** [review]
It is too late to make any changes for FW1060.10. This will have to wait for FW1060.20.

**Comment by dcrowell77** [comment]
test this please

**Comment by danlarson-ibm** [comment]
test this please

**Comment by dcrowell77** [comment]
Some of the files required for Simics use were not added to the public side of the tree so all of the full system simulation tests are failing.  The SBE team is working on this.

**Pull request merged**
