### PR TITLE
Kernel 5.10.50 and buildroot 2021.02

### PR DESCRIPTION
**Pull request by shenki**

### CODE REVIEW

**Comment by hegdevasant** [comment]
retest this please

**Comment by hegdevasant** [comment]
Looks like even I'm not in admin list?

@dcrowell77 @IlyaSmirnov91 Can you pls trigger CI ? 

-Vasant

**Comment by IlyaSmirnov91** [comment]
Ok to test

**Comment by IlyaSmirnov91** [comment]
retest this please

**Comment by IlyaSmirnov91** [comment]
ok to test

**Comment by IlyaSmirnov91** [comment]
ok to test

**Review by hegdevasant — APPROVED** [review]

**Comment by IlyaSmirnov91** [comment]
HB CI passed.

**Pull request merged**
