### PR TITLE
Remove config setting to enable NO_DMI_EREPAIR

### PR DESCRIPTION
**Pull request by Bilicon**
OpenPower Issue: 194

### CODE REVIEW

**Comment by williamspatrick** [comment]
https://github.com/open-power/hostboot/commit/500b18263e24bb22ad16456acbd5583ac25dacf7

Depends on this commit.

**Comment by williamspatrick** [comment]
@Bilicon - Need you to rebase this so it can be merged.

**Comment by Bilicon** [comment]
Rebase is done.

**Comment by williamspatrick** [comment]
Still wasn't rebased correctly, so I merged manually for you and added to master-next.

**Pull request closed without merging**
