### PR TITLE
buildroot: Update to 8dd7d991

### PR DESCRIPTION
**Pull request by jk-ozlabs**
This change adds an init script to petitboot to set the cpu frequency governor to 'ondemand' - meaning we won't be running the CPUs at full frequency if the machine is sitting idle at petitboot.

Jeremy Kerr (1):
      Add init script to set cpufreq governor

Signed-off-by: Jeremy Kerr <jk@ozlabs.org>

### CODE REVIEW

**Comment by williamspatrick** [comment]
‎Please offer pull request against master-next unless there has been some critical request for this to go into a 1.1.1 release.                                                                                                                                                                                                                                          From: Jeremy KerrSent: Thursday, April 9, 2015 8:20 PMTo: open-power/op-buildReply To: open-power/op-buildSubject: [op-build] buildroot: Update to 8dd7d991 (#134)This change adds an init script to petitboot to set the cpu frequency governor to 'ondemand' - meaning we won't be running the CPUs at full frequency if the machine is sitting idle at petitboot.

Jeremy Kerr (1):
      Add init script to set cpufreq governor

Signed-off-by: Jeremy Kerr jk@ozlabs.org



You can view, comment on, or merge this pull request online at:
  https://github.com/open-power/op-build/pull/134

Commit Summary

  buildroot: Update to 8dd7d991


File Changes

  
    M
    buildroot
    (2)
  


Patch Links:

  https://github.com/open-power/op-build/pull/134.patch
  https://github.com/open-power/op-build/pull/134.diff


—Reply to this email directly or view it on GitHub.

**Comment by ozbenh** [comment]
On Thu, 2015-04-09 at 18:20 -0700, Jeremy Kerr wrote:
> This change adds an init script to petitboot to set the cpu frequency
> governor to 'ondemand' - meaning we won't be running the CPUs at full
> frequency if the machine is sitting idle at petitboot.

Any reason why you didn't make that the default in the pb kernel
config ?

**Comment by jk-ozlabs** [comment]
@ozbenh: nope, that's a much better way to do it. I'll rework and send a pull req to -next.

**Comment by williamspatrick** [comment]
Keep in mind that the kernel config for op-build is actually in op-build itself now and we don't use a defconfig in the kernel tree anymore.

**Pull request closed without merging**
