### PR TITLE
kernel: Move to Linux v4.19.0-openpower1

### PR DESCRIPTION
**Pull request by shenki**
Move to a new upstream kernel release.

The defconfig has been regenerated against 4.19 and the non-default IO
schedulers disabled. No functional changes should result.

Signed-off-by: Joel Stanley <joel@jms.id.au>

### CODE REVIEW

**Comment by shenki** [comment]
retest this please

**Comment by shenki** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by shenki** [comment]
This probably needed a rebase on the CI script update. I've pushed that now.

It's unfortunate that github doesn't record the results of the CI runs :(

**Comment by stewart-ibm** [comment]
retest this please

**Pull request merged**
