### PR TITLE
buildroot: Move to 2017.05 release

### PR DESCRIPTION
**Pull request by shenki**
Signed-off-by: Joel Stanley <joel@jms.id.au>

Fixes https://github.com/open-power/op-build/issues/972

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1124)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
RHEL6.ancient with gcc 4.ancient strikes again!

@pragupta what's the ETA for being able to have the CI build on something remotely recent? Either this has to happen, or somebody needs to step up to maintain a bunch of this code on ancient OS and compiler combinations.

**Comment by shenki** [comment]
A fix for building on ancient GCCs has been merged in.

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch?

**Comment by wghoffa** [comment]
retest this please

**Comment by shenki** [comment]
This is blocked on merging https://github.com/open-power/op-build/pull/1174

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
@shenki Now we appear to get this is HB build on the Ubuntu hosts:

```
shutdown.S: Assembler messages:
shutdown.S:97: Error: operand out of range (10 is not between 0 and 1)
shutdown.S:97: Error: missing operand
shutdown.S:135: Error: operand out of range (10 is not between 0 and 1)
shutdown.S:135: Error: missing operand
shutdown.S:168: Error: operand out of range (3 is not between 0 and 1)
shutdown.S:168: Error: missing operand
```

**Comment by stewart-ibm** [comment]
```
ERROR: PnorUtils::checkSpaceConstraints: Image provided (/tmp/hostboot/jenkins-slave/workspace/op_build_ghprb_trigger_multi-2/CONFIG/firestone/OS/rhel6.4/op-build/output/images/zImage.epapr) has size (15746920) which is greater than allocated space (15728640) for section=BOOTKERNEL.  Aborting!
```

and yet this didn't occur elsewhere nor on the builds on our CI in Canberra.... hrm...

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
Seeing as the automated boot-CI isn't working, I've manually tested this on a couple of platforms, merging.

**Pull request merged**
