### PR TITLE
Update hostboot-binaries and pnor to use the non ECC HCODE image

### PR DESCRIPTION
**Pull request by sannerd**
- This will start using the non ECC p9n.ref_image in preparation
    for moving to op-build compiled SBE code

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/943)

### CODE REVIEW

**Comment by wghoffa** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/op-build/943)*

**Comment by wghoffa** [comment]
LGTM

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/op-build/943#-:-KfRxbMK6vgoij3jKx9s:bb6ywmx)*

**Comment by dcrowell77** [comment]
Is the plan to eventually modify the defconfig files to not have the hdr.bin.ecc name?

**Comment by wghoffa** [comment]
retest this please

**Comment by sannerd** [comment]
@dcrowell77  -- That could be done, but it is more rip up and would require a few more P8/P9 checks in op-build make files.... either for P9 or excluding P8

**Pull request merged**
