### PR TITLE
Revert HCODE to hw012118a.911

### PR DESCRIPTION
**Pull request by wghoffa**
- There has been instability in HB + OPAL causing
    boot hangs. Move back to working level until issues
    can be resolved

### CODE REVIEW

**Comment by Over-enthusiastic** [comment]
@wghoffa Does this revert remove any feature? Do we expect all stop states (stop 0,1,2,4,5 and 11) to work ?

**Comment by stewart-ibm** [comment]
Akshay Adiga <notifications@github.com> writes:
> @wghoffa Does this revert remove any feature? Do we expect all stop
> states (stop 0,1,2,4,5 and 11) to work ?

We only have up to 5 enabled currently.

I think we may lose a special wakeup fix by going back this far? I'm not
sure and it's a bit unclear... I wish the changes for the inits were
public (or, well, *ANYWHERE*).

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by Over-enthusiastic** [comment]
@stewart-ibm Oh! Thanks for the info.

**Comment by wghoffa** [comment]
@Over-enthusiastic - We are hoping to have a fix soon, hoping to sit at this level for only a very short period of time.

**Pull request merged**
