### PR TITLE
Revert "Merge pull request #3283 from wistron-corporation/master_2019…

### PR DESCRIPTION
**Pull request by klauskiwi**
…1108_kernel_partition"

Reverts #3283 that introduced a build-time patch modifying
openpower-pnor layout xml to allocate 24MB for the BOOTKERNEL for the
Mihawk platform.

As discussed in https://github.com/ibm-op-release/op-build/pull/704, we
decided that this hack can live on IBM's downstream product branch for
the time being, opening up the way upstream to more freely work on a
more generalized solution (i.e., Petitboot plugins)

This reverts commit 3aae3fb3cad3e72186a6a3b061509c310bbcc671, reversing
changes made to 458d6c370385ee093947fd8661f71e1f6e0d9afb.

Signed-off-by: Klaus Heinrich Kiwi <klaus@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by klauskiwi** [comment]
@chcyjoy @stewartsmith FYI + comments

**Comment by oohal** [comment]
I don't see any corresponding buildroot config changes so if something is using that space it's going to break building a mihawk pnor in upstream.

I'm not really sure what the point is either. Sure it's a hack, but so long as it's limited to being mihawk only it's not hurting anyone. Usually we drop hacks if they're getting in the way of something, or someone's moved to a better solution, but I'm not seeing either here.

**Comment by klauskiwi** [comment]
That's a great point.
 
Let's leave this now to gather more feedback here before deciding..
 
 -Klaus
 
Klaus Heinrich Kiwi
OPAL Project Lead
Phone: 55-19-2132-6294
E-mail: klausk@br.ibm.com
 
 
----- Original message -----From: oohal <notifications@github.com>To: open-power/op-build <op-build@noreply.github.com>Cc: Klaus Heinrich Kiwi <klausk@br.ibm.com>, Author <author@noreply.github.com>Subject: [EXTERNAL] Re: [open-power/op-build] Revert "Merge pull request #3283 from wistron-corporation/master_2019… (#3551)Date: Wed, Apr 8, 2020 11:35 AM 
 
I don't see any corresponding buildroot config changes so if something is using that space it's going to break building a mihawk pnor in upstream.
I'm not really sure what the point is either. Sure it's a hack, but so long as it's limited to being mihawk only it's not hurting anyone. Usually we drop hacks if they're getting in the way of something, or someone's moved to a better solution, but I'm not seeing either here.

**Comment by klauskiwi** [comment]
Let's keep this where it is for now

**Pull request closed without merging**
