### PR TITLE
HTMGT-OCC: Enable HTMGT compile, Load/Start OCC

### PR DESCRIPTION
**Pull request by baileysh**
RTC:171824

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1088)

### CODE REVIEW

**Comment by wghoffa** [comment]
ok to test

**Comment by e-liner** [comment]
ok to test

**Comment by stewart-ibm** [comment]
@baileysh  this fails to build with a build error in hostboot:
```
htmgt_cfgdata.C: In function ‘void HTMGT::getApssMessageData(uint8_t*, uint64_t&)’:
htmgt_cfgdata.C:992:5: error: ‘ATTR_ADC_CHANNEL_GROUNDS_type’ was not declared in this scope
     ATTR_ADC_CHANNEL_GROUNDS_type ground;
     ^
htmgt_cfgdata.C:993:21: error: ‘ATTR_ADC_CHANNEL_GROUNDS’ was not declared in this scope
     sys->tryGetAttr<ATTR_ADC_CHANNEL_GROUNDS>(ground);
                     ^
htmgt_cfgdata.C:993:47: error: ‘ground’ was not declared in this scope
     sys->tryGetAttr<ATTR_ADC_CHANNEL_GROUNDS>(ground);
                                               ^
make[9]: *** [../../../obj/modules/htmgt/htmgt_cfgdata.o] Error 1
make[8]: *** [_BUILD/PASSES/CODE/BODY] Error 2
make[7]: *** [_BUILD/SUBDIR/CODE/htmgt] Error 2
make[7]: *** Waiting for unfinished jobs....
```

**Comment by stewart-ibm** [comment]
Merged as part of https://github.com/open-power/op-build/pull/1096 which fixes up the needed skiboot bits too.

**Pull request merged**
