### PR TITLE
Latest SBE Image release

### PR DESCRIPTION
**Pull request by rajadas2**
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1048)

### CODE REVIEW

**Comment by sgupta2m** [comment]
ok to test

**Comment by sgupta2m** [comment]
@sannerd @wghoffa can you please review this

**Comment by sannerd** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/op-build/1048)*

**Comment by sgupta2m** [comment]
@williamspatrick can we please merge this

**Comment by pragupta** [comment]
@sgupta2m Do we want the sbe versions to also be updated automatically as part of the nightly op-build pull request?

**Comment by sgupta2m** [comment]
You are life saver @pragupta :) .. yes please

**Pull request merged**
