### PR TITLE
Witherspoon: Enable Physical Presence Detection and Key Clear functio…

### PR DESCRIPTION
**Pull request by mabaiocchi**
This commit updates the hostboot witherspoon.config file to enable
the support via CONFIG variables for Physical Presence Detection and
Key Clear Request.

Signed-off-by: Mike Baiocchi <mbaiocch@us.ibm.com>

### CODE REVIEW

**Comment by mabaiocchi** [comment]
Here is the pull request to add support for Physical Presence and Key Clear.  It looksl ike the CI tests are still running.
@bofferdn

**Comment by mabaiocchi** [comment]
@cjengel @nasastry @naynjain

**Comment by mabaiocchi** [comment]
@naynajain

**Comment by nasastry** [comment]
Looks Good to me ... Tested with the config options. And could see Physical Presence After flash.
Thanks!!

**Comment by mabaiocchi** [comment]
retest this please

**Comment by mabaiocchi** [comment]
@dcrowell77, we could use an outside pair of eyes.  Can you please review and merge this - thanks!

**Pull request merged**
