### PR TITLE
Set access to HBB and HBI partitions to Read Only

### PR DESCRIPTION
**Pull request by popfuture**
This change removes a revert of the "Mark Read Only Partitions as
Such" change and updates the pnor makefiles to ensure HBB and HBI
partitions are marked read only at the pnor level.

### CODE REVIEW

**Comment by wghoffa** [comment]
retest this please

**Comment by wghoffa** [comment]
retest this please

**Comment by wghoffa** [comment]
retest this please

**Comment by wghoffa** [comment]
retest this please

**Comment by wghoffa** [comment]
retest this please

**Comment by popfuture** [comment]
retest this please

**Pull request merged**
