### PR TITLE
linux: Bump to 5.10.194

### PR DESCRIPTION
**Pull request by runlevel5**
## NOTE

The https://github.com/open-power/op-build/pull/5629 must be merged first!

No error when building `blackbird` firmware on Ubuntu 22.04 ppc64le

### CODE REVIEW

**Comment by dcrowell77** [comment]
ok to test

**Comment by runlevel5** [comment]
@dcrowell77 I will fail because this PR depends on the https://github.com/open-power/op-build/pull/5629

To aid developers to verify their work locally, do you have the specs/IaC how those 2 CICD workers are setup? It's so hard to troubleshoot failed build without being able to see the error output and insights on what are installed on those boxes

**Comment by dcrowell77** [comment]
See https://github.com/open-power/op-build/tree/master/ci/Dockerfile

**Comment by IlyaSmirnov91** [comment]
This probably needs a rebase now that #5629 has been merged.

**Comment by runlevel5** [comment]
@IlyaSmirnov91 I will rebase it and bump the kernel to 5.10.194

**Comment by runlevel5** [comment]
@IlyaSmirnov91 rebased

**Comment by IlyaSmirnov91** [comment]
HW CI looks good, and the Ubuntu compilation actually passed, but it's stuck on archiving the job artifacts, so this PR is mergeable if it's ready (let me know).

**Comment by runlevel5** [comment]
@IlyaSmirnov91 it is ready to get merged

**Pull request merged**
