### PR TITLE
Fixed PATH when building PNOR squashfs to use correct pflash binary

### PR DESCRIPTION
**Pull request by charleshofer**
Signed-off-by: Charles P. Hofer <charles.hofer@ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1370)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch for testing?

**Comment by charleshofer** [comment]
That's a big mistake. Fixed it. Thanks for catching it.

**Comment by wghoffa** [comment]
ok to test

**Comment by e-liner** [comment]
ok to test

**Pull request merged**
