### PR TITLE
Update Raptor Blackbird support

### PR DESCRIPTION
**Pull request by stewartsmith**
Notable changes:
- bump to latest Raptor 2.00 machine-xml
- Support IPL observer.

Skiboot patch has been sent upstream - https://patchwork.ozlabs.org/patch/1268510/
Hostboot rvpd patch has been sent upstream

and I'm doing a build+test of this final tree now (will be ~12-24 hours until I see it as I really should sleep rather than wait for op-build). But submitting this to have CI and feedback at least.

### CODE REVIEW

**Comment by stewartsmith** [comment]
> and I'm doing a build+test of this final tree now (will be ~12-24 hours until I see it as I really should sleep rather than wait for op-build). But submitting this to have CI and feedback at least.

Update: it seems to work fine.

**Comment by klauskiwi** [comment]
I think we now have pieces that have been merged in Skiboot, perhaps other places? Would you like to rebase this so we can take a look?

**Comment by stewartsmith** [comment]
I'm having some fun as `host-localedef` now fails to build on Fedora 32, going to try and attack that this weekend.

**Comment by stewartsmith** [comment]
Superseded by https://github.com/open-power/op-build/pull/3623

**Pull request closed without merging**
