### PR TITLE
Add support for IMA (In Memory Accumulation) catalog pnor partiton

### PR DESCRIPTION
**Pull request by ploetzma**
Note - this will fail and hashes will need to be updated once https://github.com/open-power/pnor/pull/50/ and https://github.com/open-power/hostboot-binaries/pull/9 are in.

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/635)

### CODE REVIEW

**Comment by williamspatrick** [comment]
Can we get a comment on what "IMA catalog" is?

**Comment by dcrowell77** [comment]
IMA = In Memory Accumulation - This is related to the 24x7 function that collects hardware information for performance optimization.

**Comment by shenki** [comment]
That should go in the commit message and the `openpower/package/openpower-pnor/Config.in` help description @dcrowell77 / @ploetzma

**Comment by ploetzma** [comment]
@shenki Agreed, will add when I need to rebase for the commit hash update

**Pull request merged**
