### PR TITLE
Add hostboot submodule update

### PR DESCRIPTION
**Pull request by strange671**
Hostboot now includes libmctp, which is imported as a git submodule. Thus, in order to build Hostboot with MCTP (Management Component Transport Protocol) support, we must clone the git tree and its sub-modules.

Signed-off-by: Jet Li <Jet.Li@ibm.com>

### CODE REVIEW

**Comment by stewartsmith** [comment]
I don’t understand the reasoning from the text in the PR. Can you elaborate?

**Comment by strange671** [comment]
In Hostboot that has submodule config, but it will not also download while to build. So I want to make a global change when submodule exists that it will clone.

**Comment by stewartsmith** [comment]
That doesn't make anything clearer.

From peering into the Hostboot repo, how about this:


"Hostboot now includes libmctp, which is imported as a git submodule. Thus, in order to build Hostboot with MCTP (Management Component Transport Protocol) support, we must clone the git tree and its sub-modules."

-- 
  Stewart Smith
  stewart@flamingspork.com

**Comment by bofferdn** [comment]
The git submodule makefile directive won't work here since it requires the git site method, which is not configured for this package.

**Comment by strange671** [comment]
Many thanks, I've edited it. For site_method that does not git, I'll drop this PR.

**Pull request closed without merging**
