### PR TITLE
Add: add files for mowgli platform

### PR DESCRIPTION
**Pull request by LuluTHSu**
This is the initial version.

Signed-off-by: LuluTHSu <Lulu_Su@wistron.com>

### CODE REVIEW

**Comment by klauskiwi** [comment]
I built the mowgli_defconfig as proposed and flashed (' open-power-mowgli-v2.4-1005-g8255b762') on mowgli09 which was made available for me (bmc level is '0.0.9').

The system initially looped through multiple istep1 to istep 5.2 cycles, but it was stalling on 'SBE starting Hostboot' and apparently the watchdog ('org.open_power.Host.Boot.Error.WatchdogTimedOut') was recycling it. Finally, it checkstopped ('org.open_power.Host.Boot.Error.Checkstop') but without any additional info on the web interface aside from '_PID=3797'.

I also noted that the skiboot patch mentioned (https://lists.ozlabs.org/pipermail/skiboot/2020-September/017227.html) is not being pulled (not even as a build-time patch for op-build) but that wouldn't matter I think as we're failing to reach even Hostboot.

I'll try to point Hostboot / SBE etc to the OP940 levels and try again, but I can't merge the above patch upstream if it hasn't been demonstrated to work.

**Comment by LuluTHSu** [comment]
The reason for stopping in step 5.2 is because the secure boot mode is turned on, and you must either use a production key signed driver or engage the security jumper and transition it to imprint.

**Comment by LuluTHSu** [comment]
> I built the mowgli_defconfig as proposed and flashed (' open-power-mowgli-v2.4-1005-g8255b762') on mowgli09 which was made available for me (bmc level is '0.0.9').
> 
> The system initially looped through multiple istep1 to istep 5.2 cycles, but it was stalling on 'SBE starting Hostboot' and apparently the watchdog ('org.open_power.Host.Boot.Error.WatchdogTimedOut') was recycling it. Finally, it checkstopped ('org.open_power.Host.Boot.Error.Checkstop') but without any additional info on the web interface aside from '_PID=3797'.
> 
> I also noted that the skiboot patch mentioned (https://lists.ozlabs.org/pipermail/skiboot/2020-September/017227.html) is not being pulled (not even as a build-time patch for op-build) but that wouldn't matter I think as we're failing to reach even Hostboot.
> 
> I'll try to point Hostboot / SBE etc to the OP940 levels and try again, but I can't merge the above patch upstream if it hasn't been demonstrated to work.

The reason for stopping in istep 5.2 is because the secure boot mode is turned on, and you must either use a production key signed driver or engage the security jumper and transition it to imprint.

**Comment by LuluTHSu** [comment]
Hi @klauskiwi ,
Mowgli has the FW release plan in a week.
We hope this commit could be merged as soon as possible.
If there is any problem with the defconfig, please feel free to contact me.
Thank you very much.

**Comment by klauskiwi** [comment]
Hi Lulu and Claire,

 I was finally able to get past the iStep 5.2 issue with the PNOR proposed here, but something is still missing apparently:
```
^M--== Welcome to SBE - CommitId[0xd30bd988] ==--
^Mistep 3.19
^Mistep 3.20
^Mistep 3.21
^Mistep 3.22
^Mistep 4.1
^Mistep 4.2
^Mistep 4.3
^Mistep 4.4
^Mistep 4.5
^Mistep 4.6
^Mistep 4.7
^Mistep 4.8
^Mistep 4.9
^Mistep 4.10
^Mistep 4.11
^Mistep 4.12
^Mistep 4.13
^Mistep 4.14
^Mistep 4.15
^Mistep 4.16
^Mistep 4.17
^Mistep 4.18
^Mistep 4.19
^Mistep 4.20
^Mistep 4.21
^Mistep 4.22
^Mistep 4.23
^Mistep 4.24
^Mistep 4.25
^Mistep 4.26
^Mistep 4.27
^Mistep 4.28
^Mistep 4.29
^Mistep 4.30
^Mistep 4.31
^Mistep 4.32
^Mistep 4.33
^Mistep 4.34
^Mistep 5.1
^Mistep 5.2
^MSBE starting hostboot
^M

--== Welcome to Hostboot hostboot-9385359/hbicore.bin ==--

  5.35695|secure|SecureROM valid - enabling functionality
  5.45796|secure|Booting in non-secure mode (minimum secure version=0x00)
  7.63119|Booting from SBE side 0 on master proc=00050000
  7.66859|ISTEP  6. 5 - host_init_fsi
  7.88807|ISTEP  6. 6 - host_set_ipl_parms
  7.95152|ISTEP  6. 7 - host_discover_targets
  9.49887|HWAS|PRESENT> DIMM[03]=A0A0000000000000
  9.49888|HWAS|PRESENT> Proc[05]=8000000000000000
  9.49889|HWAS|PRESENT> Core[07]=F000140000000000
  9.95393|ISTEP  6. 8 - host_update_master_tpm
 10.09710|SECURE|Security Access Bit> 0x0000000000000000
 10.09711|SECURE|Secure Mode Disable (via Jumper)> 0x8000000000000000
 10.09767|ISTEP  6. 9 - host_gard
 10.18079|HWAS|FUNCTIONAL> DIMM[03]=A0A0000000000000
 10.18080|HWAS|FUNCTIONAL> Proc[05]=8000000000000000
 10.18081|HWAS|FUNCTIONAL> Core[07]=F000140000000000
 10.18350|ISTEP  6.11 - host_start_occ_xstop_handler
 11.06560|ISTEP  6.12 - host_voltage_config
 11.19648|ISTEP  7. 1 - mss_attr_cleanup
 11.80016|ISTEP  7. 2 - mss_volt
 11.99535|ISTEP  7. 3 - mss_freq
 12.45676|ISTEP  7. 4 - mss_eff_config
 13.10994|ISTEP  7. 5 - mss_attr_update
 13.16327|ISTEP  8. 1 - host_slave_sbe_config
 13.28054|ISTEP  8. 2 - host_setup_sbe
 13.28153|ISTEP  8. 3 - host_cbs_start
 13.28262|ISTEP  8. 4 - proc_check_slave_sbe_seeprom_complete
 13.33140|ISTEP  8. 5 - host_attnlisten_proc
 13.33303|ISTEP  8. 6 - host_p9_fbc_eff_config
 13.33690|ISTEP  8. 7 - host_p9_eff_config_links
 13.38521|ISTEP  8. 8 - proc_attr_update
 13.38715|ISTEP  8. 9 - proc_chiplet_fabric_scominit
 13.40527|ISTEP  8.10 - proc_xbus_scominit
 13.41928|ISTEP  8.11 - proc_xbus_enable_ridi
 13.43943|ISTEP  8.12 - host_set_voltages
 13.46011|ISTEP  9. 1 - fabric_erepair
 13.53885|ISTEP  9. 2 - fabric_io_dccal
 13.54212|ISTEP  9. 3 - fabric_pre_trainadv
 13.54650|ISTEP  9. 4 - fabric_io_run_training
 13.54795|ISTEP  9. 5 - fabric_post_trainadv
 13.54938|ISTEP  9. 6 - proc_smp_link_layer
 13.55354|ISTEP  9. 7 - proc_fab_iovalid
 13.80137|ISTEP  9. 8 - host_fbc_eff_config_aggregate
 13.80460|ISTEP 10. 1 - proc_build_smp
 14.08726|ISTEP 10. 2 - host_slave_sbe_update
 15.38920|ISTEP 10. 4 - proc_cen_ref_clk_enable
 15.44686|ISTEP 10. 5 - proc_enable_osclite
 15.44927|ISTEP 10. 6 - proc_chiplet_scominit
 15.58342|ISTEP 10. 7 - proc_abus_scominit
 15.61733|ISTEP 10. 8 - proc_obus_scominit
 15.61890|ISTEP 10. 9 - proc_npu_scominit
 15.64141|ISTEP 10.10 - proc_pcie_scominit
 15.75141|ISTEP 10.11 - proc_scomoverride_chiplets
 15.75374|ISTEP 10.12 - proc_chiplet_enable_ridi
 15.76651|ISTEP 10.13 - host_rng_bist
 15.78885|ISTEP 10.14 - host_update_redundant_tpm
 15.79409|ISTEP 11. 1 - host_prd_hwreconfig
 15.99643|ISTEP 11. 2 - cen_tp_chiplet_init1
 15.99944|ISTEP 11. 3 - cen_pll_initf
 16.00240|ISTEP 11. 4 - cen_pll_setup
 16.02400|ISTEP 11. 5 - cen_tp_chiplet_init2
 16.02785|ISTEP 11. 6 - cen_tp_arrayinit
 16.03673|ISTEP 11. 7 - cen_tp_chiplet_init3
 16.03975|ISTEP 11. 8 - cen_chiplet_init
 16.04275|ISTEP 11. 9 - cen_arrayinit
 16.04787|ISTEP 11.10 - cen_initf
 16.05077|ISTEP 11.11 - cen_do_manual_inits
 16.05381|ISTEP 11.12 - cen_startclocks
 16.05678|ISTEP 11.13 - cen_scominits
 16.05989|ISTEP 12. 1 - mss_getecid
 16.56948|ISTEP 12. 2 - dmi_attr_update
 16.57250|ISTEP 12. 3 - proc_dmi_scominit
 16.60154|ISTEP 12. 4 - cen_dmi_scominit
 16.60455|ISTEP 12. 5 - dmi_erepair
 16.64538|ISTEP 12. 6 - dmi_io_dccal
 16.65023|ISTEP 12. 7 - dmi_pre_trainadv
 16.65711|ISTEP 12. 8 - dmi_io_run_training
 16.72984|ISTEP 12. 9 - dmi_post_trainadv
 16.73528|ISTEP 12.10 - proc_cen_framelock
 16.73869|ISTEP 12.11 - host_startprd_dmi
 16.74572|ISTEP 12.12 - host_attnlisten_memb
 16.74872|ISTEP 12.13 - cen_set_inband_addr
 16.75173|ISTEP 13. 1 - host_disable_memvolt
 16.89128|ISTEP 13. 2 - mem_pll_reset
 16.94239|ISTEP 13. 3 - mem_pll_initf
 16.98892|ISTEP 13. 4 - mem_pll_setup
 17.00251|ISTEP 13. 6 - mem_startclocks
 17.05041|ISTEP 13. 7 - host_enable_memvolt
 17.06640|ISTEP 13. 8 - mss_scominit
 17.73987|ISTEP 13. 9 - mss_ddr_phy_reset
 17.82561|ISTEP 13.10 - mss_draminit
 17.91994|ISTEP 13.11 - mss_draminit_training
 18.23654|ISTEP 13.12 - mss_draminit_trainadv
 18.29005|ISTEP 13.13 - mss_draminit_mc
 18.33972|ISTEP 14. 1 - mss_memdiag
 21.88734|ISTEP 14. 2 - mss_thermal_init
 21.94290|ISTEP 14. 3 - proc_pcie_config
 21.99265|ISTEP 14. 4 - mss_power_cleanup
 21.99521|ISTEP 14. 5 - proc_setup_bars
 22.03278|ISTEP 14. 6 - proc_htm_setup
 22.06479|ISTEP 14. 7 - proc_exit_cache_contained
 22.11667|ISTEP 15. 1 - host_build_stop_image
 23.41572|ISTEP 15. 2 - proc_set_pba_homer_bar
 23.43656|ISTEP 15. 3 - host_establish_ex_chiplet
 23.45638|ISTEP 15. 4 - host_start_stop_engine
 23.48982|ISTEP 16. 1 - host_activate_master
 24.64333|ISTEP 16. 2 - host_activate_slave_cores
 24.75772|ISTEP 16. 3 - host_secure_rng
 24.73578|ISTEP 16. 4 - mss_scrub
 24.79616|ISTEP 16. 5 - host_load_io_ppe
 24.78252|ISTEP 16. 6 - host_ipl_complete
 24.90713|ISTEP 18.11 - proc_tod_setup
 25.06778|ISTEP 18.12 - proc_tod_init
 25.07052|ISTEP 20. 1 - host_load_payload
 25.44214|ISTEP 20. 2 - host_load_hdat
 26.28121|ISTEP 21. 1 - host_runtime_setup
 30.52876|htmgt|OCCs are now running in ACTIVE state
 34.23084|ISTEP 21. 2 - host_verify_hdat
 34.29855|ISTEP 21. 3 - host_start_payload
[   34.293322706,5] OPAL skiboot-v6.6-85-gabe4c4799 starting...
[   34.293326680,7] initial console log level: memory 7, driver 5
[   34.293328736,6] CPU: P9 generation processor (max 4 threads/core)
[   34.293330471,7] CPU: Boot CPU PIR is 0x0054 PVR is 0x004e1201
[   34.293332981,7] OPAL table: 0x3012f740 .. 0x3012fd00, branch table: 0x300e0000
[   34.293336196,7] Assigning physical memory map table for nimbus
[   34.293338672,7] Parsing HDAT...
[   34.293339951,7] SPIRA-S found.
[   34.293342711,6] BMC #0: HW version 3, SW version 2, chip DD1.0
[   34.293369552,4] SENSORS: Duplicate sensor ID : 0
[   34.293371234,4] SENSORS: Duplicate sensor ID : 0
[   34.293378918,4] SENSORS: Duplicate sensor ID : 0
[   34.293400966,4] SENSORS: Duplicate sensor ID : b
[   34.293428844,6] SP Family is ibm,ast2500,openbmc
[   34.293434416,7] LPC: IOPATH chip id = 0
[   34.293435668,7] LPC: FW BAR       = f0000000
[   34.293437191,7] LPC: MEM BAR      = e0000000
[   34.293438657,7] LPC: IO BAR       = d0010000
[   34.293440069,7] LPC: Internal BAR = c0012000
[   34.293451466,7] LPC UART: base addr = 3f8 (3f8) size = 1 clk = 1843200, baud = 115200
[   34.293454145,7] LPC: BT [0, 0] sms_int: 0, bmc_int: 0
[   34.294586964,5] HDAT I2C: found e3p0 - unknown@19 dp:ff (ff:)
[   34.294684354,5] HDAT I2C: found e3p1 - unknown@1a dp:ff (ff:)
[   34.294740488,5] HDAT I2C: found e3p1 - unknown@1b dp:ff (ff:)
[   34.294799404,5] HDAT I2C: found e3p0 - unknown@18 dp:ff (ff:)
[   34.295534503,5] CHIP: Chip ID 0000 type: P9N DD2.11
[   34.295857785,3] GENERIC BMC PLATFORM: **GUESSING** that there's *maybe* a BMC we can talk to.
[   34.295940727,3] THIS IS ****UNSUPPORTED****, BRINGUP USE ONLY.
[   34.296036043,5] PLAT: Detected generic platform
[   34.296081923,5] PLAT: Detected BMC platform generic
[   34.304038999,5] CPU: All 24 processors called in...
[   34.423024507,3] BMC-GUESSWORK: Here be dragons with a taste for human flesh
[   34.423104204,7] LPC: Routing irq 10, policy: 0 (r=1)
[   34.423105434,7] LPC: SerIRQ 10 using route 0 targetted at OPAL
[   34.443730571,3] NVRAM: Error -6 retrieving nvram info
[   34.443816405,2] NVRAM: Possible wait before nvram_init()!
[   34.443857687,2] NVRAM: Failed to load
[   34.443899673,2] NVRAM: Possible wait before nvram_init()!
[   34.443943276,2] NVRAM: Failed to load
[   34.443969465,2] NVRAM: Possible wait before nvram_init()!
[   34.444010672,2] NVRAM: Failed to load
[   34.444044796,2] NVRAM: Possible wait before nvram_init()!
[   34.444088552,2] NVRAM: Failed to load
[   34.444122074,4] FLASH: Can't load resource id:4. No system flash found
[   34.444123746,6] OPAL: Using OPAL UART console
[   34.444126593,7] NVRAM: Query for 'uart-con-policy' must wait for NVRAM to load
[   34.444128020,2] NVRAM: Possible wait before nvram_init()!
[   34.444128964,2] NVRAM: Failed to load
[   34.444132643,7] LPC: Routing irq 4, policy: 0 (r=1)
[   34.444133726,7] LPC: SerIRQ 4 using route 1 targetted at OPAL
[   34.444136861,7] SLW: Init chip 0x0
[   34.444148754,6] SLW: Configuring self-restore for HRMOR
[   34.444153448,7] CPU idle state device tree init
[   34.444155139,7] NVRAM: Query for 'opal-stop-state-disable-mask' must wait for NVRAM to load
[   34.444156865,2] NVRAM: Possible wait before nvram_init()!
[   34.444157851,2] NVRAM: Failed to load
[   34.444158569,7] NVRAM stop disable mask: 0
[   34.444159358,6] SLW: Enabling: stop0_lite
[   34.444160164,6] SLW: Enabling: stop0
[   34.444160865,6] SLW: Enabling: stop1
[   34.444161684,6] SLW: Enabling: stop2
[   34.444164900,7] OCC: Chip 00 Data (0000000ffd8e2000) = 01900150481e1e00
[   34.444166433,7] OCC: Chip 00 Dynamic Data (0000000ffd8e2b80) = 0300000000000001
[   34.444168037,5] OCC: All Chip Rdy after 0 ms
[   34.444181951,7] OCC: CPU pstate state device tree init
[   34.444182881,7] OCC: Chip 00 :Data (       ffd8e2000) =  1900150481e1e00                0
[   34.444184851,7] OCC: Version 90 Min 80 Nom 72 Max 30 Nr States 51
[   34.444193642,7] NVRAM: Query for 'pci-eeh-verbose' must wait for NVRAM to load
[   34.444195028,2] NVRAM: Possible wait before nvram_init()!
[   34.444196133,2] NVRAM: Failed to load
[   34.444196759,7] NVRAM: Query for 'pcie-max-link-speed' must wait for NVRAM to load
[   34.444198221,2] NVRAM: Possible wait before nvram_init()!
[   34.444199211,2] NVRAM: Failed to load
[   34.444199956,7] NVRAM: Query for 'pci-tracing' must wait for NVRAM to load
[   34.444201062,2] NVRAM: Possible wait before nvram_init()!
[   34.444202034,2] NVRAM: Failed to load
[   34.444231796,6] CAPI: Preloading ucode 201d1
[   34.444232882,7] FLASH: Queueing preload of 2/201d1
[   34.444234121,7] FLASH: Queueing preload of 0/0
[   34.444235148,7] FLASH: Queueing preload of 1/0
[   34.445561988,4] FLASH: Can't load resource id:3. No system flash found
[   34.445608153,4] FLASH: Can't load resource id:2. No system flash found
[   34.445649912,4] FLASH: Can't load resource id:0. No system flash found
[   34.445689370,4] FLASH: Can't load resource id:1. No system flash found
[   34.448124658,3] IMC: IMC Catalog load failed
[   34.448262790,2] NVRAM: Possible wait before nvram_init()!
[   34.448311446,2] NVRAM: Failed to load
[   34.448343226,2] NVRAM: Possible wait before nvram_init()!
[   34.448401377,2] NVRAM: Failed to load
[   34.448427163,2] NVRAM: Possible wait before nvram_init()!
[   34.448458178,2] NVRAM: Failed to load
[   34.452000883,3] CAPP: Error loading ucode lid. index=201d1
[   34.465503207,5] PCI: Resetting PHBs and training links...
[   36.506590856,5] PCI: Probing slots...
[   37.050984504,5] PCI Summary:
[   37.051028697,5] PHB#0000:00:00.0 [ROOT] 1014 04c1 R:00 C:060400 B:00..00
[   37.051102803,5] PHB#0001:00:00.0 [ROOT] 1014 04c1 R:00 C:060400 B:01..01
[   37.051168156,5] PHB#0001:01:00.0 [EP  ] 9005 028d R:01 C:010700 (           sas) LOC_CODE=UOPWR.-Node0
[   37.051249489,5] PHB#0002:00:00.0 [ROOT] 1014 04c1 R:00 C:060400 B:01..02
[   37.051296092,5] PHB#0002:01:00.0 [ETOX] 1a03 1150 R:04 C:060400 B:02..02 LOC_CODE=UOPWR.-Node0
[   37.051371411,5] PHB#0002:02:00.0 [PCID] 1a03 2000 R:41 C:030000 (           vga) LOC_CODE=UOPWR.-Node0
[   37.051450764,5] PHB#0003:00:00.0 [ROOT] 1014 04c1 R:00 C:060400 B:01..01
[   37.051506956,5] PHB#0003:01:00.0 [EP  ] 14e4 1657 R:01 C:020000 (      ethernet) LOC_CODE=UOPWR.-Node0
[   37.051566310,5] PHB#0003:01:00.1 [EP  ] 14e4 1657 R:01 C:020000 (      ethernet) LOC_CODE=UOPWR.-Node0
[   37.051627863,5] PHB#0003:01:00.2 [EP  ] 14e4 1657 R:01 C:020000 (      ethernet) LOC_CODE=UOPWR.-Node0
[   37.051695086,5] PHB#0003:01:00.3 [EP  ] 14e4 1657 R:01 C:020000 (      ethernet) LOC_CODE=UOPWR.-Node0
[   37.051769779,5] PHB#0004:00:00.0 [ROOT] 1014 04c1 R:00 C:060400 B:01..01
[   37.051825896,5] PHB#0004:01:00.0 [EP  ] 104c 8241 R:02 C:0c0330 (      usb-xhci) LOC_CODE=UOPWR.-Node0
[   37.051887332,4] FLASH: Failed to load VERSION data
[   37.055486611,5] INIT: Waiting for kernel...
[   37.055543335,5] INIT: platform wait for kernel load failed
[   37.055583018,5] INIT: Assuming kernel at 0x20000000
[   37.055616428,3] INIT: ELF header not found. Assuming raw binary.
[   37.055665657,2] NVRAM: Possible wait before nvram_init()!
[   37.055877948,2] NVRAM: Possible wait before nvram_init()!
[   37.055936759,2] NVRAM: Failed to load
[   37.065138101,0] FATAL: Kernel is zeros, can't execute!
[   37.065212732,3] ***********************************************
[   37.065248868,3] < assert failed at core/init.c:619 >
[   37.065279921,3]     .
[   37.065295764,3]      .
[   37.065310443,3]       .
[   37.065345112,3]         OO__)
[   37.065373826,3]        <"__/
[   37.065409714,3]         ^ ^
[   37.065448805,3] Fatal TRAP at 00000000300226b8   .load_and_boot_kernel+0xb88  MSR 9000000000021002
[   37.065524475,3] CFAR : 000000003003c404 MSR  : 9000000000021002
[   37.065575063,3] SRR0 : 00000000300226b8 SRR1 : 9000000000021002
[   37.065612085,3] HSRR0: 0000000030020024 HSRR1: 9000000000001000
[   37.065647086,3] DSISR: 40000000         DAR  : 0000000201844000
[   37.065684259,3] LR   : 00000000300226a8 CTR  : 000000003004b01c
[   37.065731307,3] CR   : 20002202         XER  : 00000000
[   37.065782686,3] GPR00: 00000000300226a8 GPR16: 0000000031eb0000
[   37.065834523,3] GPR01: 0000000031eb3a40 GPR17: 0000000030003158
[   37.065873645,3] GPR02: 0000000030137700 GPR18: 0000000000000000
[   37.065911772,3] GPR03: 000000000000003b GPR19: 0000000000000000
[   37.065950466,3] GPR04: 0000000030400018 GPR20: 0000000000000000
[   37.065985668,3] GPR05: 000000000000000a GPR21: 0000000000000000
[   37.066035345,3] GPR06: 0000000031eb0060 GPR22: 0000000000000000
[   37.066088856,3] GPR07: 0000000031eb0060 GPR23: 00000000300fe6a4
[   37.066131816,3] GPR08: 0000000000000000 GPR24: 00000000300e1100
[   37.066172798,3] GPR09: 0000000000000000 GPR25: 00000000300e06c7
[   37.066213609,3] GPR10: 0000000031eb0000 GPR26: 000000003040cd78
[   37.066248568,3] GPR11: 0000000000000000 GPR27: 0000000000000000
[   37.066285927,3] GPR12: 0000000040002202 GPR28: 0000000000000000
[   37.066326680,3] GPR13: 0000000000156008 GPR29: 8000000fffffffff
[   37.066369993,3] GPR14: 0000000000000000 GPR30: 000000003040cd70
[   37.066461481,3] GPR15: 0000000000000000 GPR31: 000000003040cd80
CPU 0054 Backtrace:
 S: 0000000031eb3d50 R: 00000000300226a8   .load_and_boot_kernel+0xb78
 S: 0000000031eb3e30 R: 0000000030023320   .main_cpu_entry+0x910
 S: 0000000031eb3f00 R: 00000000300031b8   boot_entry+0x1b0
 --- OPAL boot ---
```

Is it possible that, because we're missing the Skiboot patches that recognize Mowgli as proper platform, that the generic BMC code is not able to handle loading the Flash contents somehow?

Can you look into it and re-submit?

**Comment by klauskiwi** [comment]
by adding the skiboot changes as a build-time patch (https://lists.ozlabs.org/pipermail/skiboot/2020-September/017227.html) and also using OP940 as a base, I was able to flash the PNOR and do a few op-test runs.

See below for the failures:
```
======================================================================
ERROR [602.317s]: runTest (testcases.SystemLogin.ExampleRestAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/klausk/secureboot/op-test/testcases/SystemLogin.py", line 142, in runTest
    self.cv_SYSTEM.sys_sensors()
  File "/home/klausk/secureboot/op-test/common/OpTestSystem.py", line 1490, in sys_sensors
    self.rest.sensors()
  File "/home/klausk/secureboot/op-test/common/OpTestOpenBMC.py", line 82, in sensors
    r = self.conf.util_bmc_server.get(uri=uri, minutes=minutes)
  File "/home/klausk/secureboot/op-test/common/OpTestUtil.py", line 1973, in get
    r = self.loop_it(**kwargs)
  File "/home/klausk/secureboot/op-test/common/OpTestUtil.py", line 2016, in loop_it
    kwargs['files'], kwargs['minutes']))
common.Exceptions.HTTPCheck: Something happened with the HTTP Server.  Review the following for more details
Message="HTTP "get" problem, we timed out trying URL=https://mowgli06.aus.stglabs.ibm.com/xyz/openbmc_project/sensors/enumerate PARAMS=None DATA=None JSON=None Files=None, we waited 10 minutes, check the debug log for more details"

2020-09-29 10:30:07,414:op-test:<module>:INFO:Exit with Result errors="1" and failures="0"
2020-09-29 10:30:11,441:op-test.common.OpTestUtil:cleanup:INFO:OpTestSystem Starting to Gather BMC logs
```

```
======================================================================
ERROR [1.001s]: test_fru_print (testcases.OpTestInbandIPMI.SkirootFullInbandIPMI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/klausk/secureboot/op-test/testcases/OpTestInbandIPMI.py", line 298, in test_fru_print
    self.run_ipmi_cmds(c, [self.ipmi_method + BMC_CONST.IPMI_FRU_PRINT])
  File "/home/klausk/secureboot/op-test/testcases/OpTestInbandIPMI.py", line 108, in run_ipmi_cmds
    raise cf
  File "/home/klausk/secureboot/op-test/testcases/OpTestInbandIPMI.py", line 99, in run_ipmi_cmds
    c.run_command(cmd, timeout=120)
  File "/home/klausk/secureboot/op-test/common/OpTestSSH.py", line 225, in run_command
    return self.util.run_command(self, command, timeout, retry)
  File "/home/klausk/secureboot/op-test/common/OpTestUtil.py", line 1616, in run_command
    raise cf
  File "/home/klausk/secureboot/op-test/common/OpTestUtil.py", line 1611, in run_command
    output = self.try_command(term_obj, command, timeout)
  File "/home/klausk/secureboot/op-test/common/OpTestUtil.py", line 1686, in try_command
    raise CommandFailed(command, res, echo_rc)
common.Exceptions.CommandFailed: Command 'ipmitool fru print' exited with '1'.
Output
['FRU Device Description : Builtin FRU Device (ID 0)', 'FRU Device Description : cpu (ID 1)', ' Board Mfg Date        : Mon Jan  1 00:00:00 1996', ' Board Mfg             : IBM', ' Board Product         : PROCESSOR MODULE', ' Board Serial          : YA1935362669', ' Board Part Number     : 02WP434', '', 'FRU Device Description : system (ID 3)', ' Chassis Type          : Unspecified', ' Chassis Part Number   : 7063-CR2', ' Chassis Serial        :          1000006', ' Board Mfg Date        : Mon Jan  1 00:00:00 1996', ' Board Mfg             : IBM', ' Board Product         : SYSTEM PLANAR', ' Board Serial          : YL30UF086003    ', ' Board Part Number     : 02WF440         ', '', 'FRU Device Description : dimm0 (ID 4)', ' Product Manufacturer  : SK Hynix', ' Product Name          : DDR4-2666 16GiB 64-bit ECC RDIM', ' Product Part Number   : HMA82GR7DJR4N-VK    ', ' Product Version       : 00', ' Product Serial        : 342d94e3', '', 'FRU Device Description : dimm1 (ID 5)', ' Product Manufacturer  : SK Hynix', ' Product Name          : DDR4-2666 16GiB 64-bit ECC RDIM', ' Product Part Number   : HMA82GR7DJR4N-VK    ', ' Product Version       : 00', ' Product Serial        : 342d94bf', '', 'FRU Device Description : dimm2 (ID 6)', ' Product Manufacturer  : SK Hynix', ' Product Name          : DDR4-2666 16GiB 64-bit ECC RDIM', ' Product Part Number   : HMA82GR7DJR4N-VK    ', ' Product Version       : 00', ' Product Serial        : 342d950d', '', 'FRU Device Description : dimm3 (ID 7)', ' Product Manufacturer  : SK Hynix', ' Product Name          : DDR4-2666 16GiB 64-bit ECC RDIM', ' Product Part Number   : HMA82GR7DJR4N-VK    ', ' Product Version       : 00', ' Product Serial        : 342d952b', '', 'FRU Device Description : tpm (ID 24)', ' Device not present (Unspecified error)', '']

```

It would be good to have those sorted out before merging, but something we can probably fix after as well. The one thing we need is the skiboot support merged

**Comment by LuluTHSu** [comment]
Hi @klauskiwi ,
Thank you for providing this information about op-test, I will research and clarify the reason ASAP.
In addition, this is our latest skiboot version [https://lists.ozlabs.org/pipermail/skiboot/2020-September/017274.html](https://lists.ozlabs.org/pipermail/skiboot/2020-September/017274.html) and the members also gave feedback. It seems to be merged soon.

**Comment by klauskiwi** [comment]
@LuluTHSu Mowgli support was added with the new Skiboot PR here - https://github.com/open-power/op-build/pull/3865

Please re-base and force-push here, or open a new PR

**Comment by klauskiwi** [comment]
> 
> 
> @LuluTHSu Mowgli support was added with the new Skiboot PR here - #3865
> 
> Please re-base and force-push here, or open a new PR

Rebased PR in #3871

**Pull request closed without merging**
