### PR TITLE
Enable secure boot support in skiroot

### PR DESCRIPTION
**Pull request by naynajain**
This pull request is to enable support of secure boot function in skiroot. It includes:
1. Backported secure boot patches from kernel v5.5 to v5.4.
2. Backported xmon lockdown patch from kernel v5.5.
3. Adds secure boot relevant CONFIGs i.e. IMA and related one. in skiroot_defconfig.

Thanks & Regards,
       - Nayna

### CODE REVIEW

**Comment by klauskiwi** [comment]
Nayna -
 * for the Kernel support, I think we need to wait for Kernel 5.5 to be the op-build default. It is already theoretically supported, but not selected by default until we move to a newer buildroot that officially supports it.

 * as for the config file changes, you are making them in a way that will affect (almost) every platform we have.. How far have you tested them on say Power8 and zz? Please clarify if this feature is intended for every platform, and why not if otherwise.

Either way, I'll try to trigger the CI testing for this. I'm suspecting that the increased kernel size might not fit some platform's PNOR layout

**Comment by klauskiwi** [comment]
ok to test

**Comment by klauskiwi** [comment]
ok to test

**Comment by klauskiwi** [comment]
@naynajain CI build on x86_64 is failing:
```
security/integrity/platform_certs/load_powerpc.c:16:29: fatal error: keyring_handler.h: No such file or directory
 #include "keyring_handler.h"
                             ^
compilation terminated.
  CC      drivers/block/brd.o
make[3]: *** [scripts/Makefile.build:266: security/integrity/platform_certs/load_powerpc.o] Error 1
  CC      block/blk-core.o
  CC      fs/nls/nls_ascii.o
  CC      fs/nls/nls_iso8859-1.o
  CC      drivers/block/loop.o
  CC [M]  fs/jbd2/recovery.o
  CC      block/blk-sysfs.o
make[2]: *** [scripts/Makefile.build:500: security/integrity] Error 2
make[1]: *** [Makefile:1691: security] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by naynajain** [comment]
> Nayna -
> 
>     * for the Kernel support, I think we need to wait for Kernel 5.5 to be the op-build default. It is already theoretically supported, but not selected by default until we move to a newer buildroot that officially supports it.
> 
>     * as for the config file changes, you are making them in a way that will affect (almost) every platform we have.. How far have you tested them on say Power8 and zz? Please clarify if this feature is intended for every platform, and why not if otherwise.
> 
> 
> Either way, I'll try to trigger the CI testing for this. I'm suspecting that the increased kernel size might not fit some platform's PNOR layout

What do you mean by wait for kernel 5.5 ? I thought op-build is going to use LTS kernel (5.4) . These patches are already upstreamed in kernel 5.5. I think I am missing some context.

The feature is intended only for P9 witherspoon and I had built and tested only on the same.
This feature support in kernel is also dependent on skiboot enablement which is getting done only for witherspoon platform.

Thanks & Regards,
      - Nayna

**Comment by naynajain** [comment]
> @naynajain CI build on x86_64 is failing:
> 
> ```
> security/integrity/platform_certs/load_powerpc.c:16:29: fatal error: keyring_handler.h: No such file or directory
>  #include "keyring_handler.h"
>                              ^
> compilation terminated.
>   CC      drivers/block/brd.o
> make[3]: *** [scripts/Makefile.build:266: security/integrity/platform_certs/load_powerpc.o] Error 1
>   CC      block/blk-core.o
>   CC      fs/nls/nls_ascii.o
>   CC      fs/nls/nls_iso8859-1.o
>   CC      drivers/block/loop.o
>   CC [M]  fs/jbd2/recovery.o
>   CC      block/blk-sysfs.o
> make[2]: *** [scripts/Makefile.build:500: security/integrity] Error 2
> make[1]: *** [Makefile:1691: security] Error 2
> make[1]: *** Waiting for unfinished jobs....
> ```

I am not having permission to read when I click on "Details" link to check for the issue. Can you please get me the permission to look at the error ?

Thanks & Regards,
      - Nayna

**Comment by naynajain** [comment]
Force pushed the skiboot-stb branch with the fix.

**Comment by klauskiwi** [comment]
ok to test

**Comment by klauskiwi** [comment]
retest this please

**Comment by klauskiwi** [comment]
> 
> 
> Force pushed the skiboot-stb branch with the fix.

Are you sure? I don't see a message on Github that this happened (as it usually happens) and looking at your branch looks like the last commit was on May 14

**Comment by klauskiwi** [comment]
I somehow missed your comment below... 
 
> > Nayna -
> > ```
> > * for the Kernel support, I think we need to wait for Kernel 5.5 to be the op-build default. It is already theoretically supported, but not selected by default until we move to a newer buildroot that officially supports it.
> > 
> > * as for the config file changes, you are making them in a way that will affect (almost) every platform we have.. How far have you tested them on say Power8 and zz? Please clarify if this feature is intended for every platform, and why not if otherwise.
> > ```
> > 
> > 
> > Either way, I'll try to trigger the CI testing for this. I'm suspecting that the increased kernel size might not fit some platform's PNOR layout
> 
> What do you mean by wait for kernel 5.5 ? I thought op-build is going to use LTS kernel (5.4) . These patches are already upstreamed in kernel 5.5. I think I am missing some context.

op-build-2.5 (rc1 was tagged a few days ago) is using LTS kernel 5.4, and momentarily we're also using it upstream. But as soon as we are able to, we should move to a newer buildroot and kernel...

> The feature is intended only for P9 witherspoon and I had built and tested only on the same.
> This feature support in kernel is also dependent on skiboot enablement which is getting done only for witherspoon platform.

I understand this was tested on Witherspoon only, but in order to avoid fragmentation as much as possible, we should try to make it "available" for as many platforms as technically possible. Let's have this discussion on the mailing-list if possible.. We will probably need Hostboot folks..

**Comment by stewartsmith** [comment]
Considering Witherspoon isn't a widely available platform, is there any consideration to getting this going on one of the more publicly accessible boxes? Perhaps a development guide for enabling it?

**Comment by klauskiwi** [comment]
Taking a second look at your PR, I'm having mixed feelings about having one commit pushing all the patches, while another commit enables them in the kernel config..

Considering we will merge them and not rebase them, should be fine in case we need to bissect things, but still...

Just thinking out loud, nothing to do here

**Comment by hegdevasant** [comment]
I think kernel patches should go to open-power/linux tree.

Something changed in process. @shenki  ?

-Vasant

**Comment by klauskiwi** [comment]
retest this please

**Comment by klauskiwi** [comment]
@naynajain are there testcases in op-test? Should we enable them in CI and re-run the tests?

**Comment by naynajain** [comment]
> @naynajain how do we make forward progress with this? Are you planning on sending the kernel patches to the OpenPower-firmware mailing-list?

Sorry for delay in posting.. By the time we had skiroot building successfully here, I was about to take vacation. Just came back on Tuesday. Still catching up, I will be posting the patches early next week to openpower-firmware mailing list.

**Comment by naynajain** [comment]
Hi,

I have posted all the patches to openpower-firmware mailing list today.

Thanks & Regards,
      - Nayna

**Comment by klauskiwi** [comment]
@naynajain 

 with the patches you posted on the mailing-list merged (#3720), what do you want to do with this PR? What is left?

**Comment by naynajain** [comment]
> @naynajain
> 
> with the patches you posted on the mailing-list merged (#3720), what do you want to do with this PR? What is left?

Sorry for late response.. Patches are also merged now upstream. So, from my side I am done and PR can be closed.

Thanks & Regards,
     - Nayna

**Pull request closed without merging**
