### PR TITLE
vesnin: Bump version of machine xml

### PR DESCRIPTION
**Pull request by artemsen**
Artem Senichev (2):
      Disable PCIe port bifurcation
      Fix IBSCOM_MCS_BASE_ADDR formatting

Signed-off-by: Artem Senichev <a.senichev@yadro.com>

### CODE REVIEW

**Comment by artemsen** [comment]
Relates to http://patchwork.ozlabs.org/patch/1065584/

**Comment by stewart-ibm** [comment]
ok to test

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
It seems some of our CI was having a bad day (for a couple of days), so running it through again.

This shouldn't be a problem to get merged for v2.3 though.

**Comment by stewart-ibm** [comment]
retest this please

**Comment by stewart-ibm** [comment]
The CI in Austin is just broken.

This looks fine, so merging.

**Pull request merged**
