### PR TITLE
kernel: Move to Linux v5.2.5-openpower1

### PR DESCRIPTION
**Pull request by shenki**
PowerPC related fixes:

 powerpc/pmu: Set pmcregs_in_use in paca when running as LPAR
 powerpc/tm: Fix oops on sigreturn on systems without TM
 powerpc/mm: Limit rma_size to 1TB when running without HV mode
 powerpc/xive: Fix loop exit-condition in xive_find_target_in_mask()
 powerpc/dma: Fix invalid DMA mmap behavior
 powerpc/eeh: Handle hugepages in ioremap space
 powerpc/boot: add {get, put}_unaligned_be32 to xz_config.h
 powerpc/irq: Don't WARN continuously in arch_local_irq_restore()
 powerpc/mm: Handle page table allocation failures
 powerpc/mm: mark more tlb functions as __always_inline
 powerpc: silence a -Wcast-function-type warning in dawr_write_file_bool
 powerpc/xmon: Fix disabling tracing while in xmon
 powerpc/cacheflush: fix variable set but not used
 powerpc/pci/of: Fix OF flags parsing for 64bit BARs
 powerpc/powernv: Fix stale iommu table base after VFIO
 powerpc/powernv/idle: Fix restore of SPRN_LDBAR for POWER9 stop state.
 powerpc/powernv/npu: Fix reference leak
 powerpc/watchpoint: Restore NV GPRs while returning from exception
 mm/nvdimm: add is_ioremap_addr and use that to check ioremap address

Signed-off-by: Joel Stanley <joel@jms.id.au>

### CODE REVIEW

**Comment by shenki** [comment]
This failed building hostboot for witherspoon:
```
cd build/buildpnor/ && /usr/bin/make --no-print-directory --no-builtin-rules --no-builtin-variables buildpnor
make[6]: Nothing to be done for 'buildpnor'.
true
../src/build/trace/tracehash_hb.pl -c -d ../obj -s ../img/hbotStringFile
    GENLIST    hbibl
ERROR: ../img/hbibl.bin too large. Max allowed size is 32768
    GENLIST    hbicore
makefile:434: recipe for target 'imgsizecheck' failed
make[5]: *** [imgsizecheck] Error 1
    GENLIST    hbicore_test
```

**Comment by shenki** [comment]
Cory told me:
> I've seen a couple versions of the HBBL too large fail in the last few days.  They passed when retriggered but needs further inspection.

**Comment by shenki** [comment]
retest this please

**Comment by shenki** [comment]
retest this please

**Comment by shenki** [comment]
retest this please

**Comment by shenki** [comment]
retest this please

**Comment by cvswen** [comment]
Build timed out (after 90 minutes). Marking the build as failed.
Don't know if this is related to the HBBL problem.
Looking into the HBBL problem today.

**Comment by shenki** [comment]
All green now! Merging

**Pull request merged**
