### PR TITLE
buildroot: Update to 2018.02

### PR DESCRIPTION
**Pull request by shenki**
Release notes and announcement:

 https://git.buildroot.net/buildroot/plain/CHANGES?id=2018.02

 http://lists.busybox.net/pipermail/buildroot/2018-March/215002.html

Updated packages:

 rsync: 3.1.2 -> 3.1.3
 glibc: glibc-2.26-73 -> glibc-2.26-146
 linux-firmware: a3a26af24e29 -> 65b1c68c63f9
 util-linux: 2.31 -> 2.31.1
 eudev: 3.2.4 -> 3.2.5

Updated host packages:

 libxml2: 2.9.5 -> 2.9.7
 binutils: 2.28.1 -> 2.29.1

Signed-off-by: Joel Stanley <joel@jms.id.au>

### CODE REVIEW

**Comment by shenki** [comment]
Build tested on ppc64le and amd64. Boot tested on Romulus.

ppc64le appears to be broken due to a hostboot perl bug, but that is not a regression caused by this PR.

**Comment by stewart-ibm** [comment]
```
ERROR: PnorUtils::checkSpaceConstraints: Image provided (/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/firestone/OS/rhel6.4/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//zImage.epapr) has size (15947032) which is greater than allocated space (15728640) for section=BOOTKERNEL.```

Hrm... this seems to be the case for firestone, barrelleye, garrison and habanero (weirdly not palmetto though).

and then for firenze and pseries:
```
+ make --directory=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/firenze/OS/rhel6.4/build/op-build/buildroot O=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/firenze/OS/rhel6.4/build/op-build/output
make: Entering directory `/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/firenze/OS/rhel6.4/build/op-build/buildroot'
/usr/bin/make -j1 O=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/firenze/OS/rhel6.4/build/op-build/output HOSTCC="/usr/bin/gcc" HOSTCXX="/usr/bin/g++" silentoldconfig
  GEN     /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/firenze/OS/rhel6.4/build/op-build/output/Makefile
Your Python installation is not complete enough: argparse module is missing
make[1]: *** [core-dependencies] Error 1
make: *** [_all] Error 2
make: Leaving directory `/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi/CONFIG/firenze/OS/rhel6.4/build/op-build/buildroot'
```

So that's probably another product of broken build infrastructure.

**Comment by shenki** [comment]
Palmetto disables most of the locales, so it is not surprising that it results in a smaller image. I'll do a firestone build and see what is filling it up.

Do we have a depreciation policy for any of these old configurations? I only test on palmetto and romulus.

**Comment by shenki** [comment]
@stewart-ibm I did a build of firestone and it worked fine. Do your build machines do clobber the build directory before starting a build?

```
joel@ka3:/scratch/joel/op-build$ grep BR2_DEFCONFIG output/.config
BR2_DEFCONFIG="/scratch/joel/op-build/openpower/configs/firestone_defconfig"
joel@ka3:/scratch/joel/op-build$ git describe 
v1.21-rc2-59-g32d52f8
joel@ka3:/scratch/joel/op-build$ ls -la output/images/
total 310404
drwxr-xr-x 2 joel users     4096 Mar  6 18:13 .
drwxr-xr-x 6 joel users     4096 Mar  6 17:37 ..
-rwxr-xr-x 1 joel users   106496 Mar  6 18:03 cappucode.bin
-rwxr-xr-x 1 joel users 67108864 Mar  6 18:13 firestone.pnor
-rwxr-xr-x 1 joel users 20090880 Mar  6 18:13 firestone.pnor.squashfs.tar
-rwxr-xr-x 1 joel users 33554432 Mar  6 18:13 firestone_update.pnor
-rw-r--r-- 1 joel users 52472925 Mar  6 18:13 host_fw_debug.tar
-rwxr-xr-x 1 joel users    12288 Mar  6 18:11 ima_catalog.bin
-rw-r--r-- 1 joel users 58090496 Mar  6 18:09 rootfs.cpio
-rw-r--r-- 1 joel users 10518100 Mar  6 18:10 rootfs.cpio.xz
-rw-r--r-- 1 joel users 58562560 Mar  6 18:11 rootfs.tar
-rwxr-xr-x 1 joel users  1400075 Mar  6 18:13 skiboot.lid
-rw-r--r-- 1 joel users   362916 Mar  6 18:13 skiboot.lid.bin
-rw-r--r-- 1 joel users 15652120 Mar  6 18:11 zImage.epapr
```

**Comment by stewart-ibm** [comment]
Joel Stanley <notifications@github.com> writes:
> Do we have a depreciation policy for any of these old configurations?
> I only test on palmetto and romulus.

We don't.

It's kind of "until people stop using them" or it becomes overly burdensome.

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by stewart-ibm** [comment]
Joel Stanley <notifications@github.com> writes:
> @stewart-ibm I did a build of firestone and it worked fine. Do your
> build machines do clobber the build directory before starting a build?

Umm... I have no idea what they do.

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by shenki** [comment]
retest this please

**Comment by stewart-ibm** [comment]
retest this please

**Comment by shenki** [comment]
Regarding RHEL6: builds are still failing on gfw264. However, if they happen to land on gfw272 then they succeed.

The ubuntu-ppc64le builder succeeded for garrison and witherspoon is still going.

All images built successfully on the ozlabs Jenkins (the previous job passed for all but pseries, and pseries has passed in the current job).

**Comment by stewart-ibm** [comment]
Merged as of 9b1006d43737e31adc54df36340b817d5364d54f

I fixed pseries defconfig and the firmware-whitelist problem we identified that was blowing out the p8 BOOTKERNEL partition size.

**Pull request closed without merging**
