### PR TITLE
Enable IPL-Time Checkstop Analysis

### PR DESCRIPTION
**Pull request by IlyaSmirnov91**
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1373)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch for testing?

**Comment by stewart-ibm** [comment]
ok to test

**Comment by wghoffa** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/open-power/op-build/1373)*

**Comment by wghoffa** [comment]
retest this please

**Pull request closed without merging**
