### PR TITLE
Update zaius.config to start OCC

### PR DESCRIPTION
**Pull request by agangidi53**
Signed-off-by: Adi Gangidi adi.gangidi@rackspace.com

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1114)

### CODE REVIEW

**Comment by wghoffa** [comment]
retest this please

**Comment by wghoffa** [comment]
retest this please

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch?

**Comment by agangidi53** [comment]
same as this https://github.com/open-power/op-build/pull/1114

**Comment by wghoffa** [comment]
I apologize, I should have just retested this. Now that we moved up FW levels this will work. I merged a comparable change here: https://github.com/open-power/op-build/pull/1156

**Comment by wghoffa** [comment]
Comparable content merged yesterday.

**Pull request closed without merging**
