### PR TITLE
Update Petitboot & Skiboot for v1.10 stable branch

### PR DESCRIPTION
**Pull request by sammj**
Bump Petitboot and Skiboot up to more recent versions so we can build a more up to date image while remaining on the v1.10 stable base.

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1052)

### CODE REVIEW

**Comment by sammj** [comment]
Some ubuntu builds are failing because the v1.10 branch doesn't have the defconfigs for the p9 platforms, but for some reason a few of the rhel-based tests are failing because `xz 5.2.2` can't be downloaded.. even though ubuntu can download the same thing fine. Just an issue with the build host?

**Comment by stewart-ibm** [comment]
@e-liner the CI system is still broken - it tries to build platforms that don't exist

**Comment by stewart-ibm** [comment]
Merged to op-build-1.10.y as of 23a86c9878e3

**Comment by stewart-ibm** [comment]
Sam Mendoza-Jonas <notifications@github.com> writes:
> Some ubuntu builds are failing because the v1.10 branch doesn't have
> the defconfigs for the p9 platforms, but for some reason a few of the
> rhel-based tests are failing because `xz 5.2.2` can't be
> downloaded.. even though ubuntu can download the same thing fine. Just
> an issue with the build host?

Probably. I'm ignoring the CI.

-- 
Stewart Smith
OPAL Architect, IBM.

**Pull request closed without merging**
