### PR TITLE
zz/kernel: Move to v5.10.194-openpower1

### PR DESCRIPTION
**Pull request by rarbab**
This includes changes from 2022 that went into the last zz build (`sapphire-v6.6.6-zz-2022-01-07`). They are in @legoater 's repo but I think he may have forgotten to get them pulled here.

On top of that I've added a commit to bump the kernel again, to v5.10.194.

### CODE REVIEW

**Comment by fspbld** [comment]
ok to test

**Comment by dcrowell77** [comment]
retest this please

**Comment by dcrowell77** [comment]
retest this please

**Comment by dcrowell77** [comment]
retest this please

**Pull request merged**
