### PR TITLE
Update firestone-xml commit and add IPMI to firestone.config

### PR DESCRIPTION
**Pull request by ploetzma**

### CODE REVIEW

**Comment by ploetzma** [comment]
This is now breaking pass-1 Firestones. Hold off on this.

**Comment by ploetzma** [comment]
Okay, this is ready to be picked up. Pass-1 Systems needed Bill Schwartz's backplane VPD change, I have added it as a patch. 

The new patch encompasses current hostboot-0004, so I have removed hostboot-0004

**Comment by rjknight** [comment]
Please have Sertac include the .rpt file, it will help to determine if there are duplicate sensors defined and also provides a quick reference for the sensor numbers.

**Comment by williamspatrick** [comment]
Manually cherry-picked commits onto master-next.

**Pull request closed without merging**
