### PR TITLE
Barreleye platform definition for buildroot.

### PR DESCRIPTION
**Pull request by johnhihi**

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Hi!

When applied against master-next, this patch has the following issues:
[stewart@birb op-build]$ op-build 
make: Entering directory '/home/stewart/op-build/buildroot'
Makefile.legacy:12: *** "You have legacy configuration in your .config! Please check your configuration.".  Stop.
Makefile:36: recipe for target '_all' failed
make: *** [_all] Error 2


Which are the following options:
 │ BR2_PACKAGE_LINUX_FIRMWARE_CXGB4:                                       │  
  │                                                                         │  
  │ The Chelsio T4 option BR2_PACKAGE_LINUX_FIRMWARE_CXGB4                  │  
  │ has been renamed to BR2_PACKAGE_LINUX_FIRMWARE_CXGB4_T4                 │  
  │ to better account for the fact that a T5 variant exists.  

So I've changed it accordingly, and updated kernel version.

Merged to master-next as of 7ff102a

**Comment by johnhihi** [comment]
Got it. Thank you.

**Comment by johnhihi** [comment]
Hi @stewart-ibm 

We will also need this commit in skiboot https://github.com/open-power/skiboot/commit/9a25fcc0503488c63c4443a8dde9f77e90c314a5
Will you help us to included it in op-build?

**Comment by stewart-ibm** [comment]
Sure - so, I merged in the skiboot support yesterday, I'm going to do a skiboot-5.2.0-rc2 shortly, and when I do, I'll bump barreleye up to that in op-build master-next (along with garrison).

I'd be happy to also backport barreleye support into the skiboot stable branch, but I'll leave it up to you if you want it there or are happy with the upcoming 5.2 release.

**Comment by johnhihi** [comment]
I'm sorry, I could not understand the difference between master and stable branch.
It looks like people clone the op-build and make PNOR will checkout the master branch of packages.
So I am wondering what is stable branch used for? What is the relationship between master and stable branch?

**Comment by stewart-ibm** [comment]
For skiboot, we have the master branch where development occurs, and a stable branch where stable releases are made.

So we currently have:
- skiboot-5.1.13 <- this is stable, it is what palmetto, firestone and habanero build with
- skiboot-5.2.0-rc1 <- this is a release candidate for the next stable release currently undergoing testing and is the basis for the garisson platform, as it requires NVLINK enablement which is new to skiboot-5.2.0.
- skiboot master - the development branch, where skiboot-5.2.0-rc2 is about to be tagged.

This way we can keep platforms such as palmetto, firestone and habanero running on a stable branch with only minimal bug fixes backported while doing new enablement work in master.

**Comment by johnhihi** [comment]
Thanks for your detail illustration. Now I can understand.

These code we have run on skiboot-5.1.5 without issue.
Please also backport barreleye support into the skiboot stable branch and the upcoming 5.2 release.
Thanks again.

**Comment by stewart-ibm** [comment]
https://github.com/open-power/op-build/pull/383 brings skiboot-5.2.0-rc2 into master-next (which will become op-build v1.8) for garisson and barreleye.

Since you mention skiboot 5.1.5, I'm guessing your current work is based on op-build v1.7

If you plan to move to op-build 1.8 when it's released (current plan is mid march), I may just leave barelleye in skiboot 5.2.0 and you can pick it up there. However, if you plan to base off 1.7, I could bring it back into skiboot 5.1 (and do a 5.1.15 release) and you could put that skiboot into your 1.7 based build.

**Comment by johnhihi** [comment]
Yes, you are right. We are now work based on op-build v1.7.
We will follow up your op-build 1.8 release, so I think we wont need it backport to 1.7 and do a new release. Just leave it to op-build 1.8 release would be fine. Thanks.

BTW, I notice that the token BR2_GLIBC_VERSION_2_23=y in barreleye_defconfig is missing.
Could you help to put it back? I think it will be faster than I creating a pull request.

**Comment by stewart-ibm** [comment]
Sure, no worries.

**Comment by johnhihi** [comment]
:+1:  Many thanks :)

**Pull request closed without merging**
