### PR TITLE
POWER9 bump skiboot to c3e405b3b1e0c47efbbf31ce37ea02e9a1e005e3

### PR DESCRIPTION
**Pull request by stewart-ibm**
Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/993)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
@e-liner what is going on with the testing? It's giving me some weird Robot test failure that I can't view the logs of.

Where do these tests come from?

```
Opening Robot Framework log failed

    Verify that you have JavaScript enabled in your browser.
    Make sure you are using a modern enough browser. Firefox 3.5, IE 8, or equivalent is required, newer browsers are recommended.
    Check are there messages in your browser's JavaScript error log. Please report the problem if you suspect you have encountered a bug.

```

That is all I get.

So, I'm going to merge this anyway, it passes op-test-framework tests, and on witherspoon with some hostboot revisions you need an extra patch due to varying HB HDAT output anyway, which the patch was sent late yesterday to fix.

**Comment by e-liner** [comment]
@stewart-ibm This is the P9 HW test that was implemented.   This ended up not being a failure that was caused by you (it's a known issue that will hopefully be solved with today's pull request), but in the future could you give me a chance to look at failures before you merge things?
Also from the error you got, I would think that you need to update your browser to see these new errors.

**Comment by stewart-ibm** [comment]
e-liner <notifications@github.com> writes:
> @stewart-ibm This is the P9 HW test that was implemented.   This ended up not being a failure that was caused by you (it's a known issue that will hopefully be solved with today's pull request), but in the future could you give me a chance to look at failures before you merge things?
> Also from the error you got, I would think that you need to update
> your browser to see these new errors.

I'm running Firefox 52.0.

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by stewart-ibm** [comment]
e-liner <notifications@github.com> writes:
> @stewart-ibm This is the P9 HW test that was implemented.   This ended
> up not being a failure that was caused by you (it's a known issue that
> will hopefully be solved with today's pull request), but in the future
> could you give me a chance to look at failures before you merge
> things?

stopping merging things isn't really ideal, but I can at least point you
to such failures and when I'm going to ignore them and hopefully the p9
tests can become reliable.

I'd prefer to see op-test-framework start to be being run though.

> Also from the error you got, I would think that you need to update
> your browser to see these new errors.

It caused problems again with #999, so I again ignored it.

-- 
Stewart Smith
OPAL Architect, IBM.

**Pull request merged**
