### PR TITLE
Enable Hostboot Runtime

### PR DESCRIPTION
**Pull request by wghoffa**
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1031)

### CODE REVIEW

**Comment by pragupta** [comment]
retest this please

**Comment by williamspatrick** [comment]
Good to go?

**Comment by wghoffa** [comment]
Yes good to go, I've done many tests on Witherspoon locally that have worked just fine. I also see CI agrees Zaius works.

**Comment by pragupta** [comment]
retest this please

**Pull request merged**
