### PR TITLE
configs: Add pseries platform

### PR DESCRIPTION
**Pull request by sammj**
Add a new kernel defconfig based off skiroot_defconfig which includes
pseries support and support for some commonly used virtual devices.
Add the pseries_defconfig platform which builds a kernel and rootfs
based on this config.

Signed-off-by: Samuel Mendoza-Jonas <sam@mendozajonas.com>

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1201)

### CODE REVIEW

**Comment by stewart-ibm** [comment]
Can one of the admins verify this patch for testing?

**Comment by stewart-ibm** [comment]
ok to test

**Comment by stewart-ibm** [comment]
retest this please

**Comment by sammj** [comment]
Updated commit to catch kernel update.
(If everyone's generally happy with this it would be good to merge it so it doesn't need to keep catching updates).

**Pull request merged**
