### PR TITLE
Support Python3 as default /usr/bin/python

### PR DESCRIPTION
**Pull request by stewartsmith**
Note: this includes two patches that have been submitted upstream:

https://github.com/open-power/sbe/pull/17
and
https://github.com/open-power/pnor/pull/131

### CODE REVIEW

**Comment by hegdevasant** [comment]
@dcrowell77 / @rajadas2 Can you guys look into this one?


-Vasant

**Comment by dcrowell77** [comment]
If the changes are being submitted to the main repo, why do we need patches?

**Comment by stewartsmith** [comment]
I’ve seen it take months/years to get review there. Feel free to prove me wrong :)

**Comment by runlevel5** [comment]
@stewartsmith wondering if you could re-base this PR? Thanks much in advance

**Comment by stewartsmith** [comment]
There needs to be some agreement from SBE and PNOR projects to take the patches and merge them at a time where things will continue to work.

**Comment by klauskiwi** [comment]
Recent testing on upstream showed that this is fixed (i.e., we are able to build using python3 as the default python). Closing

**Pull request closed without merging**
