### PR TITLE
[RFC] p10/kernel: Move to v5.10.50-openpower1

### PR DESCRIPTION
**Pull request by hegdevasant**
- Updated denali and rainier configs
- Manually rebased to v5.10.50 kernel
- Removed openpower/linux-p10 directory
- Updated skiroot_defconfig based on upstream master

Signed-off-by: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by hegdevasant** [comment]
retest this please

**Comment by hegdevasant** [comment]
retest this please

**Comment by hegdevasant** [comment]
retest this please

**Comment by hegdevasant** [comment]
retest this please

**Comment by hegdevasant** [comment]
retest this please

**Comment by hegdevasant** [comment]
I have tried rainier image built on RHEL7 system and tested in rainier system. it works fine.

We are trying to sort out build issues on ppc64le systems. We will hold merging this patch until we sort out those issues.

-Vasant

**Comment by camvanng** [comment]
test p10 ubuntu

**Comment by hegdevasant** [comment]
retest this please

**Comment by hegdevasant** [comment]
retest this please

**Comment by IlyaSmirnov91** [comment]
retest this please

**Comment by camvanng** [comment]
test p10 ubuntu

**Comment by IlyaSmirnov91** [comment]
Ubuntu CI passes on Ubuntu 21.04 locally when this PR is manually rebased on top of master-p10.

**Pull request merged**
