### PR TITLE
Build PPE42 packages

### PR DESCRIPTION
**Pull request by dgilbert999**
These changes require  packages ppe42-binutils and ppe42-gcc.
Don't pull until required packages are publicly available.

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/560)

### CODE REVIEW

**Comment by williamspatrick** [comment]
Delay merging this until after we close 1.10.

**Comment by ploetzma** [comment]
Please retest this

**Comment by jazurin** [comment]
retest this please

**Comment by williamspatrick** [comment]
Need this rebased and all 3 commits should be squashed into 1.  The differences between them is not interesting from a historical perspective.

**Comment by ploetzma** [comment]
merged in https://github.com/open-power/op-build/pull/613/

This can be closed.

**Pull request closed without merging**
