### PR TITLE
Bump kernel to 5.10.197

### PR DESCRIPTION
**Pull request by runlevel5**
## Changes

* Bump kernel to 5.10.197
* Bump to GCC 11

### CODE REVIEW

**Comment by IlyaSmirnov91** [comment]
ok to test

**Comment by IlyaSmirnov91** [comment]
@runlevel5 , the compilation fails with this error:


>>> linux-headers 5.10.197 Patching
for p in /tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-4671/CONFIG/witherspoon/OS/ubuntu/build/op-build/openpower/linux ; do if test -d $p ; then PATH=/tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-4671/CONFIG/witherspoon/OS/ubuntu/build/op-build/output/host/bin:$PATH support/scripts/apply-patches.sh  /tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-4671/CONFIG/witherspoon/OS/ubuntu/build/op-build/output/build/linux-headers-5.10.197 $p \*.patch || exit 1 ; else PATH=/tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-4671/CONFIG/witherspoon/OS/ubuntu/build/op-build/output/host/bin:$PATH support/scripts/apply-patches.sh  /tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-4671/CONFIG/witherspoon/OS/ubuntu/build/op-build/output/build/linux-headers-5.10.197 `dirname $p` `basename $p` || exit 1; fi done

Applying 0001-xhci-Reset-controller-on-xhci-shutdown.patch using patch: 
patching file drivers/usb/host/xhci.c
Hunk #1 succeeded at 816 (offset 4 lines).

Applying 0002-Release-OpenPower-kernel.patch using patch: 
patching file Makefile
Hunk #1 FAILED at 2.
1 out of 1 hunk FAILED -- saving rejects to file Makefile.rej
make: *** [package/pkg-generic.mk:251: /tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-4671/CONFIG/witherspoon/OS/ubuntu/build/op-build/output/build/linux-headers-5.10.197/.stamp_patched] Error 1
make: Leaving directory '/tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-4671/CONFIG/witherspoon/OS/ubuntu/build/op-build/buildroot'

It can't apply the patch. Maybe we don't even need that patch anymore?

**Comment by runlevel5** [comment]
@IlyaSmirnov91 good catch, let me have a look into why it does not apply cleanly with `witherspoon`

**Comment by runlevel5** [comment]
@IlyaSmirnov91 just pushed, let's try again

**Pull request merged**
