### PR TITLE
buildroot: Move to 2019.05.1 stable release

### PR DESCRIPTION
**Pull request by shenki**
Upstream release notes:

 http://git.buildroot.net/buildroot/plain/CHANGES?id=2019.05.1
 http://lists.busybox.net/pipermail/buildroot/2019-July/254105.html

Note that this includes an upstreamed version of the localedef patch
that op-build was carrying.

Signed-off-by: Joel Stanley <joel@jms.id.au>

### CODE REVIEW

**Comment by stewart-ibm** [comment]
retest this please

**Comment by shenki** [comment]
The RHEL7 CI is failing to host-localedef 2.29-11-ge28ad442e73b00ae2047d89c8cc7f9b2a0de5436 due to this:

```
*** These critical programs are missing or too old: compiler
```

**Comment by shenki** [comment]
retest this please

**Comment by shenki** [comment]
Dan has been working on fixing the CI machines to use GCC 8 as their host compiler, which will resolve the glibc/locale build issue

 We expect this CI run to go green as Dan fixed up the job, but should wait until all of the CI slaves have the new compiler installed before merging.

**Comment by danlarson-ibm** [comment]
I've fixed up GCC on the machines. Got you green for that test

**Pull request merged**
