### PR TITLE
Integrate Firestone build files

### PR DESCRIPTION
**Pull request by rjknight**
I re-based my commit on top of Bill package updates.  This commit will enable the building of the Firestone pnor image from the serverwhiz2 mrw file.

### CODE REVIEW

**Comment by ploetzma** [comment]
This pull request is still valid, and if I were to take it over now I would not have any changes until Norm get's me a new firestone xml to actually do the serverwiz2 processing.

This can be merged if you agree with the changes Patrick.

**Comment by williamspatrick** [comment]
Is this now deprecated in favor of #57 and can be closed?

**Comment by ploetzma** [comment]
Yes, that is correct @williamspatrick

**Comment by rjknight** [comment]
Closing, merged in #57

**Pull request closed without merging**
