### PR TITLE
skiboot v6.4-33-g2554cac82da5

### PR DESCRIPTION
**Pull request by stewartsmith**
Andrew Geissler (1):
      Support BMC IPMI heartbeat command

Dan Crowell (1):
      Updating shared constants for HBRT

Dan Horák (1):
      gard: fix installation rule

Nicholas Piggin (1):
      asm/head: set skiboot TOC in interrupt handler entry

Oliver O'Halloran (2):
      Makefiles: Remove --Wno-stringop-truncation
      hw: Put SPDX on new files

Reza Arbab (8):
      Dedup $(HW_OBJS)
      hw/phys-map: Add pvr argument to phys_map_init()
      hw/phys-map: Add Axone memory map
      npu2: Prepare purge_l2_l3_caches() for reuse
      npu2: Refactor NPU OPAL calls
      npu2: Add checks to npu2-only codepaths
      hw: Introduce npu3
      Add Swift platform

Stewart Smith (4):
      SPDX-ify all skiboot code
      travis: Enable fedora30 for ppc64le
      travis: remove fedora29
      travis: do gcov builds on fedora30

Signed-off-by: Stewart Smith <stewart@linux.ibm.com>

### CODE REVIEW

**Comment by stewartsmith** [comment]
Anyone have any hints on why one of the CI jobs failed? I can’t see it.

**Comment by shenki** [comment]
This is the second to last step:
```
cd /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch/ && /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/hostboot_build_images//genPnorImages.pl --binDir /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch/ --systemBinFiles HBD=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HBD.staged,HDAT=EMPTY,OCMBFW=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//OCMBFW.staged,HBRT=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HBRT.staged,ATTR_TMP=EMPTY,HBB=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HBB.staged,OCC=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//OCC.staged,ATTR_PERM=EMPTY,DJVPD=EMPTY,GUARD=EMPTY,IMA_CATALOG=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//IMA_CATALOG.staged,HBEL=EMPTY,BOOTKERNEL=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//BOOTKERNEL.staged,WOFDATA=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//WOFDATA.staged,SECBOOT=EMPTY,CVPD=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//CVPD.staged,RINGOVD=EMPTY,HBI=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HBI.staged,VERSION=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//VERSION.staged,HBBL=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HBBL.staged,FIRDATA=EMPTY,SBE=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//SBE.staged,HCODE=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HCODE.staged,SBKT=EMPTY,MEMD=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//MEMD.staged,PAYLOAD=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//PAYLOAD.staged,MVPD=EMPTY,NVRAM=EMPTY,CAPP=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//CAPP.staged --pnorLayout /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/build/openpower-pnor-03469302c58f65ff57082792cdda159795f6e488/p9Layouts/defaultPnorLayout_64.xml --secureboot  --sign-mode development --hwKeyHashFile /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/hostboot_build_images//imprintHwKeyHash
HBBL cannot fit HW Keys' Hash (64 bytes) at the end without overwriting real data at /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/hostboot_build_images//genPnorImages.pl line 612.

//============= Generate PNOR Image Settings ===========//
PNOR Layout = /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/build/openpower-pnor-03469302c58f65ff57082792cdda159795f6e488/p9Layouts/defaultPnorLayout_64.xml
Emit ECC-less versions of output files, when possible = No
Test Mode = No
Secureboot = Enabled
Sign Mode = development
Key Transition Mode = NA
Lab security override (valid for SBE partition only) = Yes
//======================================================//

Loading bin files...
TRACE: manipulateImages
HBBL raw size (/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HBBL.staged) (no padding/ecc) = 75256/20480
Error running command: cd /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch/ && /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/hostboot_build_images//genPnorImages.pl --binDir /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch/ --systemBinFiles HBD=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HBD.staged,HDAT=EMPTY,OCMBFW=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//OCMBFW.staged,HBRT=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HBRT.staged,ATTR_TMP=EMPTY,HBB=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HBB.staged,OCC=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//OCC.staged,ATTR_PERM=EMPTY,DJVPD=EMPTY,GUARD=EMPTY,IMA_CATALOG=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//IMA_CATALOG.staged,HBEL=EMPTY,BOOTKERNEL=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//BOOTKERNEL.staged,WOFDATA=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//WOFDATA.staged,SECBOOT=EMPTY,CVPD=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//CVPD.staged,RINGOVD=EMPTY,HBI=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HBI.staged,VERSION=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//VERSION.staged,HBBL=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HBBL.staged,FIRDATA=EMPTY,SBE=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//SBE.staged,HCODE=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HCODE.staged,SBKT=EMPTY,MEMD=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//MEMD.staged,PAYLOAD=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//PAYLOAD.staged,MVPD=EMPTY,NVRAM=EMPTY,CAPP=/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//CAPP.staged --pnorLayout /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/build/openpower-pnor-03469302c58f65ff57082792cdda159795f6e488/p9Layouts/defaultPnorLayout_64.xml --secureboot  --sign-mode development --hwKeyHashFile /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/hostboot_build_images//imprintHwKeyHash. Nonzero return code of (65280) returned.
package/pkg-generic.mk:320: recipe for target '/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/build/openpower-pnor-03469302c58f65ff57082792cdda159795f6e488/.stamp_images_installed' failed
make[1]: *** [/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/build/openpower-pnor-03469302c58f65ff57082792cdda159795f6e488/.stamp_images_installed] Error 2
Makefile:84: recipe for target '_all' failed
make: *** [_all] Error 2
make: Leaving directory '/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2416/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/buildroot'
+ '[' 2 -ne 0 ']'
+ echo 'witherspoon build failed.'
witherspoon build failed.
```

**Comment by stewartsmith** [comment]
Is the fix to just ffspart it all and get rid of the genPnorImage.pl mess?

NFI off the top of my head what could be going on there

**Comment by cvswen** [comment]
HBBL.staged) (no padding/ecc) = 75256/20480
75256 should be ~18000, blowing up here for some reason.
Seeing this on a lot of PRs lately, may pass on retry.
Looking into it.

**Comment by shenki** [comment]
retest this please

**Comment by shenki** [comment]
Still failing with the HBBL error:
```
HBBL raw size (/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2442/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HBBL.staged) (no padding/ecc) = 75256/HBBL raw size (/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/ubuntu-ppc64le-2442/CONFIG/witherspoon/OS/Ubuntu_18.04/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//HBBL.staged) (no padding/ecc) = 75256/20480
```

**Comment by hegdevasant** [comment]
@ruscur "Pending — Build triggered for merge commit." .. any idea what's pending and why?

-Vasant

**Comment by hegdevasant** [comment]
I have https://github.com/open-power/op-build/pull/3086 to push v6.5.
Hence closing this one.

-Vasant

**Pull request closed without merging**
