### PR TITLE
DO NOT MERGE: Update to latest signing project commit

### PR DESCRIPTION
**Pull request by hellerda**
Integrate the latest commit of sb-signing-utils, for testing.  (overriding the current default of tagged version v0.2)

Meant to replace PR #1447.

---
This change is [Reviewable](https://reviewable.io/reviews/open-power/op-build/1452)

### CODE REVIEW

**Comment by bofferdn** [comment]
retest this please

**Comment by bofferdn** [comment]
retest this please

**Comment by bofferdn** [comment]
retest this please

**Comment by hellerda** [comment]
Replaced by #1472

**Pull request closed without merging**
